### ISSUE TITLE
Typo in hooks section

### ISSUE THREAD

**Issue by jgsogo** [conan-io/docs#1000]
I found a typo in the Hook doc (https://docs.conan.io/en/latest/extending/hooks.html) 
-  In the Storage, activation and sharing section, there is a `hook.conf` example where it is indicated this as valid

```
 ...
 [hooks]
 attribute_checker
 conan-center
 my_custom_hook/hook.py
```

however, there is a note claiming that .py extension should not be used, so probably it should be

```
 ...
 [hooks]
 attribute_checker
 conan-center
 my_custom_hook/hook
```

_Originally posted by @alacasta in https://github.com/conan-io/conan/issues/4196#issuecomment-450912038_

**Comment by jgsogo** [comment]
What is the recommended way to activate hooks, @danimtb? I think we should document only one (unless there is a good reason to keep both documented).

**Comment by danimtb** [comment]
Yeah, this was an oversight from my side. Both ways are possible and it was done like this to "not brake" hooks already in *conan.conf*. I'd say it is less confusing to use the full path with *.py*

**Comment by jgsogo** [comment]
Maybe it is too late (it is breaking, but over experimental feature), I want you to consider the following:

Hooks will always be a python file/module, does it makes sense to use a more pythonic approach with path to modules like `my_custom_hook.hook` (where it can be both `my_custom_hook/hook.py` or `my_custom_hook/hook/__init__.py`)? 

Advantage: no need to work with paths, you can exchange a simple hook inside a `hook.py` file with a more structured one inside its own package `hook/__init__.py` without changing anything...

**Comment by danimtb** [comment]
Yes, it could make the structure more pythonic although not superuseful, but we could explore it once we develop a nice hook. I am bit concerned about the syntax with dots ``mycustomhook.hook`` as I am not sure if would work to activate the hook via ``conan get`` but we could try. Please open an issue about this in the conan repo to explore this option and the real advantages

**Comment by jgsogo** [comment]
I think it wouldn't work, it will force you to have all the plugins under the same directory (`.conan/hooks`) or already in the Python path, while the current approach allows absolute paths that can be more convenient for hooks coming from different origins.
