### ISSUE TITLE
error while cross building c++ code using conan

### ISSUE THREAD

**Issue by deekshith-elear** [conan-io/docs#1067]
Hi,
I was facing issue while cross building code for different platforms using conan

Configuration:
[settings]
os_build=Linux
arch_build=x86_64
os=Linux
arch=armv7
compiler=gcc
compiler.version=5.4
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
AR=arm-linux-gnueabihf-ar
AS=arm-linux-gnueabihf-as
CC=arm-linux-gnueabihf-gcc
CHOST=arm-linux-gnueabihf
CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=$toolchain
CONAN_CMAKE_FIND_ROOT_PATH=$toolchain
CXX=arm-linux-gnueabihf-g++
RANLIB=arm-linux-gnueabihf-ranlib
RC=arm-linux-gnueabihf-windres
STRIP=arm-linux-gnueabihf-strip
PROJECT: Installing /home/venkatadeekshith/conan_practice/mytestpkg/conanfile.py
Requirements
Packages

Cross-build from 'Linux:x86_64' to 'Linux:armv7'
PROJECT: Generator cmake created conanbuildinfo.cmake
PROJECT: Generator txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt
Project: Running build()
[ 50%] Built target hello
[100%] Built target greet

when i was checking file properties of executable it's showing host system executable other than target system executable

 file greet
greet: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=342801747a4dad070bc73cc139f1795510d6fb64, not stripped

can you people help me out to resolve this issue

**Comment by danimtb** [comment]
Hi @deekshith-elear 

Could you please indicate if you where following any section/example in the documentation?

Maybe the compiler was not picked correctly CMake in this case

**Comment by deekshith-elear** [comment]
Hi @danimtb 
I am following documentation of below link
https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#gnu-triplet-convention

**Comment by danimtb** [comment]
Could you please run the command again with this env var activated (https://docs.conan.io/en/latest/reference/env_vars.html#conan-print-run-commands) an copy the whole output here?

I would be useful to see if the configuration is being applied correctly. Thanks!

**Comment by deekshith-elear** [comment]
The out put of the command you mentioned

XDG_VTNR=7
SSH_AGENT_PID=6320
XDG_SESSION_ID=c3
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/venkatadeekshith
CLUTTER_IM_MODULE=xim
SESSION=ubuntu
GPG_AGENT_INFO=/home/venkatadeekshith/.gnupg/S.gpg-agent:0:1
TERM=xterm-256color
VTE_VERSION=4205
XDG_MENU_PREFIX=gnome-
SHELL=/bin/bash
SSH_AGENT_LAUNCHER=upstart
DERBY_HOME=/usr/lib/jvm/java-8-oracle/db
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
WINDOWID=60817418
OLDPWD=/home/venkatadeekshith/conan_practice/mytestpkg
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1001/4687
GNOME_KEYRING_CONTROL=
GTK_MODULES=gail:atk-bridge:unity-gtk-module
USER=venkatadeekshith
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
QT_ACCESSIBILITY=1
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
UNITY_HAS_3D_SUPPORT=true
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
SSH_AUTH_SOCK=/tmp/ssh-xIchkLm1A4H7/agent.6003
SESSION_MANAGER=local/ranjithapalvadi:@/tmp/.ICE-unix/6599,unix/ranjithapalvadi:/tmp/.ICE-unix/6599
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
UNITY_DEFAULT_PROFILE=unity
DESKTOP_SESSION=ubuntu
PATH=/home/venkatadeekshith/opt/gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabihf/bin:/home/venkatadeekshith/bin:/home/venkatadeekshith/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/venkatadeekshith/rpi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:/snap/bin:/var/lib/snapd/snap/bin
QT_IM_MODULE=ibus
QT_QPA_PLATFORMTHEME=appmenu-qt5
XDG_SESSION_TYPE=x11
PWD=/home/venkatadeekshith/conan_practice/mytestpkg/temp/source/hello
JOB=unity-settings-daemon
XMODIFIERS=@im=ibus
JAVA_HOME=/usr/lib/jvm/java-8-oracle
GNOME_KEYRING_PID=
LANG=en_IN
GDM_LANG=en_US
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
COMPIZ_CONFIG_PROFILE=ubuntu
IM_CONFIG_PHASE=1
GDMSESSION=ubuntu
SESSIONTYPE=gnome-session
GTK2_MODULES=overlay-scrollbar
SHLVL=1
HOME=/home/venkatadeekshith
XDG_SEAT=seat0
LANGUAGE=en_IN:en
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
UPSTART_INSTANCE=
UPSTART_EVENTS=xsession started
XDG_SESSION_DESKTOP=ubuntu
LOGNAME=venkatadeekshith
COMPIZ_BIN_PATH=/usr/bin/
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-Xta5uwWJs9
J2SDKDIR=/usr/lib/jvm/java-8-oracle
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop
QT4_IM_MODULE=xim
LESSOPEN=| /usr/bin/lesspipe %s
INSTANCE=
UPSTART_JOB=unity7
XDG_RUNTIME_DIR=/run/user/1001
DISPLAY=:0
XDG_CURRENT_DESKTOP=Unity
GTK_IM_MODULE=ibus
J2REDIR=/usr/lib/jvm/java-8-oracle/jre
LESSCLOSE=/usr/bin/lesspipe %s %s
XAUTHORITY=/home/venkatadeekshith/.Xauthority
_=/usr/bin/env
LIBS=
LDFLAGS= -m64   
CFLAGS=-mstackrealign -fPIC  -m64  -s -DNDEBUG  
CPPFLAGS= -m64  -s -DNDEBUG  
C_INCLUDE_PATH=:
CPLUS_INCLUDE_PATH=:/usr/arm-linux-gnueabihf/

**Comment by deekshith-elear** [comment]
Hi @danimtb 
Did you find any error in my configuration for cross building. the output for command you suggested was pasted in above comment
