### ISSUE TITLE
full_options is not documented

### ISSUE THREAD

**Issue by uilianries** [conan-io/docs#1074]
Hi!

From the issue https://github.com/conan-io/conan/issues/4515 someone asked

> What is `options` vs. `full_options`?

In fact, `full_options` is not documented, but it can be clearly found by searching the [Conan code](https://github.com/conan-io/conan/search?q=full_options&unscoped_q=full_options).

Actually, neither `full_options`, `full_settings` or `full_requires` are documented.

**Comment by danimtb** [comment]
I think those parameters are not for the users but implementation details of the Conan codebase and shouldn't be documented.

 If those attributes are "publicly" exposed in the *conanfile.py* please open an issue so we can make them protected.

Thanks!
