### ISSUE TITLE
There is no package for boost header only

### ISSUE THREAD

**Issue by mmatrosov** [conan-io/docs#1083]
There is a promising option `header_only` in `boost` recipe on conan-center, but there is no package built for it:

```
>conan search -r conan-center boost/1.69.0@conan/stable -q "header_only=True"
Existing packages for recipe boost/1.69.0@conan/stable:

Existing recipe in remote 'conan-center':

There are no packages for reference 'boost/1.69.0@conan/stable' matching the query 'header_only=True'
```
It is often very convenient to get only boost headers, without any binaries, since many boost libraries are header-only. Please build and upload this package.

PS I personally think it makes more sense to create a separate header-only recipe `boost-headers`, and make `boost` recipe depend on it. That's how we did in our company, where we have all recipes hand-written. Works as a charm.

**Comment by danimtb** [comment]
Please, report this issue in https://github.com/conan-community/community/issues and we will try to add that option to the CI

**Comment by mmatrosov** [comment]
Sure: https://github.com/conan-community/community/issues/152
