### ISSUE TITLE
In HowTos add a "How to make a conanfile template and use it."

### ISSUE THREAD

**Issue by dkgs** [conan-io/docs#111]
When reading the blog post http://blog.conan.io/2016/10/24/conan-at-work.html the section about the conanfile template used by several other component is really interesting and could be really useful when managing a lot of components having the same structure.

_If someone could quickly show me how to do it, I would gladly write this documentation section._

**Comment by lasote** [comment]
Hi @dkgs You can fork this repo and make a PR. 
You can build locally installing sphinx (pip install sphinx) and other require I can't remember sphinx-??? 
Then you can run **make html** and browse the _build folder.

But don't care if you cannot run the build, just make a PR to develop branch and we will fix any "style" thing we see.

Thanks!

**Comment by dkgs** [comment]
@lasote I think there is a misunderstanding and I apologize for it. When I said 
> If someone could quickly show me how to do it
I was talking on how to do the conan file template to inherit, not the documentation itself.

There will be no problem in writing the doc (as I already forked this repo :))

**Comment by memsharded** [comment]
A few tips:

- There are two common approaches to create base or common recipes for many packages. One would be to generate the conanfile.py recipes from templates, with any string templating mechanism (the simplest would be a string search & replace for strings like %NAME% or %VERSION%, but other better alternatives as jinja can be used). The other one would be extending (inheriting) the python ConanFile recipe class.

- The string template is very simple, just save in a ```conanfile.py.in`` the contents of the recipe, then have a master script that orchestrates the package creation just use it and replace the desired fields for each recipe

- The extending one: Just put common code in an "abstract" base class:

```python
from conans import ConanFile

class ConanBase(ConanFile):
    # common code here
```

Then have other classes (the actual recipes):

```python
from . import ConanBase # Use real import here

class ConanPkgLib(ConanBase):
    name = "Pkg"
    version = "0.2"
```

The only trick is that the base class should be also added to the recipe, so the ``exports="*.py"`` field might be necessary.

**Comment by dkgs** [comment]
I like the idea of extending the base class, because even if common functionalities, the packages can differs in some specific points.
But what bothers me is that the base class should be added to the recipe. Does it means that if I have N package sharing common functionalities, I have to copy the base class in each of them ? If so, isn't it possible to separate this base class and put it in another recipe and then the N-packages can add it to their requirements ?
This would be ideal, because the base class would be treated as a dependency, have a version and so on... but I can already see the problem : how to import this base class that is defined in the requirements and therefore should have already be imported...
So now we are stuck and should copy the base class in each package where we need it ? Otherwise, I didn't understood something.

**Comment by danimtb** [comment]
I think is issue was solved with teh python_requires feature, which is a dedicated feature for this purpose. 
https://docs.conan.io/en/latest/extending/python_requires.html

Feel free to comment or reopen in case you disagree. Thanks!
