### ISSUE TITLE
[docs] simplify explanation of owner

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/docs#1132]
The documentation explaining the `owner` part of package references was a source of confusion for me learning Conan.

> `pocoproject` is the owner of this package version. It is basically a namespace that allows different users to have their own packages for the same library with the same name, and interchange them. So, for example, you can upload a certain library under your own user name, and later the same packages can be uploaded, without modifications, to another official group or company username.

IMO place a full stop after "allows different users to have their own packages for the same library with the same name" and delete everything after. Especially words like "interchange" and "upload" being used, doesn't really add the the explanation and serves mostly to potentially confuse.

In fact, I opened an ill-fated issue (though I admit this may be a tendency of mine) about it: #4192.

**Comment by Lawrencemm** [comment]
Thanks. Had no idea there was a docs repo.

**Comment by danimtb** [comment]
Moving this out of the milestone as it is not related to the next release

**Comment by jgsogo** [comment]
Closed via https://github.com/conan-io/docs/pull/1134
