### ISSUE TITLE
Create a "glossary" section defining fundamental concepts of the Conan model

### ISSUE THREAD

**Issue by danimtb** [conan-io/docs#1138]
Reading some documents describing how Conan and its model works, it is very common to have a first section describing what is a reference, a binary package, a revision...

There are some intrinsic problems in the naming and sometimes it is not clear when we use these concepts. For example, the "package" word means the binary package or the recipe and the packages generated? Or is a package a binary package + the recipe?

I think having this kind of concepts in a common section like a glossary might be handy.

WDYT? @conan-io/barbarians @conan-io/community-leaders

**Comment by lasote** [comment]
Approved

**Comment by lasote** [comment]
In case this is useful: https://docs.docker.com/ (how they implement the glossary)

**Comment by uilianries** [comment]
> In case this is useful: [docs.docker.com](https://docs.docker.com/) (how they implement the glossary)

https://docs.docker.com/glossary/
