### ISSUE TITLE
Document "public parameters"

### ISSUE THREAD

**Issue by lasote** [conan-io/docs#1156]
In the section that receives it, in a very general way. E.g: In the hooks section, document that the object received as the `remote` contains a `.url` and a `.name`. The same idea for the rest.

**Comment by jgsogo** [comment]
This information is already in the docs: https://docs.conan.io/en/latest/reference/hooks.html#function-parameters

> remote: Named tuple with attributes name, url and verify_ssl.

We may add the `enable/disable` (https://github.com/conan-io/docs/pull/1392), but I'm not sure if all we would ever get a disabled remote into these functions (ping @czoido).
