### ISSUE TITLE
Document better include_prerelease

### ISSUE THREAD

**Issue by lasote** [conan-io/docs#1177]
https://github.com/conan-io/conan/issues/4882

Put an explicit example and clarify that, first the condition (>=1.0) has to be satisfied, then, that using include_prerelease it will also take into account the prereleases.

**Comment by danimtb** [comment]
Info should be here: https://docs.conan.io/en/latest/mastering/version_ranges.html

**Comment by jgsogo** [comment]
Closed via https://github.com/conan-io/docs/pull/1411
