### ISSUE TITLE
Upgrading Conan Version via CLI - HowTo?

### ISSUE THREAD

**Issue by solvingj** [conan-io/docs#118]
I got this message today when using conan:

WARN: A new conan version (v0.17.0) is available in current remote. Please, upgrade conan client to avoid deprecation.

However, I could not find any instructions on how to do this, other than downloading the new version and running the installer.  Is there a way to do this via CLI?   If so, I don't think it's documented.

**Comment by memsharded** [comment]
Actually, the preferred way is using the python/pip packages (as commented in the wishlist thread), so:

```bash
$ pip install conan --upgrade
```

I agree that clarifying this in the docs would be good, thanks for noticing.

**Comment by mloskot** [comment]
Could this be also clarified that Python-less binary installers like the one for Windows are not, let's call it, self-upgradeable? So users need to download newer installer and re-install conan.

**Comment by memsharded** [comment]
Yes @mloskot, it makes sense, submitted PR: https://github.com/conan-io/docs/pull/917

**Comment by mloskot** [comment]
@memsharded Thank you!
