### ISSUE TITLE
Add snapcraft documentation

### ISSUE THREAD

**Issue by Fohlen** [conan-io/docs#119]
Add a snapcraft example on https://github.com/conan-io/conan/issues/789#issuecomment-268115019
I'll will dig into the `readthedocs` guide and add appropriate documentation and maybe a blog post, as mentioned by @lasote

**Comment by memsharded** [comment]
This seems open for a long time ago. Closing now, but please re-open if this becomes active again, will love to add documentation for integration with snapcraft if this becomes a feature.
