### ISSUE TITLE
Document 'tools.check_output'

### ISSUE THREAD

**Issue by jgsogo** [conan-io/docs#1233]
Document tool introduced in https://github.com/conan-io/conan/pull/4854, it is piping the output to a file to avoid mixing with unexpected output.

**Comment by lasote** [comment]
I prefer to keep it internal. We have the `self.run` mechanism and it is not fully clear that it shouldn't be always like that. Until then better to keep it as internal usage.

**Comment by jgsogo** [comment]
Agree, I think it is too early to release it as stable 👍
