### ISSUE TITLE
conan getting started fails on os x

### ISSUE THREAD

**Issue by jlgerber** [conan-io/docs#1234]
# repro 
- clone git repo per docs
- mkdir build && cd build
- conan install ..

# faiure
```
ERROR: Missing prebuilt package for 'zlib/1.2.11@conan/stable'
Try to build it from sources with "--build zlib"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```
Pretty big turn off when your official walkthrough fails

**Comment by danimtb** [comment]
Hi @jlgerber and thanks for posting.

In fact, this is pretty common in apple as the compiler version is constantly changing. Could you indicate the compiler version you used? (output of `conan profile show default` command).

Also, you can continue with the getting started if you just build the missing package for your configuration:

```
conan install .. --build zlib
```

Please give it a go and tell us how it goes. Thanks! 😄

**Comment by jlgerber** [comment]
@danimtb, 
   of course, I attempted to build from source using --build... that led to another missing dependency which i had to --build. Eventually, I decided to build something simpler, so i tried yaml-cpp, which failed as well. I noticed that there was a descrepancy between the version of clang that i have (10) and the version that it was expecting. Ultimately, the only way that i got this to work was uninstalling conan, blowing away my .conan directory, and reinstalling. then it all worked. I had been playing around with conan a couple of years ago...

**Comment by danimtb** [comment]
Sorry to hear that.

Probably there was an error in the migration process of the cache or the settings.yml was not updated with the latest settings.

Did the getting started worked after the reinstall of Conan?

P.S. I have checked and all binaries for Macos, including apple-clang 10 are available for zlib

**Comment by jlgerber** [comment]
Turns out when I nuked Conan and reinstalled, it worked.

**Comment by danimtb** [comment]
Thanks for checking and trying again 😄
