### ISSUE TITLE
Document return code when ConanInvalidConfiguration

### ISSUE THREAD

**Issue by lasote** [conan-io/docs#1237]
https://docs.conan.io/en/latest/mastering/conditional.html?highlight=conaninvalidconfiguration

Explain that the process will return `6` and it can be used in CI to discard configurations

https://github.com/conan-io/conan/issues/4924

**Comment by danimtb** [comment]
We have that documented here: https://docs.conan.io/en/latest/reference/commands/return_codes.html
Is it enough?

**Comment by lasote** [comment]
oh! I couldn't find it. Maybe is a good idea to link that from https://docs.conan.io/en/latest/mastering/conditional.html?highlight=conaninvalidconfiguration and probably the other way around.

**Comment by danimtb** [comment]
This issue was closed by #1263
