### ISSUE TITLE
Document how to deploy bundled artifacts onto Artifactory when migrating

### ISSUE THREAD

**Issue by monsdar** [conan-io/docs#1239]
As described here:
https://www.jfrog.com/confluence/display/RTF/Deploying+Artifacts#DeployingArtifacts-DeployinganArtifactBundle

It's necessary to zip the package directly from the data directory and then upload those onto Artifactory. Works well for me, but wasn't documented anywhere.

**Comment by monsdar** [comment]
Linked issue: https://github.com/conan-io/conan/issues/4929

**Comment by danimtb** [comment]
Is this really working well?

The Conan server has a layout different from Artifactory.
There should be other missing metadata files that are created dynamically.

Moreover, the revisions might be ill-formed for the reasons above.

Have you tested it installing those "bundled" packages again? Is there any other action needed?

**Comment by monsdar** [comment]
That's a good point actually. After uploading the package looked right, but I haven't tested whether everything is usable. I'll check that out tomorrow and report back.

**Comment by danimtb** [comment]
Great, thanks a lot! I haven't tried that process before although it seems quite interesting for migrations to Artifactory. Please let us know when you try it 😄

**Comment by monsdar** [comment]
Seems not to work... After uploading the package it looks good within the Artifactory UI, but I can't find it with `conan search * -r artifactory`. I'll create a feature request in the conan issue-tracker. Closing here.
