### ISSUE TITLE
Update Installation Documentation due to PyYAML problems

### ISSUE THREAD

**Issue by ketzu** [conan-io/docs#1244]
Current version of conan depends on PyYAML <3.14 >= 3.11 (see https://github.com/conan-io/conan/blob/develop/conans/requirements.txt) but PyYAML is part of the distutils and therefore not easily removed or downgraded and by now in version 5.1.

Suggested solutions:

Actually follow up on this:

> We strongly recommend using virtualenvs (virtualenvwrapper works great) for everything related to Python.

by providing an explanation of how to do it.

Add PyYAML collisions to known installation inssues.

Unfortunately I can not provide a solution to the actual problem, as I frustratingly tried to get things to work for awhile now. Relevant issue of updating to newer versions of pyyaml seem to be abandoned for now: https://github.com/conan-io/conan/pull/4285

Sorry for the unhelpful issue.

**Comment by memsharded** [comment]
> Sorry for the unhelpful issue.

Not unhelpful at all :)

We have added a couple of links in the docs, pointing to the docs of virtualenvwrapper, there are good introductions there to learn how to use them: https://docs.conan.io/en/latest/installation.html

Actually, we didn't know that pyyaml 5.1 was out, we might be able to try to bump it, see if it passes CI, and it might be included in the requirements range. Done in: https://github.com/conan-io/conan/pull/4945

**Comment by memsharded** [comment]
Next conan version will allow pyyaml 5.1, so this can be closed.
Please check when conan 1.15 is out, and comment or re-open if necessary. Thanks again!
