### ISSUE TITLE
All images should have filename "conan-xxxx"

### ISSUE THREAD

**Issue by memsharded** [conan-io/docs#1246]
Necessary for SEO

**Comment by jgsogo** [comment]
`xxxx` stands for something? 
Exactly that caption or can they have any caption and then that _special string_?

**Comment by danimtb** [comment]
We would need some clarification about what it is needed to be done

**Comment by danimtb** [comment]
I think it is not the caption of the images but the actual name of the files

**Comment by jgsogo** [comment]
Yes, it is the same as this one: https://github.com/conan-io/website/issues/47

**Comment by danimtb** [comment]
Yes, I think so

**Comment by danimtb** [comment]
closed by #1389
