### ISSUE TITLE
Whats the best way to find conan python function reference?

### ISSUE THREAD

**Issue by rconde01** [conan-io/docs#126]
moved from https://github.com/conan-io/conan/issues/807#issuecomment-269448293

Maybe it's just because I'm a python n00b, but I've found it frustrating to find reference for self.copy for example where in one case I was interested in preserving symlinks and another I was interested in throwing away the path information. I finally found them by searching the repo...but it wasn't very efficient. It would be nice to have a searchable class reference...or maybe I'm "doing it wrong".

**Comment by lasote** [comment]
Added new reference section with improved contents, tools, etc
