### ISSUE TITLE
[bug] unknown VS version in documentation

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/docs#1319]
Hi there,
in the documentation there is written a Visual Studio version number which does not exist:
https://docs.conan.io/en/latest/reference/conanfile/methods.html#self-info-vs-toolset-compatible-self-info-vs-toolset-incompatible

The table specifies a **Visual Studio Version** ```13``` for **Compatible toolset** ```v120```.
While the toolset exists the Visual Studio version does not.

**Comment by danimtb** [comment]
removing this from milestone as it can go directly to master's "live" version

**Comment by danimtb** [comment]
fixed via #1320
