### ISSUE TITLE
mark CONAN_USERNAME and CONAN_CHANNEL as deprecated

### ISSUE THREAD

**Issue by lasote** [conan-io/docs#1368]
They will disappear at Conan 2.0, the reason we introduce them was for the `conan install <path>` command that didn't allow a reference. But since the reference is a possibility they should be avoided.

Edit here: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#user-channel
Edit also here: https://docs.conan.io/en/latest/reference/env_vars.html#conan-username-conan-channel

**Comment by danimtb** [comment]
Should we show a deprecation warning in the client too?

**Comment by memsharded** [comment]
Not if it will clutter the codebase and the tests with ``catchWarnings`` things.

**Comment by Johnnyxy** [comment]
Hi there,
if ```CONAN_USERNAME``` and ```CONAN_CHANNEL``` are removed from Conan 2.0 is it possible to retrieve the username and channel outside of the class that inherits the ConanFile-class?

This would be important for ```python_requires```:
```python
_t_name = 'tlib'
_t_version = os.getenv('TLIB_VERSION', '0.0.0')
_t_user = os.getenv('TLIB_USERNAME', os.getenv('CONAN_USERNAME', 'user'))
_t_channel = os.getenv('TLIB_CHANNEL', os.getenv('CONAN_CHANNEL', 'testing'))
_t_reference = '{name}/{version}@{user}/{channel}'.format(name=_t_name, version=_t_version, user=_t_user, channel=_t_channel)
_tlib = python_requires(_t_reference)
```

**Comment by jgsogo** [comment]
Closed by https://github.com/conan-io/docs/pull/1413 (already in `master`)

@Johnnyxy  About your concern regarding the `python_requires` you should have a look to the new implementation we are preparing (https://github.com/conan-io/conan/pull/5804) and write your concerns about it there (or as a new issue if they are related to _old_ `python_requires`).  Here in the `docs` repo, the comment will get lost 😞

**Comment by memsharded** [comment]
Yes @Johnnyxy please do so, but most importantly, please note that the current trends and good practices that are being established seem to point that it is better not to use channels in that way, to define "stages" or "promotions" of packages, but rather keep them fixed and use different repositories in the servers and move packages between them. In that way packages are fully immutable, nothing changes, which is an important thing.

**Comment by Johnnyxy** [comment]
Yes. In the beginning I used ```CONAN_USERNAME``` and ```CONAN_CHANNEL``` when creating packages. Currently new buildchain-code will not use them anymore as it is more specific when setting this on commandline directly -> less error prone.

As for the redesign of the ```python_requires``` feature:
It seems to me that at the moment you are tending to bring the definition of ```python_requires``` into the recipe-ConanFile-class. This would mean that at Conan-time (configure, build, etc.) the recipe can define what it ```python_requires``` instead of relying on hardcoded inclusion by the interpreter. 

Like so:
```python
class Recipe(ConanFile):
     python_requires = ["tool/...", ...]
     python_requires_extend = "tool.SomeClass"
```

This would totally make the ```CONAN_USERNAME```, etc. obsolete for my use case. I am looking forward to it.
