### ISSUE TITLE
[bug] type-o in docs

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/docs#1379]
hi there,
just a minor mispelling:
https://docs.conan.io/en/latest/reference/generators/deploy.html#deploy

> Files form dependencies are deployed under a folder with the name of the dependency.

```Files >>form<< dependencies```

**Comment by memsharded** [comment]
No problem, I can transfer it directly in Github. 
The important thing is to report and contribute, thanks very much for all your contributions! :) :) :)
