### ISSUE TITLE
Document italics in the available generators list

### ISSUE THREAD

**Issue by Morwenn** [conan-io/docs#1428]
In the [available generators list][1], some generators use a normal font while other ones use italics, but the page doesn't explain what this difference mean. It would be nice to mention the meaning of italics somewhere in the page.

I am opening this issue specifically because I don't know myself what this means, but it feels obvious that it has to mean something.

  [1]: https://docs.conan.io/en/latest/reference/generators.html

**Comment by danimtb** [comment]
Hi @Morwenn and thanks for the suggestion.

Normally, italics are used to indicate a path or the name of a file. You can find the documentation style guidelines here: https://github.com/conan-io/docs#text-emphasishighlighting

Actually, generators should not be in italics and it doesn't reaññy mean anything different from other ones.

**Comment by danimtb** [comment]
Closed by #1433
