### ISSUE TITLE
How to: Extract output stream from self.run

### ISSUE THREAD

**Issue by uilianries** [conan-io/docs#1481]
This follow [comment](https://github.com/conan-io/conan/issues/5292#issuecomment-498781676) shows how to extract the output from self.run command. It can be added to How To page.

Why? Checking the output can be useful for test package, when installing tools and validating their result/output.

**Comment by danimtb** [comment]
All the information is here: https://docs.conan.io/en/latest/reference/conanfile/other.html#running-commands but maybe we have to update the title of the section with "Output and running commands"

I don't think an how-to is needed for such a basic thing but maybe it is needed.

**Comment by uilianries** [comment]
Yes, it's enough. I searched for `self.run`, that's why I didn't find your link. Thanks for pointing me.
