### ISSUE TITLE
Remove CompatiblePackage from docs

### ISSUE THREAD

**Issue by db4** [conan-io/docs#1499]
Examples in https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#compatible-packages contain
```python
from conans import ConanFile, CompatiblePackage
```
Since conan 1.21.0 `CompatiblePackage` no longer exists and should be removed.

**Comment by memsharded** [comment]
Thanks for noticing! Submitted https://github.com/conan-io/docs/pull/1500 to fix it asap.
