### ISSUE TITLE
1.21 conan lockfile is no longer compatible with 1.20 lockfile

### ISSUE THREAD

**Issue by EugenMayer** [conan-io/docs#1512]
Even though i cannot find anything in the Changelogs https://docs.conan.io/en/latest/changelog.html?highlight=conaninfo%20txt about this change - only the statement https://docs.conan.io/en/latest/introduction.html#stability that those changes are to desired ( that is why i opened this issue )

i get into trouble with conan 1.21.0 and lockfiles

```
conan --version
Conan version 1.21.0
```

When working on a codebase with a lockfile of `conan 1.20.5`

```
26 ERROR: Error parsing lockfile <redacted>/conan.lock': This lockfile was created with a previous incompatible version. Please regenerate the lockfile
```

Running `conan install .` fixes the issue ( by recreating the lockfile ) ... but according the the stability changes, this should have never happened - is this a bug?

What change is

```
  "3c727868-2258-11ea-8ca0-0242ac120002": {
    "pref": "pcre/8.41#0:dc4c96eeba70bcda3b8bb4a1f4297956095dc601#0",
    "options": "build_pcrecpp=False\nbuild_pcregrep=False\nfPIC=True\nshared=True\nwith_bzip2=True\nwith_jit=False\nwith_unicode_properties=False\nwith_utf=False\nwith_zlib=True\nbzip2:build_executable=True\nbzip2:fPIC=True\nbzip2:shared=True\nzlib:fPIC=True\nzlib:minizip=False\nzlib:shared=True",
    "requires": {
     "bzip2/1.0.8#0": "3c7235d8-2258-11ea-8ca0-0242ac120002",
     "zlib/1.2.11#0": "3c7234d4-2258-11ea-8ca0-0242ac120002"
    }
   },
```

became

```
  "8": {
    "pref": "pcre/8.41#0:dc4c96eeba70bcda3b8bb4a1f4297956095dc601#0",
    "options": "build_pcrecpp=False\nbuild_pcregrep=False\nfPIC=True\nshared=True\nwith_bzip2=True\nwith_jit=False\nwith_unicode_properties=False\nwith_utf=False\nwith_zlib=True\nbzip2:build_executable=True\nbzip2:fPIC=True\nbzip2:shared=True\nzlib:fPIC=True\nzlib:minizip=False\nzlib:shared=True",
    "requires": {
     "bzip2/1.0.8#0": "5",
     "zlib/1.2.11#0": "2"
    }
   },
```

**Comment by memsharded** [comment]
Hi @EugenMayer 

According to the docs: https://docs.conan.io/en/latest/versioning/lockfiles.html, it is still marked as experimental:

> This is an experimental feature subject to breaking changes in future releases.

The changelog is: 

> Fix: Make lockfiles invariant when the graph doesn’t change. Now 2 different lockfiles captured with the same resulting graph in 2 different instants will be identical. #6139

It was considered a fix, and worth the breaking changes, as not having repeatable lockfiles really seemed an important issue, the implementation in https://github.com/conan-io/conan/pull/6139/files didn't add docs, as the version control and error message seems to be enough to describe what is happening and the solution, better than say it in the docs, where users will probably not read it.

Sorry for breaking, we really think it was worth the trouble, thanks for reporting.

**Comment by EugenMayer** [comment]
@memsharded is see, sure i have seen that disclaimer - i all good with this, just though to report that and ensure it was planned ( and as you write it was ).

Considering the fix and the issues, this was more then worth the breaking change, all for it.

You can close the issue anytime, thank you for the hints

**Comment by memsharded** [comment]
Yes, totally planned. Maybe the changelog should have been more explicit about it, sorry about that, we will try better next time. Thanks for the feedback!
