### ISSUE TITLE
Mark an unspecialized `cpp_info.name` for deprecation

### ISSUE THREAD

**Issue by Minimonium** [conan-io/docs#1516]
Conan is removing an ability to use unspecialized `cpp_info.name` in 1.22.

**Comment by memsharded** [comment]
It is not exactly planned this way. What is planned is to not allow it in ConanCenter. If users in their private recipes want to use ``cpp_info.name`` to change all generators, it will be possible. It just doesn't make sense in ConanCenter, because it breaks users.

**Comment by Minimonium** [comment]
Thanks for clearing up! I'll close it then. :slightly_smiling_face:
