### ISSUE TITLE
Description of package_id() is unclear

### ISSUE THREAD

**Issue by tamboril** [conan-io/docs#152]
I've gone through the source and read this documentation, but it is still not clear
what `package_id()` does.  Will you review the documenation for that function?

**Comment by memsharded** [comment]
Do you mean this section http://docs.conan.io/en/latest/howtos/define_abi_compatibility.html?
We did a great effort to write it, not sure how we could improve it. We will review it, but any specific suggestion or question about it? Thanks!

**Comment by tamboril** [comment]
I meant [this section](http://docs.conan.io/en/latest/reference/conanfile.html#package-id) in the reference, but now I see that the section you mentioned is referenced there. Sorry about that.

**Comment by memsharded** [comment]
No problem :)

Just read the other section, and if something is not clear, please tell. Thanks for your feedback

**Comment by tamboril** [comment]
OK.  That section is very well written.  I think there is a typo in the `RequirementInfo` methods, though.  Where it says, `self.info.requires["MyOtherLib"].full_package()`, should that be `...full_package_mode()` ?

**Comment by memsharded** [comment]
I think you are right, just submitted a PR: https://github.com/conan-io/docs/pull/153, thanks!
