### ISSUE TITLE
New image for ConanDocs Introduction

### ISSUE THREAD

**Issue by Dattax** [conan-io/docs#1587]
Can someone help replace the current image on Conan Docs with this new one (this one includes ConanCenter). You'll want to first upload the images to the images folder in this repo - and then link it from there.

Old: image:: images/conan-systems.png

New: image:: images/image-new.png

**Comment by memsharded** [comment]
Hi @Dattax 

This image is wrong:

- The server side is ``conan_server`` (that is the name of the server app) not Conan client
- The arrow does not go to ConanCenter. Client cannot upload to ConanCenter, only download.

**Comment by Dattax** [comment]
Oops, for your first point - you're right, I just realized I attached the wrong image (an old iteration!). Let me go find and come back with the correct one. Your 2nd point - I'll fix that.

**Comment by Dattax** [comment]
![Conan-new](https://user-images.githubusercontent.com/1408846/76337758-0f172880-62b5-11ea-8961-02ced2f3c8a2.png)

This was the newest iteration sent over. Thoughts?

**Comment by memsharded** [comment]
That is better, but still the arrows are in opposite direction:

- The arrow between ConanCenter and Artifactory is in the opposite direction
- The arrow between ConanCenter and Client is in the opposite direction
- The arrow between Artifactory and Client should be in both directions.

**Comment by Dattax** [comment]
I need to think about this, but...the way it was designed, I think the arrows indicate which item is supporting the item moving at the end of the arrow. For example, the client supports ConanCenter and Artifactory support ConanCenter. I agree that the Artifactory  and Client arrow should go both ways.

**Comment by memsharded** [comment]
I see, but IMHO, it is very confusing. It is Artifactory the one implementing the Conan API, not the opposite. I think most readers wouldn't understand this direction, and the "package install" direction is the one that should be represented here.

**Comment by Dattax** [comment]
![image-new](https://user-images.githubusercontent.com/1408846/76769833-3315b680-675a-11ea-9d06-ed4d23595870.jpg)
Here is the original with the suggestions. This should work, yes?

**Comment by Dattax** [comment]
Ok, I will be sending over a new one with the arrows representing the data flow.

**Comment by Dattax** [comment]
![new-flow](https://user-images.githubusercontent.com/1408846/76774830-abcc4100-6761-11ea-9ce7-2de29266fc34.png)

Here is the image with the requested changes.

**Comment by memsharded** [comment]
Perfect, I'll change it in the docs

**Comment by Dattax** [comment]
Thanks!

**Comment by memsharded** [comment]
I have put that image in the docs. Even if increasing the size of the image, the text "Community Edition for C/C++" reads very blurry, difficult to read. Making the image even bigger probably will look weird. Can we please change the font or something for clarity?

![image](https://user-images.githubusercontent.com/15367152/76808035-b54bbc80-67e6-11ea-905f-53edfef982a8.png)

**Comment by Dattax** [comment]
![new-image-2](https://user-images.githubusercontent.com/1408846/76809467-2e77ef00-67a8-11ea-9bb2-508737cf97af.jpg)

That's good feedback. See if this works. If not, I'll have to go back and ask the designers to fix.

**Comment by memsharded** [comment]
It would have been nice to have better quality image, this one resolution is a bit poor.

But NP, I have done PR https://github.com/conan-io/docs/pull/1600.
