### ISSUE TITLE
[bug] v1.22.2/1.22.3 Changelog missing and duplicated

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/docs#1615]
Hi there, as I was stepping around the changelog on Conan's doc site I saw a "bug".
The changelog for version 1.22.2 is exactly the same as for version 1.22.3 except version and date ([see here](https://docs.conan.io/en/latest/changelog.html#id18)).

Best regards

**Comment by czoido** [comment]
Hi @Johnnyxy,
Thanks a lot for reporting :)

**Comment by danimtb** [comment]
closed by #1617
