### ISSUE TITLE
Stale docs at readthedocs

### ISSUE THREAD

**Issue by memsharded** [conan-io/docs#1667]
This is still out there, and very outdated: https://conan-docs.readthedocs.io/en/feature-cmake-toolchain-file/introduction.html

We don't own the project, so can't remove, maybe @anton-matosov ?

**Comment by anton-matosov** [comment]
Hi @memsharded, 
Deactivated it. 
Didn't know that branch deletion is not enough.
Until next time 🙇

**Comment by Croydon** [comment]
Solved, can be closed
