### ISSUE TITLE
When using a base Conanfile, settings and generators get duplicated

### ISSUE THREAD

**Issue by cguldner** [conan-io/docs#1680]
When using a base conanfile, settings and generators values are getting duplicated. I have this base conanfile:

```python
class BaseConan(ConanFile):
    license = "None"
    description = "A base conanfile for common program options"
    settings = "os", "build_type", "arch", "multiarch", "toolchain"
    generators = "cmake",
```

When I go to use it in another conanfile.py, upload it, and run `conan inspect` on it, I get the following partial output
```
generators: ('cmake', 'cmake')
exports: None
exports_sources: None
short_paths: False
apply_env: True
build_policy: None
revision_mode: scm
settings: ('os', 'build_type', 'arch', 'os', 'build_type', 'arch')
```

The conanfile.py that I'm using it in doesn't declare the `generators` or `settings` variables, it just has the following `init` method:
```python
class DerivedConan(ConanFile):
    python_requires = "base/1.0@user/channel"
    python_requires_extend = "base.BaseConan"

    def init(self):
        base = self.python_requires["base"].module.BaseConan
        self.settings = base.settings + self.settings
        self.generators = base.generators + self.generators
        self.options = dict(base.options, **self.options)
        self.license = base.license
```
Based on the [example](https://docs.conan.io/en/latest/reference/conanfile/methods.html#init), I wouldn't expect `self.settings` of `DerivedConan` to be the same as `base.settings`.

This also begs the question as to whether the underlying type of `settings` and `generators` should be a `set`. I got around the issue by just doing:

```python
    def init(self):
        base = self.python_requires["base"].module.BaseConan
        self.settings = set(base.settings + self.settings)
        self.generators = set(base.generators + self.generators)
        self.options = dict(base.options, **self.options)
        self.license = base.license
```

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 14.04
  * Conan version: 1.24.1
  * Python version: 3.5

**Comment by cguldner** [comment]
@memsharded I'm still thinking there ought to be something to remove duplicate settings and generators, even if it doesn't involve changing the underlying type.

**Comment by memsharded** [comment]
> @memsharded I'm still thinking there ought to be something to remove duplicate settings and generators, even if it doesn't involve changing the underlying type.

Conan internally removes them, when it can process those attributes. There will not be repeated settings in the package_id, or in ``self.settings`` object inside methods, or the generator will be called twice. This is only happening "visually" at the ``conan inspect`` level, because that command is also taking the python class, unprocessed, and displaying its attributes. It will display the class attributes as they are defined in the class. I am not sure we should be changing the ``conan inspect`` to use sets in the output, this would hide for example cases in which the user declared directly ``settings = "os", "arch", "os"``.

**Comment by cguldner** [comment]
@memsharded I see the generator called twice, so I think there is still a bug there

**Comment by memsharded** [comment]
> @memsharded I see the generator called twice, so I think there is still a bug there

Ok, we can fix that at the internal ``write_generators`` level, but the ``conan inspect`` output will still be the same, that cannot be changed.

**Comment by cguldner** [comment]
@memsharded I'm thinking there should still be an update to the docs to explain that Conan inheritance is the same as regular Python inheritance
