### ISSUE TITLE
404 response page

### ISSUE THREAD

**Issue by memsharded** [conan-io/docs#1690]
404 response page - when the server returns a 404 for a certain page we need to present a user friendly page at the requested URL without redirects. E.g. https://docs.conan.io/en/latest/missing

we can perhaps present it with the navigation bar of the docs so that people can continue browsing the docs despite reaching a 404 page.

**Comment by memsharded** [comment]
It seems the redirect is an issue, and it would be better to have this page without redirects. I am not sure if this is even possible, but I am re-opening for consideration.

**Comment by uilianries** [comment]
The default Github approach is using Jekyll, but we don't use it, so the documentation recommends a 404.html at root level: https://help.github.com/en/github/working-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site

We could copy en/latest/404.html to /404.html and adapt the file paths (image and theme)

**Comment by uilianries** [comment]
We have an answer from Github Staff:

https://github.community/t/adding-404-page-to-a-custom-path/11067/2

Basically, we need a HMTL file on root level. We could use a symbolic link for that file.

**Comment by memsharded** [comment]
Ok, please @uilianries try to do this:

- Have an html, simplified from the docs html, something with similar look and feel to the docs.
- All the menu, index, etc, can be removed.
- Mostly a link to the root docs.conan.io

I guess our CI can take that html and put it in the production branch, right?

**Comment by uilianries** [comment]
Yes, I think so. We can generate a symbolic link and create the html file in src/

**Comment by memsharded** [comment]
I have done a dummy check: https://docs.conan.io/asdasd

Just copying the 404.html inside en/latest to the root, overwriting the existing redirect. It seems to work. So we would need:

- Automate the copying in CI from en/latest to root
- Automate in CI fixing the root 404.html. All urls (href, src, etc, should prepend ``en/latest/``)

**Comment by uilianries** [comment]
Thanks for checking! I'll do it tomorrow!

**Comment by memsharded** [comment]
Closed by #1896
