### ISSUE TITLE
Can conan be used from different processes?

### ISSUE THREAD

**Issue by dmitry-zakablukov** [conan-io/docs#184]
Good day.

I have a question: can conan be used from different processes? The question was born from the following errors from the two different build processes running on the same machine:
```
Traceback (most recent call last):
  File "C:\tools\Python27\Scripts\conan-script.py", line 9, in <module>
    load_entry_point('conan==0.21.0', 'console_scripts', 'conan')()
  File "C:\tools\Python27\lib\site-packages\conans\conan.py", line 6, in run
    main(sys.argv[1:])
  File "C:\tools\Python27\lib\site-packages\conans\client\command.py", line 990, in main
    error = command.run(args)
  File "C:\tools\Python27\lib\site-packages\conans\client\command.py", line 805, in run
    raise exc
WindowsError: [Error 183] Cannot create a file when that file already exists: u'C:\\Users\\user\\.conan\\data\\AapGenerator\\1.1\\passware\\stable\\build\\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9'
```
and
```
Traceback (most recent call last):
  File "C:\tools\Python27\Scripts\conan-script.py", line 9, in <module>
    load_entry_point('conan==0.21.0', 'console_scripts', 'conan')()
  File "C:\tools\Python27\lib\site-packages\conans\conan.py", line 6, in run
    main(sys.argv[1:])
  File "C:\tools\Python27\lib\site-packages\conans\client\command.py", line 990, in main
    error = command.run(args)
  File "C:\tools\Python27\lib\site-packages\conans\client\command.py", line 805, in run
    raise exc
shutil.Error: [(u'C:\\Users\\user\\.conan\\data\\AapGenerator\\1.1\\passware\\stable\\source\\conanfile.py', u'C:\\Users\\user\\.conan\\data\\AapGenerator\\1.1\\passware\\stable\\build\\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\\conanfile.py', "[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\user\\\\.conan\\\\data\\\\AapGenerator\\\\1.1\\\\passware\\\\stable\\\\build\\\\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\\\\conanfile.py'")]
```

How should I synchronize different processes that use conan?

Best regards, Dmitry.

**Comment by memsharded** [comment]
Please check:
- https://github.com/conan-io/conan/issues/800
- https://github.com/conan-io/conan/issues/848

The short answer: conan access to a local cache is not concurrent. That would be quite challenging at the moment

Long answer: there are different things that you could do depending on what you are doing:

- If using conan in a CI server, with multiple concurrent build jobs, you probably want to set a different, temporary CONAN_USER_HOME for each job, so it runs in a clean environment
- If some CI job wants to build many different package binaries from the same recipe, it can be done concurrently with some cautions. Typically call first ``conan source`` command, so the source code (one shared copy for all packages) is downloaded. Then, N parallel tasks can be fired, one to build each different package configuration, as builds and package folders are isolated (for the same package)
- If you are running in a developer machine, you probably want to run conan sequentially. If installing different packages, there will be no problem, but if the same package has to be downloaded or built from sources at the same time, there will be collisions and behaviors like the one you reported.

I'd suggest following the conversation in https://github.com/conan-io/conan/issues/848

**Comment by dmitry-zakablukov** [comment]
Thank you, @memsharded , for the answer. Sorry that I didn't find similar questions myself...

**Comment by memsharded** [comment]
No problem, IMHO github search for issues is not very good, so it is not easy to find similar or related issues. Don't hesitate to ask as many questions as you want :)
