### ISSUE TITLE
[QUESTION] Artifactory support for revisions

### ISSUE THREAD

**Issue by chris-laplante** [conan-io/docs#1853]
The docs say that revisions are currently only supported by conan_server, with bintray and Artifactory support coming soon: https://docs.conan.io/en/1.13/mastering/revisions.html#server-support.  But [this blog post](https://blog.conan.io/2019/04/01/New-conan-release-1-14.html.) suggests that revision support has been available in Artifactory since version 6.9. Should the docs be updated?

**Comment by czoido** [comment]
Hi @chris-laplante,
You are checking the documentation for conan 1.13, please check the documentation for the latest version of conan: https://docs.conan.io/en/latest/versioning/revisions.html

**Comment by chris-laplante** [comment]
Ah sorry, I'm an idiot.
