### ISSUE TITLE
Incorrect statement in conanfile set_name/set_version method reference 

### ISSUE THREAD

**Issue by thvdburgt** [conan-io/docs#1911]
The line

>The ``self.recipe_folder`` attribute is only defined in these two methods.

in https://github.com/conan-io/docs/blob/develop/reference/conanfile/methods.rst#set_name-set_version .
Can be removed since conan-io/conan/pull/7314 has been merged.

**Comment by memsharded** [comment]
Closed in #1912, thanks!
