### ISSUE TITLE
Document recommendations for conan.io channels

### ISSUE THREAD

**Issue by memsharded** [conan-io/docs#195]
From https://github.com/conan-io/conan/issues/1213, by @nunojpg

>Conan packages become more usable if they become predictable and consistent.
>I have a hard time figuring out when is it supposed to use channels stable/testing/ci.
>For example, if I'm packaging bleeding edge for CI, which should be version next, would you recommend that it is packed as next@ci or master@ci?
>Essentially I think a style guide for deciding what to call Versions and Channels should be something quick to do (if you know what you are doing, so not me), and would be really of use before the number of packages start exploding.
>Thanks,
>Nuno

I agree, some guidelines for conan.io channels could be useful (just for conan.io, obviously each one can use any convention on their private packaegs).

**Comment by oDn** [comment]
This issue is closed but I can't seem to find where in the docs channel guidelines are addressed. Have I missed something ?

**Comment by danimtb** [comment]
Hi @oDn!

I guess no channel guidelines were done.

Basically we, as package creators, use _testing_ channel when we are developing a recipe and _stable_ one when the recipe is ready enough to be used.

From the perpective of a library developer, channels could be used to create different scopes of your library. For example, use _rc_ channel for release candidates of your library, maybe _experimental_ for those kind of features, or even _qa_ / _testing_ before the library is checked by testers.

I would say that the most used channels by us are nowadays _testing_ and _stable_.

**Comment by rmam-spinworks** [comment]
Currently, the main source of information on how to use channels with conan is the post from @danimtb.  

In fact, [danimtb's post](https://github.com/conan-io/docs/issues/195#issuecomment-371528075) is the very first result returned by Google when googling for "conan how are channels used".

It would be helpful if conan provided a small text somewhere in conan.io regarding the `user` and `channel` attributes just to provide some guidance on how to use them.  In fact, just cutting and pasting @danimtb's comment straight to conan's FAQ would be a major help.

**Comment by danimtb** [comment]
I have opened an issue #928 to track this and finally add it to the docs in the FAQ or in the conanfile attributes. Thanks @rmam-spinworks for reminder and glad you found my answer useful!

**Comment by rmam-spinworks** [comment]
@danimtb I should be the one thanking you for taking the time to write that post.  It says everything a newbie needs to know about channels.  Great stuff and kudos.
