### ISSUE TITLE
Android standlone toolchain deprecated

### ISSUE THREAD

**Issue by Talkless** [conan-io/docs#1973]
In page https://docs.conan.io/en/latest/systems_cross_building/cross_building.html , there'se sentence:
> Now you have to build a standalone toolchain. 

With a link to https://developer.android.com/ndk/guides/standalone_toolchain .
That links now shows that standalone toolchains are obsolete, with warning:
> Warning: If using r19 or newer, follow the Use the NDK with other build systems document for instructions on using the NDK toolchains with arbitrary build systems. As of r19, **the NDK's default toolchains are standalone toolchains, which renders this process unnecessary.**

So.. I'm a bit confused. All this cross-building makes my brain hurt :-/, and it seems docs are outdated a bit?

**Comment by SSE4** [comment]
that's correct, the official recommendations on how to build for Android changes from time to time, and our docs aren't updated automatically. e.g. they deprecated GCC and standalone toolchains at some points.
