### ISSUE TITLE
conan_set_find_library_paths mentions CMAKE_INCLUDE_PATH twice

### ISSUE THREAD

**Issue by gerben90** [conan-io/docs#1976]
The documentation under [conan_set_find_library_paths](https://docs.conan.io/en/1.32/reference/generators/cmake.html?highlight=conan_set_find_library_paths#conan-set-find-library-paths) mentions CMAKE_INCLUDE_PATH twice:
> Sets CMAKE_INCLUDE_PATH and CMAKE_INCLUDE_PATH.

One of them should be CMAKE_LIBRARY_PATH.

**Comment by gerben90** [comment]
Created a PR to fix this issue:
https://github.com/conan-io/docs/pull/1977

**Comment by memsharded** [comment]
Solved by https://github.com/conan-io/docs/pull/1977, thanks!
