### ISSUE TITLE
[bug]  Incomplete sentence in docs

### ISSUE THREAD

**Issue by colin-pm** [conan-io/docs#1989]
There seems to be an incomplete sentence in the Yocto documentation.

https://github.com/conan-io/docs/blame/master/integrations/cross_platform/yocto.rst#L39-40

**Comment by colin-pm** [comment]
Also, it seems like the meta-conan layer is not actively maintained.  No changes have been made in two years.  The main branch of the repo is compatible with Yocto 2.6.  Looks like there is also a warrior branch that was never merged into main with support for 2.7.  Yocto is currently on 3.1 with 3.2 in development.  If the meta-layer is no longer maintained, it may be good to indicate that in the documentation.

**Comment by colin-pm** [comment]
As an update I have created two PRs for the meta-conan layer that adds support for 3.1 and 3.2 :)

https://github.com/conan-io/meta-conan/pull/8
https://github.com/conan-io/meta-conan/pull/7

**Comment by memsharded** [comment]
Thanks very much @colin-pm for contributing this update.

We are aware of users using both Conan and Yocto, but many cannot contribute back and it is easy that things get a bit outdated if we cannot prioritize it enough. 

Quick question, aren't those 2 PR mutually incompatible? It seems they are both changing
```
LAYERSERIES_COMPAT_meta-conan = "gatesgarth"
# AND
LAYERSERIES_COMPAT_meta-conan = "dunfell"
```

Any suggestion how to handle this?

**Comment by colin-pm** [comment]
conan-io/meta-conan#7 is meant to be merged first.  Once it's merged, a branch should be made of master named "dunfell".  Then conan-io/meta-conan#8 can be merged and another branch can be created off master named "gatesgarth".  I would have created PRs to merge into those branches upstream, but I'm not sure if that's possible since the branches don't exist.

The second PR removes dunfell support because conan-io/meta-conan#8 removes python3-packaging from the Conan meta-layer because it became available upstream in meta-openembedded's meta-python layer for 3.2 (Gatesgarth).  Additionally, native support was added to python3-colorama's upstream recipe in 3.2 as well.

Creating branches for each release of Yocto seems to be the git flow I've seen most meta-layers follow.  The tip of master only needs to be compatible with the tip of master for poky and the master branches of any other meta-layers.  I'm not sure if this is the flow you want to follow.

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/docs/pull/2022
