### ISSUE TITLE
Specify accepted pattern format of `conan install --build` option in docs/reference/commands/install.rst

### ISSUE THREAD

**Issue by ovanes** [conan-io/docs#199]
Please explain in the docs which format is expected, e.g. `regex`, `globbing expression` etc. Currently unclear.

**Comment by memsharded** [comment]
Good point, could be better explained. Patterns in most conan commands are ``fnmatch`` patterns, not regex.

**Comment by ovanes** [comment]
thanks!

**Comment by lasote** [comment]
Fixed in docs, will be added to the help message in the conan client too.
