### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by mkacher** [conan-io/docs#2005]
https://docs.conan.io/en/latest/reference/conanfile/tools/gnu.html?highlight=maketoolchain#definitions

typo in Definitions code sample:

def generate(self):
    tc = MakeToolchain(self)
    tc.**preprocessor_definitions**["MYVAR"] = "MyValue"
    tc.generate()

**Comment by solvingj** [comment]
https://github.com/conan-io/docs/pull/2007

**Comment by danimtb** [comment]
fixed by #2007
