### ISSUE TITLE
Build documentation after each push

### ISSUE THREAD

**Issue by uilianries** [conan-io/docs#204]
Hi!

I didn't see some Travis or other build integration in this repository.  
Anyone could create a bad reference or a bad syntax in doc and push.  
A very simple approach, is run install_nginx and check it results.

**Comment by memsharded** [comment]
Hi @uilianries,

The build integration is directly run by the readthedocs service. I usually run "make html" locally to generate and proofread docs if there is something I think it could break them.

**Comment by uilianries** [comment]
Nice. Maybe a README file with [build status ](http://conanio.readthedocs.io/en/latest/?badge=latest) would be great.

**Comment by memsharded** [comment]
Done :)

**Comment by uilianries** [comment]
Great!  
 Thanks @memsharded
