### ISSUE TITLE
Is it possible to use conan export-pkg with a profile ?

### ISSUE THREAD

**Issue by Bawen34** [conan-io/docs#2116]
Hello,

Is it possible to use conan export-pkg with a profile as a parameter ?

Because when I do such a thing, I got packages overwritten. The only differences I have in my profiles is the setting compiler.version; and this difference seems to not be taken into account when using conan export-pkg...

Thanks in advance

**Comment by memsharded** [comment]
Hi @Bawen34 

Have you made sure that your package actually declares the settings ``settings = "os", "compiler", "arch", "build_type"``?
If you could share the recipe or part of it, and the output of the ``export-pkg`` command, that might help too.

**Comment by Bawen34** [comment]
Thanks for you reply..
I am using conan-1.37.0
My profile contains:
```
[settings]
    os=Linux
    os_build=Linux
    arch=armv7
    arch_build=x86_64
    compiler=gcc
    compiler.version=7.3
    compiler.libcxx=libstdc++11
[build_requires]
	libpcap/1.9.1@3rd-party/stable
```
I have two other profiles when only compiler.version differs

Once my package generated, I have in conaninfo.txt
```

[settings]
    arch=armv7
    os=Linux

[requires]

[options]

[full_settings]
    arch=armv7
    os=Linux

[full_requires]

[full_options]

[recipe_hash]
    51b439d703c69e4b922e47be6c1ad87f 
```

**Comment by Bawen34** [comment]
And this is my command line
conan export-pkg ./build/linux_armv7 user/channel -pr ./linux_armv7-profile -e platform=linux_armv7 -f

**Comment by Bawen34** [comment]
> Hi @Bawen34
> 
> Have you made sure that your package actually declares the settings `settings = "os", "compiler", "arch", "build_type"`?
> If you could share the recipe or part of it, and the output of the `export-pkg` command, that might help too.

I think I see what you mean, let me try
