### ISSUE TITLE
In sample `hello`, problem about creating package without test

### ISSUE THREAD

**Issue by playgithub** [conan-io/docs#2128]
https://github.com/conan-io/docs/blob/master/creating_packages/getting_started.rst#creating-and-testing-packages

In the doc above

```
$ conan create . demo/testing
...
Hello world Release!
```

I've tried to create package without test as below, but the test package is also built and run, as same as above

```
$ conan create .
...
Hello world Release!
```

**Comment by danimtb** [comment]
Hi @playgithub,

Sorry but I don't get what you mean. You said you removed the test_package folder?
The only difference I see in you command is that you did not use the `<user>/<channel>`  (`demo/testing` in your case). That does not affect the test package at all, it is only an argument for the reference you are creating.

**Comment by playgithub** [comment]
> Hi @playgithub,
> 
> Sorry but I don't get what you mean. You said you removed the test_package folder?
> The only difference I see in you command is that you did not use the `<user>/<channel>` (`demo/testing` in your case). That does not affect the test package at all, it is only an argument for the reference you are creating.

The only difference I made it to call `conan create .` instead of  `conan create . demo/testing`.

**Comment by danimtb** [comment]
Thanks for the clarification. That only affects the reference or the package that you are creating. If you have a `lib1` with version `2.0.0` you can create a package that can be referenced as `lib1/2.0.0@demo/testing` if you specify so in the command: `conan create . demo/testing` (the recipe *conanfile.py* already contains the name and the version). This is normally used to diffrenciate the references you create providing additional information like `testing`, `unstable`, `stable`, `production`...

However, you can also omit the `<user>/<channel>` part: `conan create .`. Packages provided in `conancenter` do not contain user and channel as they are considered "official" packages coming from the community. In the case of enterprise packages, we recommend adding a user/channel to distinguish one package from the other. For example, Conan Center provides `openssl/1.1.1k` and you could also create a different OpenSSL recipe in your company with reference `openssl/1.1.1k@mycompany/testing` so you are able to use one or the other.

**Comment by playgithub** [comment]
> Thanks for the clarification. That only affects the reference or the package that you are creating. If you have a `lib1` with version `2.0.0` you can create a package that can be referenced as `lib1/2.0.0@demo/testing` if you specify so in the command: `conan create . demo/testing` (the recipe _conanfile.py_ already contains the name and the version). This is normally used to diffrenciate the references you create providing additional information like `testing`, `unstable`, `stable`, `production`...
> 
> However, you can also omit the `<user>/<channel>` part: `conan create .`. Packages provided in `conancenter` do not contain user and channel as they are considered "official" packages coming from the community. In the case of enterprise packages, we recommend adding a user/channel to distinguish one package from the other. For example, Conan Center provides `openssl/1.1.1k` and you could also create a different OpenSSL recipe in your company with reference `openssl/1.1.1k@mycompany/testing` so you are able to use one or the other.

Thanks

so for a complete reference, i.e. `pkg/version@user/channel`, they maps to subdirectories in `.conan\data`, for example:
`hello/0.1@demo/test` maps to path `.conan\data\hello\0.1\demo\test`,
`hello/0.1` maps to path `.conan\data\hello\0.1\_\_`,
right?

**Comment by danimtb** [comment]
yes, that is the most noticeable difference in the cache
