### ISSUE TITLE
doc are not comprehensive enough for newbies

### ISSUE THREAD

**Issue by playgithub** [conan-io/docs#2129]
I'm learning conan by reading the official docs from the beginning.
But I feels hard, some concepts are vague to me, though I've reading the doc one section by one section.
Any suitable learning stuff for newbies?

**Comment by memsharded** [comment]
Have you tried the academy? https://academy.jfrog.com/path/conan It is free, online, hands-on training courses.

**Comment by playgithub** [comment]
Thanks
