### ISSUE TITLE
Anyway to generate the docs in a pdf file?

### ISSUE THREAD

**Issue by playgithub** [conan-io/docs#2150]
# Problems

## For html
There is always a pop:
```
By clicking “Accept All Cookies”, you agree to the storing of cookies on your device to enhance site navigation, analyze site usage, and assist in our marketing efforts.
```
If I don't change the cookies settings, I have to click `Accept All cookies` time by time to  close the pop.

Also page rendering is relatively slow.

## For epub
It has  a problem https://github.com/conan-io/docs/issues/2149
Also slow rendering

## For Html Help
Not formatted properly

## For others
Not suitable for Windows

**Comment by czoido** [comment]
Hi @playgithub,
We generate a pdf with the docs for each release, please check: https://docs.conan.io/en/1.38/conan.pdf
If you want to generate the docs yourself, you can do that running:

```
sphinx-build -W -b latex -d ./_build/.doctrees ./ ./_build/latex
make -C ./_build/latex all-pdf
```

in the root folder of the [documentation](https://github.com/conan-io/docs) (we use this docker image to generate the docs in the ci: https://github.com/conan-io/docs/blob/develop/.ci/Dockerfile)

Hope this helps!

**Comment by playgithub** [comment]
Thanks very much

**Comment by playgithub** [comment]
> ```
> sphinx-build -W -b latex -d ./_build/.doctrees ./ ./_build/latex
> make -C ./_build/latex all-pdf
> ```

The first command succeeds, the size of `_build/latex` is nearly 9.5MB.
The second command output nothing in terminal, and no corresponding pdf file can be found.

**Comment by czoido** [comment]
> 
> The first command succeeds, the size of `_build/latex` is nearly 9.5MB.
> The second command output nothing in terminal, and no corresponding pdf file can be found.

It should be generated in `_build/latex/conan.pdf`

**Comment by playgithub** [comment]
> It should be generated in `_build/latex/conan.pdf`

no one, is some dependencies missed?

**Comment by playgithub** [comment]
OK, needs something like `MiKTeX` or `TeX Live`.
Thanks

**Comment by playgithub** [comment]
As a note, after installing `MikTex` and `gnu make for Windows`, it succeeds.
