### ISSUE TITLE
Is this document correct? 

### ISSUE THREAD

**Issue by solvingJ** [conan-io/docs#216]
https://github.com/conan-io/docs/blob/master/integrations/cmake/cmake_generator.rst

It starts out: 
> For modern cmake (>=3.1.2), the macro conan_define_targets() defines ...

But then in the code below it has: 
> conan_basic_setup(TARGETS)

It seems like "conan_basic_setup(TARGETS)" should be "conan_define_targets(TARGETS)"

**Comment by memsharded** [comment]
The docs are fine, I think. There is a macro called ``conan_define_targets()`` that will do the targets related stuff. But the usual way to use it is calling ``conan_basic_setup(TARGETS)``, that will do also other things besides the targets definitions.

You can have a look to the generated code in ``conanbuildinfo.cmake`` file, you will understand it better.

**Comment by solvingJ** [comment]
Fair enough.  The most important thing is that it's correct.  Just be advised that its confusing to introduce a macro in a doc and then show the calling of the previously introduced macro without explanation that one calls the other in the background.  It looks like a very typical copy/paste error.  Anyway, FYI, I'm very excited to have conan.  Thanks for all your work.
