### ISSUE TITLE
`conan install` option `-pr`

### ISSUE THREAD

**Issue by playgithub** [conan-io/docs#2180]
```
$ conan install -h
...
 -pr PROFILE_HOST, --profile PROFILE_HOST
                        Apply the specified profile to the host machine
  -pr:b PROFILE_BUILD, --profile:build PROFILE_BUILD
                        Apply the specified profile to the build machine
  -pr:h PROFILE_HOST, --profile:host PROFILE_HOST
...
```

It looks like that `-pr` and `-pr:h` are the same.
I think `-pr` = `-pr:b` + `-pr:h`, is it true?
If true, the doc for `-pr` be better as
```
 -pr PROFILE_HOST, --profile PROFILE_HOST
                        Apply the specified profile to the host machine and the build machine
```

**Comment by uilianries** [comment]
> It looks like that -pr and -pr:h are the same.

Yes, correct. More information here: https://docs.conan.io/en/latest/reference/profiles.html#build-profiles-and-host-profiles

>  I think -pr = -pr:b + -pr:h, is it true?

No. They are different features. When you pass a single profile, Conan will consider os and os_build, but when using multi profile, they are separated profiles. This is very useful in cases where you need to cross-compiler and need an application as build requirement (e.g. protobuf). You can read more here: https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#using-build-requires

>  If true, the doc for -pr be better as

Thank you for your suggestion. Those lines are directly collected from `conan install --help` output, so first we would need to update that command help.

**Comment by playgithub** [comment]
Thanks, however I can't understand the doc, I'll learn it later.
