### ISSUE TITLE
Better documenting building systems other than CMake

### ISSUE THREAD

**Issue by useredsa** [conan-io/docs#2201]
I want to consider if it would be easy for people that use Makefiles to compile their project to use conan,
given that at the moment what they do is to copy the libraries into the project's folder.
Unfortunately, in the documentation, almost all examples use CMake.

There is a [page](https://docs.conan.io/en/latest/integrations/build_system/make.html) about the generator make,
but it seems it might be outdated, as it asks the user to write this line in their Makefile:
```
$(call CONAN_BASIC_SETUP)
```
but `CONAN_BASIC_SETUP` is not defined,
and thus the configuration does not work.
Is this a mistake in the docs or maybe I am doing something wrong?

If I finally find it worth it, would it be possible to contribute to the docs?
I also see that this generator is going to be removed in favor of the autotools integration.
When would that be happening?

Best regards,

**Comment by memsharded** [comment]
Hi @useredsa 

Yes, all the efforts should go to the new integrations in ``conan.tools`` in this case: https://docs.conan.io/en/latest/reference/conanfile/tools/gnu.html

We will start doing the switch in the documentation starting from next release, for all new integrations as they become ready. Additions and improvements to the documentation, including the examples repo will be welcome, of course. Lets do the switch first, then start adding from there. Thanks!

**Comment by useredsa** [comment]
Hi @memsharded.

I have thought a little bit more about it and I feel the current state of the documentation is a problem.
The Make integration is not yet deprecated.
It will, in version 2.0, but it is currently not.
Then, why is `CONAN_BASIC_SETUP` not generated inside `conanbuildinfo.mak` in the example?
It sounds like the integration is already broken.

**Comment by memsharded** [comment]
Hi @useredsa 

Yes, this seems to be a bug in the documentation itself. For some reason something was documented something that was not there, this should be fixed in the docs, you are right, lets fix it.

**Comment by memsharded** [comment]
https://github.com/conan-io/docs/pull/2215 should fix this, thanks for telling!

**Comment by useredsa** [comment]
Thank you very much @memsharded .
