### ISSUE TITLE
local html doc always popup cookie settings

### ISSUE THREAD

**Issue by playgithub** [conan-io/docs#2228]
## Reproduce Steps
1. build doc with `make html`
2. open `index.html`
3. chromium shows a popup at bottom for cookies settings
4. set as in the screenshot
  ![image](https://user-images.githubusercontent.com/3665590/133426470-24f76dcb-a3f9-4519-890c-2ce039b1d8fd.png)
5. refresh the page, the popup shows aggain

## Question
How not to show the popup after settings done?

**Comment by uilianries** [comment]
Hi! I believe your browser did not cache your choice.

Personally, I use https://www.i-dont-care-about-cookies.eu/ to avoid Cookies.

**Comment by playgithub** [comment]
Thanks, but I prefer a way without addons.

**Comment by czoido** [comment]
Hi, 
This looks more related to the browser, I have not been able to reproduce under the major browsers. Closing this issue as I don't think we can do anything more on our side.

**Comment by playgithub** [comment]
The online docs (https://docs.conan.io) have no problem, only the offline docs that built from source have such a problem.
