### ISSUE TITLE
Plans, methods, or examples for packaging c++ libraries built with gradle

### ISSUE THREAD

**Issue by WilliamBehrens** [conan-io/docs#2235]
I'm currently trying to package https://github.com/wpilibsuite/allwpilib into a conan package. While the CMake project embedded into it builds most of the components the biggest one I need, wpilibc, only builds via the main gradle project, `./gradlew :wpilibc:build`, but conan doesn't seem to have any offical support for packaging gradle projects yet so does someone have an example of doing this or any ideas as to how?

**Comment by memsharded** [comment]
Hi @WilliamBehrens 

The truth is that we don't have a gradle integration yet, I recall some users having some in private, but it was not contributed back.

Implementing an integration is relatively easy if you know the build system well enough. We had some documentation and blogs like https://blog.conan.io/2019/07/24/C++-build-systems-new-integrations-in-Conan-package-manager.html for describing how to develop a custom integration, but now it has become a bit outdated. The best approach (for anyone that would like to give this a try, at the moment it doesn't seem to have a big enough demand to invest time to implement it in the short term ourselves) would be:

- Mimic some of the integrations in the new ``conan.tools`` space, like ``conan.tools.microsoft`` or ``conan.tools.cmake``
- Use a ``GradleDeps`` component to model the dependencies information, writing a file that can be passed to gradle
- Use a ``GradleToolchain`` component to model the mapping from Conan settings to Gradle configuration
- Use a ``Gradle`` component to wrap the command line invocation
- First, just write those components in the same ``conanfile.py`` you use to build. When they work, you can put these components in a ``conanfile.py`` and pass it as ``python_requires`` so it can be reused.
