### ISSUE TITLE
Question about package hashing

### ISSUE THREAD

**Issue by tleachman1234** [conan-io/docs#225]
Is there a variable you can call to return the package hash that conan will use for the current build? It is mentioned in the docs: 

> Then, for each different configuration of settings and options, a package ID will be computed in the form of a SHA-1 hash of such configuration. Sources will be copied to the “build/hashXXX” folder, and the build() method will be triggered.

But I don't see anything in the docs as to either a variable that holds this hash value, or the way it is exactly computed so you can reproduce the same hash.

**Comment by memsharded** [comment]
Hi!

Yes, you call ``self.info.package_id()`` to get it. Just be aware that it might not be available all of the time, until the full graph hasn't been built, the package ID is still not computed. Why would you want to get the package ID from your recipes? In theory it is something that is abstracted away, it would be interesting to learn about your use case. Thanks!

**Comment by tleachman1234** [comment]
Basically, the way we are wanting to use conan is so that all our package dependencies can be hosted on JFrog Artifactory, but we already have an extensive build system in place using makefiles, and redesigning this to fully use cmake and conan is out of the scope of the project I'm working on. In the makefile there is a variable that defines where to look for our packages, and since the hash may change I need a way of retrieving it to insert into the makefile. So we are only partially using conan, for compiling packages and fetching them from the repository, but not to build our final applications.

**Comment by memsharded** [comment]
Uhm... I still don't get why you need the exact ID, as that will be generated from the settings. Maybe there might be a better way, if you want to discuss it further, we might able to jump to chat, please write to info@conan.io if you want to.

**Comment by tleachman1234** [comment]
Actually, the way I was looking at it previously was that I wasn't generating the paths with `conan install`. So I could run this instead, however it generates files that I will probably just want trashed. Although `conan install` supports pointing the command at a `conanfile.txt` to use, I don't see a way to tell conan where to put the generated files (`conanbuildinfo.cmake` for example). Unless I'm missing something, this might be good functionality to add. I could see several reason to specify a specific install folder instead of just writing the files to the current directory

**Comment by memsharded** [comment]
Right now conan install works in the current directory. Files will be generated there. Generally it is not a big issue, the ``conanbuildinfo.cmake`` is generated in the build folder which is plenty of other temporary cmake files, so you typically trash the whole folder, there is no reason to just trash the ``conanbuildinfo.cmake``, as long as the build needs it.

There is ongoing work improving the internals of the conan api, and it includes a ``cwd`` argument to be able to set the output directory. Then, as long as the build system is able to find the generated files in the different location, it will be fine.  In the meantime, you will have to run ``cd path/to/yourdir`` and ``conan install`` from there.
