### ISSUE TITLE
New 'Conan migration guide to 2.0' has outdated properties info

### ISSUE THREAD

**Issue by eigenwhat** [conan-io/docs#2321]
https://docs.conan.io/en/1.43/conan_v2.html#new-properties-model-for-the-cpp-info-in-conan-2-0-generators

Part of the documentation still refers to the new properties affecting legacy generators.

> New properties defined for CMake generators family, used by CMakeDeps generator:
>
> * `cmake_file_name` property will affect all cmake generators that accept the `filenames` property _(cmake_find_package and cmake_find_package_multi)._
> * `cmake_target_name` property will affect all cmake generators that accept the `names` property _(cmake, cmake_multi, cmake_find_package, cmake_find_package_multi and cmake_paths)._

**Comment by memsharded** [comment]
You are right, lets fix this asap, thanks very much for reporting.

**Comment by franramirez688** [comment]
Thanks for reporting it @eigenwhat 
The fix https://github.com/conan-io/docs/pull/2322 is already merged.
