### ISSUE TITLE
Document Gitlab CI integration

### ISSUE THREAD

**Issue by memsharded** [conan-io/docs#233]
Developed by @uilianries in https://github.com/conan-io/conan/pull/1401

**Comment by uilianries** [comment]
Okay, I can update docs tonight :smile:

**Comment by memsharded** [comment]
Good, you are an awesome contributor to the project! 
Please if so, do it to the "develop" branch, that we merge to master and release when 0.25 is out.

Thanks again once more for your incredible job.
