### ISSUE TITLE
Is = necessary in version range examples?

### ISSUE THREAD

**Issue by johnmcfarlane** [conan-io/docs#2335]
@lasote are you sure the `=` first introduced [here](https://github.com/conan-io/docs/pull/176/files#diff-422fbfa49c09f6c17e165fa9a06b427c8ae0b9cfd79f6f708b079b4abbe486cdR23) is necessary? [node-semver 0.8.1](https://pypi.org/project/node-semver/0.8.1/) (and its [JS originator](https://github.com/npm/node-semver)) don't seem to mention `~=` in their examples.

**Comment by lasote** [comment]
Hi @johnmcfarlane, you are right. I don't recall why it was allowed but I can see that we dropped that in Conan 2.0 (develop2) branch. So probably we should remove it from the docs. I will ask the team in case I'm missing something.
