### ISSUE TITLE
Improve conan Docs README

### ISSUE THREAD

**Issue by uilianries** [conan-io/docs#236]
Hi!

Should be better if Conan docs provides some more information in README, such as:
* How to build docs in local host (e.g. build.bat)
* How to Read built docs in local host (e.g firefox _build/html/index.html)
* How to contribute. Create a new branch from develop and create a PR to develop
* Build dependencies (e.g. Sphinx)

I already know Sphinx and wasn't complicated to me, but newbie guys might be lost. And Conan docs uses master/develop branches, but the flow is not documented, anyone could create a PR directly to master.

Regards.

**Comment by lasote** [comment]
Done!

**Comment by uilianries** [comment]
Thanks @lasote!
