### ISSUE TITLE
Improve "conan test_package" explanation with real commands

### ISSUE THREAD

**Issue by memsharded** [conan-io/docs#238]
As detailed here: https://github.com/conan-io/conan/issues/1450

**Comment by lasote** [comment]
Now with export-pkg

**Comment by danimtb** [comment]
`conan test_package` does no longer exists. Similar command is conan create and it it is well explained  here: http://docs.conan.io/en/latest/packaging/getting_started.html#creating-and-testing-packages and here: http://docs.conan.io/en/latest/reference/commands/creator/create.html

Regarding `conan export-pkg` maybe this should be explained in a how-to with an specific example of the its details as it is a very particular command and not the normal or recommended flow for creating conan packages.
