### ISSUE TITLE
dependencies - are these bugs already addressed?

### ISSUE THREAD

**Issue by SSE4** [conan-io/docs#2384]
the following [page](https://docs.conan.io/en/latest/reference/conanfile/dependencies.html) about dependencies says:
```
These tools are very experimental and subject to breaking changes.
It also contains some known bugs regarding tool_requires, to be addressed in next Conan 1.39
```

it's already conan 1.44, are these bugs already addressed or still there?
maybe it's time to update the notice?

**Comment by uilianries** [comment]
I believe it was fixed on Conan 1.44: https://github.com/conan-io/conan/pull/10168. @lasote  can you confirm it?

**Comment by lasote** [comment]
I don't really know which bugs are these

**Comment by memsharded** [comment]
I think those were the bugs of the filtering of dependencies, but that was solved. It can be removed.

**Comment by uilianries** [comment]
Thank you!
