### ISSUE TITLE
Unclear instructions for Running Artifactory CE 

### ISSUE THREAD

**Issue by knatten** [conan-io/docs#2609]
In https://docs.conan.io/en/latest/uploading_packages/artifactory/artifactory_ce.html, there's a section about running Artifactory CE. It says:

> There are several ways to download and run Artifactory CE. The simplest one might be to download and unzip the designated zip file, though other installers, including also installing from a Docker image.

I don't really understand the second sentence here, might there be some words missing?

> When the file is unzipped, launch Artifactory by double clicking the .bat or .sh script in the bin subfolder, depending on the OS.

There is no `bin` subfolder, I assume you mean the `app/bin` subfolder? There are several `.sh` files in that directory, which one are you referring to?

**Comment by memsharded** [comment]
Yes, that is true, those instructions belong to older versions of Artifactory, this should be updated.

The folder is ``app/bin``, the file should be ``artifactory.bat`` or ``artifactory.sh``

**Comment by knatten** [comment]
Ah, too bad, then I'm running the correct script and my problem is something else. Where's the best place to report issues / ask for help running that script? It just keeps printing this warning:

> Retry 170 Elapsed 1.4 minutes failed: Registration with router on URL http://localhost:8046 failed with error: UNAVAILABLE: io exception. Trying again

until it fails with

> Cluster join: Service registry ping failed; Error while trying to connect to local router at address 'http://localhost:8046/access': Connect to localhost:8046 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
Application could not be initialized: Connection refused (Connection refused)

**Comment by knatten** [comment]
Thanks a lot! We'll probably end up with a self hosted commercial Artifactory server in the end, we're evaluating our options at the moment. I'll try the 30 day trial later when I'm not about to go on vacation shortly.

I'm running `jfrog-artifactory-cpp-ce-7.39.4-linux.tar.gz`, which I'm pretty sure I got from https://conan.io/downloads.html. I'm on a regular desktop version of Ubuntu 21.04, with no firewalls or anything.

I first tried to run `./artifactory.sh | tee /tmp/artifactory.log` as my regular user (which I believe is what you're supposed to do?), and when it didn't work, I tried running it as root with `sudo ./artifactory.sh | tee /tmp/artifactory-root.log`. Here's the log from the run as root https://www.dropbox.com/s/rsomrbndy9vreyx/artifactory-root.log?dl=0. 

After having run it as root once, it now starts failing in a different way when I run it as my regular user, probably because some files got the wrong permissions when I ran it as root. But I suggest we ignore that problem here. Unfortunately I did not save the logs from running it as non-root, but the failure mode as root seems to be the same as when I initially ran it as non-root.

**Comment by memsharded** [comment]
Apparently, this was already solved and it is working, so all good.
Sending a PR now to fix the docs (that will close this issue, but please don't hesitate to open a new one for any further question, thanks!)

**Comment by knatten** [comment]
Thanks for fixing the docs! I was not able to fix the issue with Artifactory CE, I just ran `conan_server` instead to be able to progress with my investigation. A colleague of mine however found [some other instructions](https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory#114759846426ba6f791464bf9ba31c6f64eea325c) for running Artifactory CE, and that worked for them. So I'll try that instead when I'm back after vacation.
