### ISSUE TITLE
Packages in editable mode: Missing `conan_toolchain.cmake`

### ISSUE THREAD

**Issue by turlucode** [conan-io/docs#2645]
Looking at the example for [Packages in editable mode](https://github.com/conan-io/docs/blob/master/developing_packages/editable_packages.rst) at this step but also on the next:
```
$ cd say

# windows, we will build 2 configurations to show multi-config
$ conan install . -s build_type=Release
$ conan install . -s build_type=Debug
$ mkdir build && cd build
$ cmake .. -DCMAKE_TOOLCHAIN_FILE=conan/conan_toolchain.cmake
$ cmake --build . --config Release
$ cmake --build . --config Debug

# Linux, we will only build 1 configuration
$ conan install .
$ mkdir cmake-build-release && cd cmake-build-release
$ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=conan/conan_toolchain.cmake
$ cmake --build .
```

The `-DCMAKE_TOOLCHAIN_FILE=conan/conan_toolchain.cmake` or `-DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake` don't exist.

**Comment by memsharded** [comment]
Hi @turlucode 

Thanks very much for reporting this. It seems that some of the changes in new ``layout()`` feature changed the file location. Lets fix it.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/docs/pull/2648
