### ISSUE TITLE
Enhance the `options` section in the DOCs

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/docs#266]
Do you mind to enhance the `options` section in the DOCs a bit and describe with an example exactly how to 
1. define an new option
2. assign a value to this new option
3. retrieve a value from this new option
in a conanfile.py

This section is somewhat confusing(detail missing) to a newby and will avoid raising many issues: 
http://docs.conan.io/en/latest/reference/conanfile/attributes.html#options-default-options

Maybe the same goes for settings, env_info, user_info, cpp_info : 
http://docs.conan.io/en/latest/reference/conanfile/attributes.html#settings
http://docs.conan.io/en/latest/reference/conanfile/methods.html#env-info
http://docs.conan.io/en/latest/reference/conanfile/methods.html#user-info
http://docs.conan.io/en/latest/reference/conanfile/methods.html#cpp-info

- Also does `options` need to be defined in the profile too? DOCs does not say that
- Can a new option be a list type/container?

Thanks,

**Comment by memsharded** [comment]
I have published a new improved section for this: http://docs.conan.io/en/latest/reference/conanfile/attributes.html#options-default-options

I think it addresses better the above issues.

The one I don't understand is the "Can a new option be a list type/container?" one

**Comment by Twoflower2** [comment]
Again, thanks for your quick turn-around. 

You answer that one here `Options are defined in package recipes as dictionaries of name and allowed values:`

**Comment by Twoflower2** [comment]
@memsharded 

Why would I get this ERROR defining a new option called `vproc`:

conanfile.py
```python
    options = {"vproc" : [123456] }
```

cmd/output:
```
> conan info
ERROR: Conanfile: 'vproc' value not defined
```

**Comment by memsharded** [comment]
Options need to have a value. The command ``conan info`` shows a dependency graph for a certain install configuration, so all the settings and options have to be defined either as defaults, or in command line:

```bash
$ conan info -o vproc=1234
```

**Comment by Twoflower2** [comment]
Perfect. Please close.
