### ISSUE TITLE
Manual on how to upload to bintray

### ISSUE THREAD

**Issue by Brunni** [conan-io/docs#267]
Hi,

I'm really having a hard time after conan.io repository moved to bintray.

I didn't find a button to create a repository (which I assume that I have to) so I created an organization.
But now the organization expired and I cannot access the repository anymore.

How do I do this correctly for open source stuff?

Btw: I know this page: https://github.com/conan-io/docs/blob/master/packaging/bintray/move.rst
But I cannot do this on my profile page: `On your user profile (or organization profile) click “Add new repository”.
`
Regards
Michael

**Comment by memsharded** [comment]
Yes, the docs page is: http://docs.conan.io/en/latest/packaging/bintray/move.html

You dont need to create an organization, creating repos in your user is fine too. Also, don't know about organizations expiring. Maybe you didn't create an OSS user but a trial one for PRO version?
If you want to connect and chat, and go step by step, I might try to help to check what is happening.

**Comment by memsharded** [comment]
Ok, it could be that you created a premium organization, but that is a trial one, if you are not under a premium account. You should create an OSS organization, make sure you are also running your user under an OSS account, not a premium/trial one. Did you received an email about this?

The conan docs linked above, point to the link: https://bintray.com/signup/oss, which is the one to use for signup an OSS account.

Could this be the issue? Thanks!

**Comment by Brunni** [comment]
I managed to get my account running thanks to conan.io support (twitter) :)

Problem was, that my account was some trial account and no open source account. And it is not possible to convert such an account. So I had to get it deleted and re-create it. :(

**Comment by memsharded** [comment]
Thanks for telling, glad it was solved with our support :)

Sorry for the trouble :( 

Besides syncing with Bintray support, I have just added a very clear and visible warning to the conan docs: http://docs.conan.io/en/latest/packaging/bintray/move.html

I hope with that, the problem doesn't happen again to anyone else. Do you think the issue can be closed now? Any other suggestion of something we could improve? Thanks!
