### ISSUE TITLE
package_files run example wrong

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/docs#269]
https://github.com/conan-io/docs/blob/master/reference/commands/package_files.rst

Run:

>    $ conan package_files Hello/0.1@lasote/stable -s os=Windows -s arch=x86 -s build_type=Release --path=Release_x86

should read at the end `--package_folder=Release_x86` or `-pf Release_x86`

**Comment by lasote** [comment]
This command will be replaced in the comming 0.28 with `export-pkg`
