### ISSUE TITLE
[Documentation] Missing 2.0 migration docs for tools.collect_libs() 

### ISSUE THREAD

**Issue by stackfun** [conan-io/docs#2702]
Documentation update request:

The `self.collect_libs()` and `from conans.tools import collect_libs` was [removed in conan 2.0](https://github.com/conan-io/conan/issues/3716) but it is not mentioned in the 2.0 recipe migration docs here https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html

The replacement for conan 2.0 is `from conan.tools.files import collect_libs`

Maybe its worth double checking all the API's that were removed in conan 2.0

**Comment by SpaceIm** [comment]
fixed by https://github.com/conan-io/docs/pull/2700
