### ISSUE TITLE
`dummy build` concept is not well explained

### ISSUE THREAD

**Issue by SSE4** [conan-io/docs#2742]
v2 migration talks about some `dummy build` concept "explained above", but it's actually never explained
https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#the-build-method

**Comment by SSE4** [comment]
@czoido pointed it's explained in https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#the-generate-method (but that's not obvious)
1. `dummy build` should be searchable (as a whole thing, not as separated words). right now there is only 1 match.
2. if it's some important concept referenced in other places, it should have its own title/section
3. cross reference should be more helpful than just vague `explained before` (where exactly?)
4. I would also change `nothing special` part - it doesn't deliver any useful information to the user (especially, newcomer). what actually does it mean?

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/docs/pull/2744
