### ISSUE TITLE
[question] How to specify imports in conanfile.txt with root_package

### ISSUE THREAD

**Issue by jpfeuffer** [conan-io/docs#2783]
In the docs it says it supports the same params as the imports function. What does that mean?
`pattern=.@dst=./cmake@root_package=cmake` does not work. Neither without the `key=` values.
And the examples given with the `x,y -> z` syntax are incredibly basic and do not include specific packages.

**Comment by memsharded** [comment]
For reference https://docs.conan.io/en/latest/reference/conanfile_txt.html#imports

The syntax is:
```
[imports]
., license* -> ./licenses @ folder=True, ignore_case=True, excludes=*.html *.jpeg
```
That is, the first ``x, y -> z`` are source, pattern and destination, and then after the ``@`` it is  possible to specify the other arguments.

In any case, please note that ``imports`` feature is being removed in 2.0, the recommended modern way is:

- Use the ``generate()`` method in the consumer
- In the ``generate()`` method, iterate the ``self.dependencies``
- Use ``copy(self, ...)`` from the new ``from conan.tools.files import copy``

**Comment by jpfeuffer** [comment]
Yes sorry. It is actually mentioned in a small example after the description. I misunderstood the @ usage.

But how can I use "generate" in a conanfile.txt if this gets deprecated?

**Comment by memsharded** [comment]
It needs to be a ``conanfile.py``. The rationale is explained in the 2.0 docs: https://docs.conan.io/en/2.0/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html, everything that is beyond the basic usage of ``conanfile.txt`` can be done in the ``conanfile.py``

**Comment by jpfeuffer** [comment]
I see. So instead of using the imports category or the equivalent imports function in a conanfile.py, I have to put it in the generate function?
In there, can I just call the generator that I am using and after that use the copy method? Does the copy method have the same signature as the one that was previously advertised for use in the imports function?

**Comment by memsharded** [comment]
The ``copy()`` method should also be the one from the new tools: https://docs.conan.io/en/latest/reference/conanfile/tools.html, see details https://docs.conan.io/en/latest/reference/conanfile/tools/files/basic.html#conan-tools-files-copy

Yes, you can call any number of generators, and then call your ``copy()`` logic after it (or before the generators too, doesn't really matter)
