### ISSUE TITLE
[bug] Wrong prefix for AutotoolsToolchain (or wrong docs)

### ISSUE THREAD

**Issue by dubvulture** [conan-io/docs#2795]
The [documentation](https://docs.conan.io/en/latest/reference/conanfile/tools/gnu/autotoolstoolchain.html) for AutotoolsToolchain states that:

- **configure_args: Additional arguments to be passed to the configure script.**
    - **By default the following arguments are passed:**
        - `--prefix`: With the self.package_folder value.

But the code seems to default to **/**, see [here](https://github.com/conan-io/conan/blob/6fc624d4c1ec165618f9426172b2b0ec569b4de4/conan/tools/gnu/autotoolstoolchain.py#L205).
This was changed in conan-io/conan#11284, before that it was set as stated in the documentation.

**Comment by jellespijker** [comment]
> Thanks for reporting @dubvulture, The documentation is indeed wrong, we'll fix it, I'm transferring this to the docs repo. @jellespijker Regarding the problem with Windows there's a PR open: [conan-io/conan#12193](https://github.com/conan-io/conan/pull/12193) there are some tests pending but we will try to push it for the next release.

that is excellent news 👍
