### ISSUE TITLE
[bug] Wrong documenation with `self.folder.source`

### ISSUE THREAD

**Issue by gabyx** [conan-io/docs#2866]
### Environment details

* Operating System+version: n/a
* Compiler+version: n/a
* Conan version: 1.53

### Steps to reproduce

Documentation:

I still think something is wrong with the documentation:

Here https://docs.conan.io/en/latest/developing_packages/package_layout.html#example-export-sources-folder
it states that cwd in `source()` is same as `self.folders.source = 'src'`, and that is also what I experience in `source()` when debugging, and that is not
what is stated here : https://docs.conan.io/en/latest/reference/conanfile/methods.html#self-folders

> But the current working directory in the `source(self)` method will not include this subfolder, because it is intended to describe where the sources are after downloading (zip, git…) them, not to force where the sources should be. As well, the

What is the case now, and how was it desined?

**Comment by memsharded** [comment]
This should fix it: https://github.com/conan-io/docs/pull/2867

It makes the ``self.folders.source`` behavior with regards to the ``source()`` method also the same as the ``self.folders.build`` with regards to the ``build()`` method.

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/docs/pull/2867

**Comment by gabyx** [comment]
**Thanks @memsharded : Thats now much better to have ground truth what happens.**

Although I dont know how to specify `self.folders` such that I clone into `~/.conan/.../source/.` (possibly `self.folders.source = "."`)
and that CMake configures in `~/.conan/.../source/a/b/c` because my project is inside `a/b/c`.

Any suggestion?

**Comment by memsharded** [comment]
I think this might be the ``cmake.configure(build_script_folder=`` argument?
One thing is where are your sources, like the root folder of your sources, this is defined by the layout.
If ``CMake`` needs to locate the entry ``CMakeLists.txt`` in a subfolder of the sources that is not the root one, this can be specified by ``build_script_folder``.

In this example, things are cloned in the ``src`` folder, but the CMakeLists will be inside ``subfolder``


```python
     def layout(self):
        self.folders.source = "src"

    def build(self):
        assert os.path.exists(os.path.join(self.source_folder, "subfolder", "CMakeLists.txt"))
        cmake = CMake(self)
        cmake.configure(build_script_folder="subfolder")
        cmake.build()
```

**Comment by gabyx** [comment]
OK, thats a solution.

What I dont get here from the design is the following:

Example here: https://docs.conan.io/en/1.56/reference/conanfile/methods.html?highlight=source#source

> The current working directory where the source() method runs is the self.source_folder. Note, however, that this folder can be different if the recipe defines the layout() method and specifies a self.folders.source = "src". In that case, the self.source_folder and the current working directory will be the composition of the base folder (typically where the recipe is) and the user specified "src" subfolder.

This is all fine and now aligned with the fix in this corresp. PR.
But: You would specify `subfolder/myproject-with-cmake` (in example `src`) as `self.folders.source` to point to the source. But now in the `source()` folder you are in this directory, but `git clone` must run 2 folders up in `../..`. I don't get this design decision? (Saying: The initial documentation in this question, was much more concise.)

What we did is that our special `git clone` method traverses upwards as many parts you have in `self.folders.source` and do the clone there.

**Comment by memsharded** [comment]
> But: You would specify subfolder/myproject-with-cmake (in example src) as self.folders.source to point to the source. But now in the source() folder you are in this directory, but git clone must run 2 folders up in ../... I don't get this design decision?

Because if you are packaging a third party (conanfile.py not in the sources repo), the source folder is intended to be the root of what you are cloning, not any subfolder inside what you are cloning, and the ``self.folders.source = "src"`` is a mechanism to keep your current ``conanfile.py`` project clean (you can ``.gitignore`` the ``src`` subfolder). Whatever directory structure you have inside ``src`` is mostly irrelevant, as it is not your source code, but a third party, so it doesn't matter what hierarchy is inside, and only ``CMake`` needs to be informed where to locate the starting ``CMakeLists.txt``?
