### ISSUE TITLE
broken link from docs.conan.io

### ISSUE THREAD

**Issue by AndreiCherniaev** [conan-io/docs#2911]
I open https://docs.conan.io/en/2.0/tutorial/consuming_packages/build_simple_cmake_project.html
I push "Edit on GitHub"
I get error 404

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/docs/commit/cd032670ef690aaf704e01574bd550eeb1dc57f0, thanks very much for reporting! (it might take some time to deploy live)
