### ISSUE TITLE
Create your first Conan package with Meson example

### ISSUE THREAD

**Issue by czoido** [conan-io/docs#3066]
An example [for the examples section](https://docs.conan.io/2/examples.html), similar to this part of the tutorial https://docs.conan.io/2/tutorial/creating_packages/create_your_first_package.html but for Meson.

**Comment by memsharded** [comment]
I have been doing some support in https://github.com/conan-io/conan/issues/13344, and it needs some fix in the associated PR to work with ``tool_requires`` (it works if meson+pkgconf+ninja are in the environment, but not in Conan packages):

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/docs/pull/3621
