### ISSUE TITLE
Unable to create lockfile

### ISSUE THREAD

**Issue by gabeblack** [conan-io/docs#3075]
I've created a binary-only conan package (my conanfile.py only defines the `build` and `package` methods). The conanfile.py contains values for `name`, `version`, `settings`, and several optional attributes (e.g., `url`).

The package is created just fine via `conan create path/to/conanfile.py  my_pkg/1.0@my/reference` and I'm able to verify the files are exported in the `package` subfolder in my local conan cache.

However, I'm unable to create a lockfile for the package. I've tried various methods:

`conan lock create /path/to/conanfile.py`
`conan lock create --reference=my_pkg/1.0@my/reference`
`conan lock create --reference=my_pkg/1.0@my/reference --name=my_pkg --version=1.0`

I also tried variations of the above adding the `--lockfile-out=conan.lock` option.

No matter what I get the error: "**Error while initializing requirements. Specify the 'name' and the 'version'**"

I manually exported the package in case that was required: `conan export . my_pkg/1.0@my/reference`

How do I create a lockfile? I googled and didn't find any hits for what I'm running in to other than someone suggesting to use --reference, so I must be really doing something wrong... I'm using `conan version 1.59` if that matters.

Thank you in advance!

**Comment by memsharded** [comment]
Hi @gabeblack 

> . I'm using conan version 1.59 if that matters.

**Comment by gabeblack** [comment]
Ok, I reproduced it. I have a cmake script that runs "configure_file" to populate some fields in a generated conanfile.py file. If the `requires` attribute with a list containing an empty string (e.g., `requires=[""]`) it fails in that manner. That is understandable and an error on my part. I got confused because I thought it was my package name/version that it was complaining about, not the package dependencies. Anyway, thank you for the response!

BTW, I had switched to conan 2.0, but then switched back. The reason being that `conan create` command changed (no longer has the reference in the command), but the docs were still incomplete on how to migrate (still had "TODO" in the documentation). Since our packages have references in them, I wasn't sure how to migrate to creating them without references. So I thought 2.0 was probably a little to fresh to migrate to and I'd do it perhaps a little later.

**Comment by memsharded** [comment]
> Ok, I reproduced it. I have a cmake script that runs "configure_file" to populate some fields in a generated conanfile.py file. If the requires attribute with a list containing an empty string (e.g., requires=[""]) it fails in that manner. That is understandable and an error on my part. I got confused because I thought it was my package name/version that it was complaining about, not the package dependencies. Anyway, thank you for the response!

Great, happy to know you found the reason. 

> The reason being that conan create command changed (no longer has the reference in the command), but the docs were still incomplete on how to migrate (still had "TODO" in the documentation).

It would be good to know a bit more. You mean the migration guides in https://docs.conan.io/1/conan_v2.html? Because the docs for Conan 2.0 are already available and quite complete, including reference for the commands in https://docs.conan.io/2

In your case, the syntax would be ``conan create . --name=pkg --version=0.1`` instead of passing the reference.

I am closing this issue as solved, but please open new ones if you have any further questions. Thanks!
