### ISSUE TITLE
Conan 2 documentation, introduction to versioning, conan list uses conanv2 as remote instead of conancenter

### ISSUE THREAD

**Issue by benjaminchauvin** [conan-io/docs#3116]
In the documentation:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/31856424/226141620-12edafff-b034-43f9-9579-34f3020576ed.png">

On my machine:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/31856424/226142095-14caa8e5-05bc-4e01-82b6-352eb3881406.png">

 It seems that the remote should be `conancenter` instead of `conanv2`.

**Comment by memsharded** [comment]
Good point, thanks for reporting @benjaminchauvin, you are right, this comes from the beta stage, needs to be updated.

Would you like to submit a PR to ``release/2.0`` branch to fix it yourself?

**Comment by benjaminchauvin** [comment]
> Good point, thanks for reporting @benjaminchauvin, you are right, this comes from the beta stage, needs to be updated.
> 
> Would you like to submit a PR to `release/2.0` branch to fix it yourself?

Thanks for your feedback @memsharded . Sure, I will create a PR shortly and let you know.

**Comment by benjaminchauvin** [comment]
@memsharded I created a PR: https://github.com/conan-io/docs/pull/3117

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/docs/pull/3117
