### ISSUE TITLE
conanbuildenv.sh have wrong order of exported variables

### ISSUE THREAD

**Issue by xiaoliangwu** [conan-io/docs#3118]
Hi,
please help to check the wrong export order in conanbuildenv.sh when we have multi profiles, like:

**profile1:**
```
[buildenv]
base_var=base_value
```

**profile2:**
```
include(profile1)
[buildenv]
myvar=$base_var some_extra_values
```

now, when I install with --profile profile2,  in the generated conanbuildenv.sh , we expect to have:

```
export base_var="base_value"
export myvar="$base_var some_extra_values"
```

however, the content is

```
export myvar="$base_var some_extra_values"
export base_var="base_value"
```

so $myvar  only have "some_extra_values" without "base_value" as base_var is exported after it.

thanks

**Comment by memsharded** [comment]
Hi @xiaoliangwu 

Thanks for your report.

First, please let me suggest that the use of that custom variables text-replacement has already been superseded by jinja templates in Conan 1.X and it has been completely removed in Conan 2.0. 

Second suggestion, you shouldn't rely on order of variables for appending operations. The ``[buildenv]`` has explicit ``append``, ``prepend``, ``define`` and ``unset`` operations. If you want to perform appending/prepending to an existing value, please use the ``varname+=`` or ``varname=+`` for that. Use the ``varname+=(path)path/value`` for paths.

**Comment by xiaoliangwu** [comment]
OK, thanks for the comment. another problem I have is : the "import" cannot import a files on parent directory like "include" did. when we can run  include("../basefile") , however, {% import "../basefile" as base %} not work. is it on purpose?

**Comment by memsharded** [comment]
I think that is a limitation of the ``jinja`` templating system.
We added ``profile_dir`` variable to jinja context, pointing to the folder containing the profile, so it can be used to compute absolute paths from it.

**Comment by xiaoliangwu** [comment]
maybe we can add "profiles" root , that is ".conan2/profiles" , so user can import any files under it. if we give the profile_dir to the profile file dir, then we have no way to access other files other than files that under this dir. 

for example:
.conan2/profiles/common/debug
.conan2/profiles/common/gcc
.conan2/profiles/linux64/gcc-debug

then when we install  "gcc-debug" , we cannot import "../common/gcc" unless we create symbol links

**Comment by memsharded** [comment]
Problem with that approach is that profiles are intended to work also on user space, and there are many users that use profiles not installed in the Conan cache. Adding the profiles root to the import path could be causing unexpected priority errors which would be probably difficult to understand. This is the reason we recommend using relative paths and flat structures.

**Comment by xiaoliangwu** [comment]
understand. thanks for the explanation
