### ISSUE TITLE
what's the suggested way in CICD

### ISSUE THREAD

**Issue by xiaoliangwu** [conan-io/docs#3131]
Hi
  in CICD pipeline, we can run:
      conan create .
or with a set of commands like
      conan source . && conan install . && conan build . && conan export-pkg . 

which one is the best practise ?

thanks

**Comment by memsharded** [comment]
Hi @xiaoliangwu 

Thanks for your question.
The ``conan source + install + build + ...`` is in general intended as the "developer flow". So developers can do ``conan install``  to install dependencies, then ``cmake`` (or other build system) to develop locally, then they can do ``conan build`` to test locally if the build works, and ``conan export-pkg`` to test locally the package too.

But in CI a ``conan create`` is simpler, and the recommended approach in most cases.

**Comment by xiaoliangwu** [comment]
ok, if we go with "conan create" approach,and we use revision_mode="scm" , so we can guarantee that the repo is clean ( everything is committed ).

how about we save the commit_id in export(), like

    update_conandata(self, {"sources": {"commit": scm_commit, "url": scm_url}})

in source() , we checkout the code using

    git.clone(url=sources["url"], target=".")
    git.checkout(commit=sources["commit"])

so we don't need to copy source to export_source_folder and then to source_folder. is it a suggested practise?

**Comment by memsharded** [comment]
Yes, I think you are describing the process documented in https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html. Please have a look and let me know if this is what you are looking for

**Comment by xiaoliangwu** [comment]
yes, so this is a preferred or suggested way than using "export_sources()" to copy the local source tree , right?

**Comment by memsharded** [comment]
> but scm capture method is faster IMHO , at least we save a copy process to export_source_folder, right?

As discussed above, the extra copies (both speed or storage) wouldn't be the bottleneck in most scenarios, as it would only be a fraction of the build time anyway, so I wouldn't bother about this and go with the most pragmatic and simplest approach.

That would be quite easy to benchmark. If you can do a ``conan create`` with the ``exports_sources`` approach, and print the relative time of the different steps and overall time of the process, that would allow us to understand the issue better.

**Comment by memsharded** [comment]
I like the "premature optimization is the root of all evil" famous quote by Sir Tony Hoare (popularized by Donald Knuth). I tend to be as pragmatic and keep things as simple as possible, until they really become the bottleneck.

Thanks for your feedback!
