### ISSUE TITLE
[bug] Tutorial multi-config layout on Linux does not work as expected

### ISSUE THREAD

**Issue by npuichigo** [conan-io/docs#3133]
### Environment details

* Operating System+version: Ubuntu 20.04
* Compiler+version: gcc 8
* Conan version: 2.0.2
* Python version: 3.10

### Steps to reproduce

https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html#use-the-layout-method

In tutorial, the build folder on Linux show be `f"build/{str(self.settings.build_type)}"` according to 
```
self.folders.build = "build" if multi else f"build/{str(self.settings.build_type)}"
```

but there's no folder named `build/Release` during building

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/docs/pull/3140
