### ISSUE TITLE
[question] How to define ABI compatibility for Visual Studio

### ISSUE THREAD

**Issue by forry** [conan-io/docs#3139]
### What is your question?

Hello,
I'm considering migrating our repository to conan 2.0. We have lot's of packages with prebuilt binaries for Visual Studio. The recipes mostly only define one method telling that different compiler versions and toolsets are compatible so you can mix and match them. This yields a lot of combinations. The package binaries were loaded using `export-pkg` with the -pf argument so we don't have the binary duplication in the export folder. 

1) I don't see a -pf argument in export-pkg anymore is it somehow replaced by defining a layout? How?
2) Even when I just run `conan export-pkg . --user=user --channel=prebuild` the conan complains: `ConanException: 'self.settings' access in 'package_id()' method is forbidden`. I have read about the compatibility() method but since I'm not a python programmer I don't quite understand if that applies to my case and if yes, how exactly I'm to generate the resulting super object for this case - all of the different combinations of compilers and toolsets.

Here is the example conanfile.py:

```
from conan import ConanFile
from conans.model.version import Version

class SomePackage(ConanFile):
    name = "somepackage"
    version = "1.0.0.38"
    license = ""
    author = "***"
    url = "***"
    no_copy_source = True
    settings = "os", "compiler", "arch"
    
    def package_id(self):
        v = Version(str(self.settings.compiler.version))
        toolset = str(self.settings.compiler.toolset)
        if self.settings.compiler == "Visual Studio" and (v >= "15" and v <= "17") and any((toolset == x for x in ["None", "", "v141", "v142", "v143"])):
            self.info.settings.compiler.version = "15 compatible"
            self.info.settings.compiler.toolset = "v141 compatible"

```

Thanks
Forry

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/docs/pull/3140

**Comment by forry** [comment]
No, thank you very much. My mistake was to assume that the release of 2.0 meant that the doc is complete and that I'd skipped most of the tutorial parts (to save time) to go to the things that I was interested in in the reference, since I knew the conan 1, or tried to find corresponding chapters to get a refresher. I need to backtrack a little and get a feel for it, then I will probably raise a new question/suggestion about the compatibility and its documentation unless I find it open.

**Comment by memsharded** [comment]
Good, thanks very much for the feedback!
Don't hesitate then to open new tickets if you have further questions.

**Comment by forry** [comment]
Quick one. Have you fixed the second one in the migration guide (https://docs.conan.io/1/migrating_to_2.0/recipes.html#migrate-conanfile-compatible-packages-to-the-new-compatibility-method) in the "To" section there seems to still be a `self.settings`, after a hard refresh. I guess it would work in conan 1 but not in conan 2? Or is the `self.settings` ok to use in the compatibility() method, which then leaves me confused even more :)?
