### ISSUE TITLE
Is defining ABI compatibility in the producer instead of the consumer possible/desired?

### ISSUE THREAD

**Issue by niosHD** [conan-io/docs#3153]
As far as I understood, by default, conan assumes that dependencies follow semantic versioning and that I can override the default in the `package_id` method of the consuming recipe. (see https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#versioning-schema)

However, when a package does not follow semver, does this mean that every consuming recipe has to override the versioning scheme or is there a possibility to define this directly within the package?

For reference, I had the following discussion with Hipony (Thank you!) on Slack who encouraged me to open this issue:

> Hipony [11:12 AM]
>> @niosHD that's an interesting question, docs are confusing here and I can't really tell how to do it from the producer. They describe how consumer can describe compatible packages, but it would make much more sense to describe ABI rules in the recipe so each consumer would automatically get version scheme for each package, by rules defined by package' maintainers. And fixing `package_id` is not an option since it's an end-user feature. Confusing indeed! :thinking_face:
>> Basically it requires for an end user to have consuming rules, because you can't really control it from the producer side

> niosHD [11:33 AM]
>> @Hipony Right, I would also prefer to express the ABI guarantees as part of the actual package and was hoping that I just missed this possibility, hence the question.

>Hipony [11:37 AM]
>> It's a bit tricky, I feel you that it have much more sense to define ABI compatibility from the producer part, but then it would require to inspect dependency recipes from the consumer recipe and they can contradict with each other (one thing to be ABI compatible with semver and the other with different users/channels).
>> and keep in mind that dep recipes could be changed at any time with their respective compatibility values
>> tricky!

> niosHD [11:48 AM]
>> Semantically, specifying the default ABI compatibility in the producer with possibility to override it in the consumer seems to be what I want. However, I agree that implementing this may be tricky. I assume that the full dependency tree has to be evaluated in order to decide if a binary package can be used. I don't know if this is also required in the current model but if not than this would probably be unacceptable in terms of overhead. Let's see what others think that are deeper in the conan internals.

>Hipony [11:51 AM]
>> I think this is a important use case, although it would be a pretty big change in internals.

**Comment by memsharded** [comment]
This has been now documented as attributes and in the binary compatibility section, closing as solved
