### ISSUE TITLE
Conan as a build tool 

### ISSUE THREAD

**Issue by mdzahid989** [conan-io/docs#3154]
Can i use conan as build tool - Our current build system in gmake.
Suppose - i want to build submodule or an executable - can i use conan build to build that ?

For rnd development - what is recommended ?
conan install ; conan build or
conan install ; gmake

**Comment by memsharded** [comment]
Hi @mdzahid989 

In Conan 2.0 ``conan build`` already does ``conan install + calling build()``

Both can be perfectly good, depending on the use case. 
The ``conan install`` + calling your build system (gmake, cmake, ...) is the most typical developer flow, it integrates better with other tools like IDEs, etc. The new "transparent" integrations based on file generation in the ``generate()`` method and helpers like ``CMakeToolchain`` and ``CMakeDeps`` and the ``layout()`` definition helps with this. For ``gmake`` I guess ``AutotoolsToolchain`` and ``PkgConfigDeps`` might be useful.


The ``conan build`` can help to automate calling the build system, can be convenient for CI or when developers don't really care about developing code or calling the build system directly.

**Comment by mdzahid989** [comment]
Thanks @memsharded  - Your answers are really helpfull 
Have a great day.

**Comment by memsharded** [comment]
Happy to help :) 

If the response is good, then we can close the issue. Don't hesitate to re-open or create new tickets if you have any further question. Thanks!
