### ISSUE TITLE
custom generator in conan2

### ISSUE THREAD

**Issue by xiaoliangwu** [conan-io/docs#3192]
Hi,
  Do we still have custom generator in conan2?

https://docs.conan.io/1/reference/generators/custom.html#custom-generator

I check the https://docs.conan.io/1/conan_v2.html#conan2-migration-guide , but not sure which feature is the replacement

thanks

**Comment by czoido** [comment]
Hi @xiaoliangwu,

Thanks for the question. I'm pasting here the [answer](https://github.com/conan-io/conan/issues/13758#issuecomment-1520602907) to a similar question in the Conan repository. This is something that we definitely need to improve in the Conan docs:

There are 2 things that replace the 1.X previous custom generators packages, depending on the use case:

- For the general case, explicit ``python_requires`` are recommended, that instantiate a helper explicitly in the consumers ``generate()``. That means that the consumers should be ``conanfile.py`` with a ``generate()`` method. This method is good for many reasons:
  - Independent, private versioned dependencies: so every package can evolve at their pace, and doing a breaking change to the generator doesn't break all consumers at all
  - ``python_requires`` affect ``package_id`` of the consumers, so correct versioning can be used to trigger re-builds or to not trigger to save CI time
- Global generators, installable in the cache with ``conan config install`` will be added in 2.0.5: https://github.com/conan-io/conan/pull/13718

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/docs/pull/3213
