### ISSUE TITLE
Complete Development Workflow Hands On Guide

### ISSUE THREAD

**Issue by azriel91** [conan-io/docs#32]
Currently there are many small hands-on tutorials on certain parts of a complete workflow, and I had to keep many tabs open and jump between them (tutorials, packaging, reference pages) to figure out how things fit together.

I intended to write a guide for the full development cycle, but ended up writing bits on "how things work" and realized there's still parts I don't understand ([#16 package command!](https://github.com/conan-io/docs/issues/16))

See [Conan Quickstart](https://gist.github.com/azriel91/29e5c1e09367aa9eacd1) for my initial write up, and search for `TODO` for parts I wasn't certain about.

My write up may be incorrect, feel free to copy it over and fix up any technically incorrect parts (need to translate markdown to restructured text), otherwise I probably will in the future. I can fix grammar and paraphrase later as well.

**Comment by monsdar** [comment]
I think it could be useful to write about common usecases (not only the development workflow) to get the idea across on how Conan is supposed to be used and how the workflows are intended. I also had the experience that the documentation describes how everything works, but not how everything fits together. A "What do you want to do?"-format could be helpful.

Usecases I could think of:

1. Using Conan as a developer (add Boost, ZeroMQ, ... to your component)
1. Using Conan as a distributor (using conanfile.py)
1. Using Conan as a distributor of binary packages (having precompiled thirdparty releases available)
1. Using Conan as a tester
1. Using Conan in Continuous Integration
1. Using Conan for deployment

The first 3 cases are covered I think. I currently try to get my head around on how I could use Conan in our CI environment or if it is useful for deployment too.

**Comment by memsharded** [comment]
Yes, exactly, the docs are structured from moving the reader from point 1, to point 2 and 3.

Currently some improvements are being done (it can be certainly used in testing and CI, other users are doint it), for the development/test case, for example, the definition of "scopes": https://github.com/conan-io/conan/pull/290

It is true that use case 6 is not addressed yet, it is quite an orthogonal concern. Sure conan generators can be done to make easier the creation of installers .deb, .msi, etc, but so far conan is quite centered on the developer view, not so much in the sysadmin/devops point of view.

As things keep moving forward and evolving we will add those use cases to the docs. I like very much you idea of "What you want to do?", I will use it next time I am on the docs. The truth is that many times conan users are moving faster and the docs are difficult to keep in sync. If you have any question about cases 4, 5 and 6. Just ask. Thanks!

**Comment by monsdar** [comment]
Just asked about CI in the conan [main project](https://github.com/conan-io/conan/issues/308).

**Comment by jgsogo** [comment]
A lot of things have been already documented since this pull-request was opened. If there is something needed, some generic use case to document, it's better to open a dedicated pull request to work on it.
