### ISSUE TITLE
Add a note about Ubuntu 23.04 when installing Conan with pip

### ISSUE THREAD

**Issue by uilianries** [conan-io/docs#3205]
For Ubuntu 23.04, first is needed to create a virtual environment before running `pip` command. 

https://docs.conan.io/2/installation.html#known-installation-issues-with-pip

https://www.reddit.com/r/Python/comments/1338oge/you_cant_use_pip_on_ubuntu_2304_anymore/

**Comment by samuel-emrys** [comment]
It's already on the installation page, but you should really push installation using `pipx` here - it installs python applications into a virtualenv and makes them available in the global context.. pretty much exactly what you would have to do manually here.

**Comment by memsharded** [comment]
The PR #3360 is enough to close this ticket?

**Comment by uilianries** [comment]
@memsharded Yes, it's clear and useful. Thank you @czoido !!!
