### ISSUE TITLE
[question] Please document `settings_target` and its difference from `settings`

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/docs#3208]
### What is your question?

I'm curious about the difference between `self.settings` and `self.settings_target`. I understand that `self.settings_build` refer to settings on the build machine, and that `self.settings` refer to host (target) for which package is built. However, why is then `self.settings_target` needed?

I've search the documentation for `settings_target` keyword, and [found almost nothing](https://docs.conan.io/2/search.html?q=settings_target&check_keywords=yes&area=default). There is only a obscure mention in ["Adding information" part](https://docs.conan.io/2/reference/conanfile/methods/package_id.html?highlight=settings_target#adding-information) of the `package_id` method documentation , a brief mention in [XCRun documentation](https://docs.conan.io/2/reference/tools/apple/other.html?highlight=settings_target#conan-tools-apple-xcrun), without any explanation, and [a broken link](https://docs.conan.io/2/tutorial/creating_packages/other_types_of_packages/tool_requires_packages.html?highlight=settings_target#read-more) in "Read more" section of "Tool requires packages".

I've basically discovered the `settings_target` by reading [these weird comments](https://github.com/conan-io/conan-center-index/blob/master/recipes/android-ndk/all/conanfile.py#L257-L269) in the official Android NDK conan package.

While creating my own NDK conan package, I wanted to make a similar validation, so I initially wrote the `validate` method in my recipe like this:

```python
def validate(self):
    if self.settings.os != "Android":
        raise ConanInvalidConfiguration(
            f"You've added {self.ref} as a build requirement, while os={self.settings.os} != Android"
        )
    if self.settings.compiler != 'clang':
        raise ConanInvalidConfiguration(
            f"Android NDK only supports clang compiler, while compiler={self.settings.compiler} != 'clang'"
        )
    if self.settings.compiler.libcxx not in ['c++_static', 'c++_shared', 'libc++v2']:
        raise ConanInvalidConfiguration(f'Unsupported libcxx library:{self.settings.compiler.libcxx}')
```

However, this validation always failed, both when creating the package (which is kind of expected, since I was creating the package using profile for my mac), **and while using the package** (which I didn't expect, since host system was now Android, and build system was mac, so WTF?!?).

Then, I rewrote my `validate` like this:

```python
def validate(self):
    if self.settings_target.os != "Android":
        raise ConanInvalidConfiguration(
            f"You've added {self.ref} as a build requirement, while os={self.settings_target.os} != Android"
        )
    if self.settings_target.compiler != 'clang':
        raise ConanInvalidConfiguration(
            f"Android NDK only supports clang compiler, while compiler={self.settings_target.compiler} != 'clang'"
        )
    if self.settings_target.compiler.libcxx not in ['c++_static', 'c++_shared', 'libc++v2']:
        raise ConanInvalidConfiguration(f'Unsupported libcxx library:{self.settings_target.compiler.libcxx}')
```

... and this failed with accessing `None` object, because apparently sometimes `self.settings_target` is None. Why? I've seen this being raised as [an issue](https://github.com/conan-io/conan/issues/13515) where another toolchain is being packaged into conan.

My final version of `validate` is this:

```python
def validate(self):
    if self.settings_target is not None:
        if self.settings_target.os != "Android":
            raise ConanInvalidConfiguration(
                f"You've added {self.ref} as a build requirement, while os={self.settings_target.os} != Android"
            )
        if self.settings_target.compiler != 'clang':
            raise ConanInvalidConfiguration(
                f"Android NDK only supports clang compiler, while compiler={self.settings_target.compiler} != 'clang'"
            )
        if self.settings_target.compiler.libcxx not in ['c++_static', 'c++_shared', 'libc++v2']:
            raise ConanInvalidConfiguration(f'Unsupported libcxx library:{self.settings_target.compiler.libcxx}')
```

... which works correctly, but I don't understand why.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @DoDoENT,
We have just added a [whole section](https://github.com/conan-io/docs/pull/3625) with a detailed explanation on how to create a recipe for a toolchain, hope this is enough to close the ticket but please feel free to reopen if you have any more questions.

**Comment by DoDoENT** [comment]
It looks great! Thanks!
