### ISSUE TITLE
Typo in RunEnvironment example

### ISSUE THREAD

**Issue by uilianries** [conan-io/docs#322]
Hi!

The example for `RunEnvironment` in docs is wrong. The snippet uses the module `AutoToolsBuildEnvironment` instead of `RunEnvironment`.

http://docs.conan.io/en/latest/mastering/build.html#runenvironment

It's a very simple type, but newbies can be confused about that.

Regards.

**Comment by memsharded** [comment]
You meant the ``import``, right? Done: http://docs.conan.io/en/latest/mastering/build.html#runenvironment

**Comment by uilianries** [comment]
Yes.
