### ISSUE TITLE
[question] Search existing binary packages in Conan 2.0

### ISSUE THREAD

**Issue by fschoenm** [conan-io/docs#3245]
### What is your question?

In Conan 1.x, it was possible to search for existing binaries in the cache or a remote. It looked like this (and was documented in the CLI help):

    $ conan search zlib/1.2.13@
    Existing packages for recipe zlib/1.2.13:

        Package_ID: 26fcc0328f1f040b7758678448266b1788141aab
            [options]
                fPIC: True
                shared: False
            [settings]
                arch: x86_64
                build_type: Debug
                compiler: gcc
                compiler.version: 10
                os: Linux
                os.glibc: 2.31
            Outdated from recipe: False

        Package_ID: ad1b339313aea1c712b773cfc45cbdce89108d61
            [options]
                fPIC: True
                shared: False
            [settings]
                arch: x86_64
                build_type: RelWithDebInfo
                compiler: gcc
                compiler.version: 10
                os: Linux
                os.glibc: 2.31
            Outdated from recipe: False

I couldn't find anything similar in Conan 2.0. What is the equivalent command there?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by fschoenm** [comment]
@czoido, unfortunately that also doesn't work:

    $ conan2 list -r vsdk "zlib/1.2.13@vsdk/stable#*:*"
    vsdk
      zlib
        zlib/1.2.13@vsdk/stable
          revisions
            0 (2023-05-17 13:11:00 UTC)
              packages
            ededf45d1afa40f8c445ce1a4b4f9e70 (2023-05-17 13:35:02 UTC)
              packages

**Comment by czoido** [comment]
Yes @fschoenm, I'm afraid it's not possible. You can have recipes with syntax compatible between 2.0 and 1.X to allow migration but reusing Conan 1.X packages in 2.0 is not possible as all the resolution of the dependency graph completely changed with the new graph model.

**Comment by fschoenm** [comment]
@czoido I see. Would be useful to mention that at the very top of your migration guide because I didn't read that information anywhere and the migration guide makes it sound like you can have recipes/packages that are compatible with conan 1.x and 2.x.

**Comment by czoido** [comment]
Thanks @fschoenm we'll improve the docs ASAP

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/docs/pull/3247
