### ISSUE TITLE
AutoPackager doc is wrong

### ISSUE THREAD

**Issue by fschoenm** [conan-io/docs#3251]
I tried to work along the documentation of the `AutoPackager` (https://docs.conan.io/2/reference/tools/files/packaging.html).

The page seems to have multiple errors. For example, it talks about something like `self.cpp.local.*` directories but that property doesn't exist and leads to errors. Correct seems to be something like `self.cpp.source.*` instead (though I might be wrong because the documentation lacks).

The definition of patterns seems to be also wrong because I have to set `packager.patterns.source.include` instead.

The whole page could use a rework.

**Comment by memsharded** [comment]
Hi @fschoenm 

Thanks for pointing this out. Indeed the AutoPackager docs are outdated, seems based on an older implementation. I'll fix it.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/docs/pull/3253
