### ISSUE TITLE
Getting Started / Example project  does not work with conan 2.0.6

### ISSUE THREAD

**Issue by apivovarov** [conan-io/docs#3258]
[getting_started](https://docs.conan.io/1/getting_started.html)

Example project 
```
$ git clone https://github.com/conan-io/examples.git && cd examples/libraries/poco/md5
```

First error - Missing dependencies error when running
```
conan install ..

# it should be replaced with 
conan install .. --build=missing
```

Second Error
```
conanfile.txt: Writing generators to /Users/pivovaa/workspace/conan-examples/libraries/poco/md5
ERROR: Invalid generator 'cmake'. Available types: CMakeToolchain, CMakeDeps, MesonToolchain, MSBuildDeps, MSBuildToolchain, NMakeToolchain, NMakeDeps, VCVars, QbsProfile, VirtualRunEnv, VirtualBuildEnv, AutotoolsDeps, AutotoolsToolchain, PkgConfigDeps, BazelDeps, BazelToolchain, IntelCC, XcodeDeps, XcodeToolchain, PremakeDeps
```
```
$ cat conanfile.txt
[requires]
poco/1.9.4

[generators]
cmake
```

Third error
```
conan install poco/1.9.4@
ERROR: Conanfile not found at /Users/pivovaa/workspace/conan-examples/libraries/poco/md5/poco/1.9.4@
```

Very strange. How new people are going to try conan if even Getting Started is broken???

**Comment by RubenRBS** [comment]
Hi! Thanks a lot for your report.
The page you linked shows the following message at the top:
> This document is for a "1.X" Conan version. [Click here to see the Conan 2.0 documentation](https://docs.conan.io/2/)

Which is a warning for readers to know that such documentation is only intended for Conan 1. You thus bring a good point that it might not be visible enough not to get users confused, we might change it a bit so it pops out more

I recommend you check out https://docs.conan.io/2/tutorial.html the tutorial secion for the v2 docs, which neatly go step by step into how to use Conan

:)

**Comment by RubenRBS** [comment]
Great! Feel free to open more issues if you find any other problems following the tutorials!

**Comment by apivovarov** [comment]
I searched for conan examples and got to https://github.com/conan-io/examples which is conan1 examples. That is confusing.
better if this repo shows latest conan2 examples. Old conan1 examples can be moved to old/archive folder.
Also this repo has link to old documentation.
So, the default case scenario is still conan1. 
I guess its time to change default links and repos to conan2 resources

**Comment by memsharded** [comment]
The docs already default to Conan 2.0 docs, and all the links from those default docs go to the ``examples2`` repo, not to ``examples``. If you find some link that points to the old ``examples`` repo, please report and we will fix it.

We cannot move or close the ``examples`` old repo, because it is still used by some Conan 1.X users, and it will be breaking links and other stuff for users that haven't still upgraded to Conan 2.
