### ISSUE TITLE
About graph info on transitive dependencies

### ISSUE THREAD

**Issue by retanoj** [conan-io/docs#3294]
Hi there, I run `conan graph info pkg1 -f json > graph.json` to generate dependencies graph of pkg1.

I notice that `pkg1` dependencies include `pkg2` and `pkg3` on graph.json result. This does not match my expectation.

```json
{
  "graph": {
    "nodes": {
      "0": {
        "ref": "pkg1/1.0",
        "dependencies": {
          "1": {"ref": "pkg2/1.0", ...},
          "2": {"ref": "pkg3/1.0", ...},
        }
      }
    }
  }
}
```

As my experience with Maven / Composer / Npm, `pkg1` dependencies should only include `pkg2`，and `pkg2` dependencies include `pkg3`.

So is there any method to do this?

pkg1 & pkg2 & pkg3 codes show as below.
```python
# pkg1
from conan import ConanFile

class Pkg1(ConanFile):
    name = "pkg1"
    version = "1.0"

    settings = "os", "compiler", "arch", "build_type"

    requires = "pkg2/1.0"


# pkg2
from conan import ConanFile

class Pkg2(ConanFile):
    name = "pkg2"
    version = "1.0"

    settings = "os", "compiler", "arch", "build_type"

    requires = "pkg3/1.0"

# pkg3
from conan import ConanFile

class Pkg3(ConanFile):
    name = "pkg3"
    version = "1.0"

    settings = "os", "compiler", "arch", "build_type"


```

**Comment by memsharded** [comment]
Hi @retanoj 

In C++ the transitive dependencies are more important than in other package managers, and that is what the whole ``dependencies`` is serialized. If you want to know what are the direct dependencies, that information is exactly in the ``...`` that you are omitting in the ``direct=True|False`` trait. You can use that trait to differentiate the direct dependencies and the transitive ones.

**Comment by retanoj** [comment]
> ...

oh.. thx. I got the "direct" flag.
And could u explain why transitive deps are more important than others in C/C++?

**Comment by memsharded** [comment]
> And could u explain why transitive deps are more important than others in C/C++?

Because when you link an executable with a "direct" dependency that is a static library, you also have to directly link against all the other static transitive libraries that the direct one depends on, and they become part of the final executable binary code, being embedded. So a transitive library several levels of transitivity above, directly affects the final create binary of the consumer. This doesn't happen in other languages like python, java or node/js

**Comment by retanoj** [comment]
> you also have to directly link against all the other static transitive libraries that the direct one depends on

em.... 
If there is a dependency relation about A --(static link)--> B --(static link)--> C, which means C is (partly) embedded in B, and "embedded B" is (partly) embedded in A. C affects A by C is invoked in B and B is invoked in A. In C language, we just see ONE file A but not B or C. This is just about file structure but not dependency relation.

May be the whole `dependencies` is serialized in graph node is just conan choice, I respect and accept it :)

**Comment by memsharded** [comment]
> which means C is (partly) embedded in B, and "embedded B" is (partly) embedded in A

Not sure what you mean. Only the bits in the definitions of the headers files of C become part of B. But the whole libc.a (or .lib in windows), is not part of B, and in the same way the whole ``libb.a`` is not embedded in ``liba.a``.
When an executable links with ``liba.a``, it needs to be passed directly the ``libb.a`` and ``libc.a``, and it is the executable the one who directly embeds the 3 libraries in its binary code. If you change any .cpp file in libC or in libB, not a single bit changes in the downstream libA library, but it goes directly to the executable. So the executable definitely needs visibility over all the transitive static libraries. That also means that a change in libC .cpp files does not require to re-build either libB or libC, but it requires to relink the executable. Then, the ``libC`` has a direct influence in the ``package_id`` of the executable, and this is the thing that doesn't happen in those other languages.

Conan needs to compute that information, it is very necessary, and having the information and not serializing it, didn't make a lot of sense, as that information for example is something that anyone integrating with a proprietary build system would need.

I think the original question was addressed, could we close the issue? Thanks very much for the feedback!

**Comment by retanoj** [comment]
> I think the original question was addressed, could we close the issue? Thanks very much for the feedback!

yes..thx again.

**Comment by retanoj** [comment]
> Only the bits in the definitions of the headers files of C become part of B.

yes, I made a mistake here. Thx for your reminding.

> So the executable definitely needs visibility over all the transitive static libraries.

yes again. And for other language, like java, it also package every .jar library into one .jar file when generate a fat jar. It's similar to static link.

As my opinion, when meet transitive dependencies, I prefer to build a graph like this, and let user traverse the deps tree to get something they need.
```json
{
  "graph": {
    "nodes": {
      "0": {
        "ref": "pkg1/1.0",
        "dependencies": {
          "1": {"ref": "pkg2/1.0", "shared": false, ...},
        }
      },
      "1": {
        "ref": "pkg2/1.0",
        "dependencies": {
          "1": {"ref": "pkg3/1.0", "shared": false, ...}
        }
      },
      "2": {
        "ref": "pkg3/1.0",
        "dependencies": {
          
        }
      }
    }
  }
}
```

**Comment by memsharded** [comment]
> As my opinion, when meet transitive dependencies, I prefer to build a graph like this, and let user traverse the deps tree to get something they need.

That is the thing, it is not that simple to just traverse the dependency graph and compute the transitive requirements ``traits``. Conan does a bunch of inference based on the options, package-types, and types of requires, to compute the ``traits`` of transitive requirements. This would be almost impossible to reproduce by users while traversing the dependencies, so this is why it is serialized for users wanting to apply that knowledge to their own builds.
