### ISSUE TITLE
what is "work in progress" package  ID mode?

### ISSUE THREAD

**Issue by SSE4** [conan-io/docs#3325]
it's never documented what is the `work-in-progress` package ID mode. it's only briefly [mentioned](https://docs.conan.io/1/migrating_to_2.0/general.html#default-package-id-mode), but never actually explained in the documentation.
other modes explained are listed here: https://docs.conan.io/2/reference/conanfile/attributes.html#package-id-embed-non-embed-unknown-mode

**Comment by RubenRBS** [comment]
That work in progress refers to that subsection of the page, which is still a work in progress we need to yet need to fill, and does not refer to an id :)

**Comment by SSE4** [comment]
and why closed if it's still work in progress?
