### ISSUE TITLE
[bug] Documentation for credentials.json doesn't render bullet points correctly

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/docs#3358]
As added in https://github.com/conan-io/docs/pull/3350/files, bullet points are not rendered as bullet points or on new lines on the website. I believe a new line is missing between the end of the paragraph and beginning of the bullet points, i.e.

```diff
 Conan can authenticate against its Conan remote servers with the following:
-- Interactive command line, when some server launches an unauthorized error, the Conan client will ask for user/password interactively and retry.
+
+- Interactive command line, when some server launches an unauthorized error, the Conan client will ask for user/password interactively and retry.
```

How it's rendering:

![image](https://github.com/conan-io/docs/assets/36361864/eddf8bb4-9b80-4aed-b843-38f904b776af)

**Comment by RubenRBS** [comment]
Good catch, thanks a lot @samuel-emrys :)
