### ISSUE TITLE
How to set proxy in conan2?

### ISSUE THREAD

**Issue by QiuYilin** [conan-io/docs#3410]
### What is your question?

In conan1.0  proxies can be set in conan.conf
```
[proxies]
http = http://dev-proxy.oa.com:8080
https = http://dev-proxy.oa.com:8080
```
In conan2.0, It seems like there are related options too in global.conf

`core.net.http:proxies`

but how to set the value ?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hints for docs in https://github.com/conan-io/conan/issues/78#issuecomment-1746824394

**Comment by QiuYilin** [comment]
@memsharded  Thank you!
