### ISSUE TITLE
How disable CONAN_HOME cache memory location

### ISSUE THREAD

**Issue by sangramjadhavbhtc** [conan-io/docs#3417]
Hi,
it is possible to switch between defined folders for cache memory with the original cache memory of Conan (i.e. username\.conan)?
When CONAN_HOME env. variable is defined. because currently after defining CONAN_HOME everything is happening inside the defined folder.

**Comment by memsharded** [comment]
Hi @sangramjadhavbhtc 

You can have different CONAN_HOME variables, but define in each one a ``global.conf`` that contains the ``core.cache:storage_path`` definition to share the same package storage for both homes.

**Comment by sangramjadhavbhtc** [comment]
Hi, @memsharded,  

I have tried putting ```core.cache:storage_path```into the global.conf but it gives me an error. I have also added env. variable as **CONAN_HOME** and location of folder like "C:/Users/sangram.jadhav.BHTCGROUP/Desktop/**conanhometrail**" 

![image](https://github.com/conan-io/docs/assets/129362731/9bd693b6-5b59-4225-a2c7-ae4efcace346)


I also do not understand, how to use the default Conan cache after defining a customized Conan cache.
And in which global.conf file I should define ```core.cache:storage_path``` and how.

![image](https://github.com/conan-io/docs/assets/129362731/a4e75e90-3612-4be6-ac36-2dcf7a9102f6)

I am trying to add as shown in the above image. Please correct me if I am missing something.

**Comment by memsharded** [comment]
You have the examples in commented code, they are ``conf = value``, with an ``=`` sign, not ``:``.
In your case:
```
core.cache:storage_path=C:/Users....
```
Please do not use the same value as CONAN_HOME, that would be a disaster, the default is ``<CONAN_HOME>/p`` if inside of the Conan home.

**Comment by sangramjadhavbhtc** [comment]
Yes, understood! I have tried this and now, I am able to export and toggle the cache memory contains to the custom path.

**Comment by memsharded** [comment]
Great! Then I guess we can close this ticket now as resolved, thanks for the feedback.
