### ISSUE TITLE
"Using build tools as Conan packages" example is misleading

### ISSUE THREAD

**Issue by kuddai** [conan-io/docs#3420]
Good evening

In this tutorial
[Using build tools as Conan packages](https://docs.conan.io/2/tutorial/consuming_packages/use_tools_as_conan_packages.html#consuming-packages-tool-requires)

it looks like required build tools will be installed on its own and only conan is required.

However, you need to install your **own** system wide cmake before you can execute
```
conan install . --output-folder=build --build=missing
```

otherwise it can compile zlib in your tutorial, complaing about that **cmake** is missing.

It is especially confusing because it states that 
```
cmake/3.27.7: Appending PATH environment variable: /Users/user/.conan2/p/cmake253f38c8fbec3/p/CMake.app/Contents/bin
```

which looks like PATH env variable is update and will use cmake from conanfile.txt.

Couldn't figure out for some time, how it is supposed to work due to this line. Thought that PATH isn't updated for some reason.

In reality it leads to empty code which is just a stub for the future
https://github.com/conan-io/conan/blob/5955fdb87ee2f5e37aa3f8aea6e9c5ff62c494a7/conans/model/build_info.py#L46

And then you can build **your own** code with cmake from conanfile.txt.

But in order to do that you need to have system cmake in the first place.

If this is intended behaviour (albeit from user perspective it would be cool if conan just use cmake from conanfile.txt to build other dependencies) then please remove `Appending PATH environment variable` line. It is confusing as it makes user think that $PATH is updated with path to cmake, when in practice it doesn't

**Comment by memsharded** [comment]
I think with the clarification in https://github.com/conan-io/docs/issues/3420 maybe now it is better and we could close this issue, what do you think @kuddai ?

**Comment by kuddai** [comment]
Thank you!
