### ISSUE TITLE
[bug] Documentation: small imprecision in the second page of Conan 2 tutorial

### ISSUE THREAD

**Issue by Adnn** [conan-io/docs#3422]
### Steps to reproduce

On [the second page of the tutorial](https://docs.conan.io/2/tutorial/consuming_packages/use_tools_as_conan_packages.html).

> Conan used the system path’s CMake version to build this example.

Yet, reading the first page, it seems Conan did not have to call CMake as it found all dependencies as prebuilt.
The user explicitly called the CMake commands, and indeed tapped into the system path's CMake version.

Maybe a more precise phrasing could be used here?

**Comment by Adnn** [comment]
Another small mistake in the tutorial (not opening individual issues for those).

[On the 4th page](https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html):

> requirements() in this method we can use the self.requires() and self.tool_requires() methods to declare all our dependencies (libraries and build tools).

Yet, in the `conanfile.py` code above, the `tool_requires` is not in `requirements()` but in `build_requirements()`.

**Comment by czoido** [comment]
Hi @Adnn,
I made a PR to the docs with some changes: https://github.com/conan-io/docs/pull/3423 
Do you think it would be more clear with those changes? 
Thanks!

**Comment by Adnn** [comment]
Hi @czoido,

To me the changes look excellent, thank you for your help!

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/docs/pull/3423
