### ISSUE TITLE
conan cache path command

### ISSUE THREAD

**Issue by Vasile-Creuco** [conan-io/docs#3442]
How can I get content from conan package with conan cache path command in conan 2?
I can get source, build, ..., but I can't get the content from package.

**Comment by memsharded** [comment]
Hi @Vasile-Creuco 

Thanks for your question

You need to provide the ``package_id`` of the binary you want to check, like ``conan cache path pkg/version:package_id``, because there can be many different binaries in the cache for the same version. You can list them with ``conan list pkg/version:*``

**Comment by memsharded** [comment]
you can find examples and usage in https://docs.conan.io/2/reference/commands/cache.html

**Comment by Vasile-Creuco** [comment]
Yes. I know that, but I want to use the content from conan_package.tgz. I would like to know if there a posibility with conan cache path...

Thank you!

**Comment by memsharded** [comment]
Any feedback about the use case? Maybe we can suggest some other idea, or at least learn from the use case. Thanks!
