### ISSUE TITLE
Feasibility of shared read only cache + writable local cache.

### ISSUE THREAD

**Issue by dpatchi** [conan-io/docs#3478]
Hello All,

Based on my understanding - with Conan, every user can have their local cache in their local disk and use it.
Considering the fact that if we have huge number of users using the same cache - they need to have cache at their local disk level which costs lot of disk usage.

Can we have any possibility of like this?

Shared cache -> read only by all -> write(install by only one user which can be part of CI).
Local cache -> Conan to check if the desired version of exists in shared cache - if yes use, if not download it in local and use it.

Thank you

**Comment by memsharded** [comment]
Hi @dpatchi 

Thanks for your question

> Shared cache -> read only by all -> write(install by only one user which can be part of CI).
Local cache -> Conan to check if the desired version of exists in shared cache - if yes use, if not download it in local and use it.

At the moment this is not possible, and it is not planned. This is indeed a good idea, we have already considered it, but it is something very complex, and it would require a huge effort, both to develop and future maintenance and support. Caching is difficult, and shared cached that need to be synchronized (locked) are even more challenging. There are possibilities that shared caches over network shared connections can be slowly painful for developers too. At the moment the Conan cache is not even concurrent for a single user, so there is still a long journey to get there. The plan is first to implement cache concurrency, as part of our Conan 2.X roadmap (following months), but before considering a multi-level cache, there will be a ton of other pending priorities, so this idea sounds something more like Conan 3.0.

At the end of the day, disk is relatively cheap, compared with developers and CI compute time, and we keep releasing tools like the recent ``conan remove -lru`` to efficiently keep cache size under control. 

Thanks very much for your feedback, I'd suggest to close this ticket as not-planned at the moment, if the idea becomes part of the future roadmap at some point, we will re-open.

**Comment by dpatchi** [comment]
Thank you James for your valuable input.

**Comment by mgratzke** [comment]
Hi, as the "roadmap" beeing mentioned - is there a public roadmap for conan available? Could not find anything in the Docs...

**Comment by memsharded** [comment]
We use the ``milestones`` in Github: https://github.com/conan-io/conan/milestones

We generally plan the next release in advanced, done monthly, plus a 2.X general backlog of things that we plan.
