### ISSUE TITLE
Add a search functionality to the docs which delivers useful results. 

### ISSUE THREAD

**Issue by Danielku15** [conan-io/docs#3519]
Hey everyone. 

I have the feeling that the search on the Conan 2 docs is mostly useless. You cannot even find pages when you know the exact title. e.g. you search for "Creating Packages" (with or without quotes doesn't matter) and you hope to find https://docs.conan.io/2/tutorial/creating_packages.html

But this page is only the 16th page result. There are various keywords which are spread across many pages, so you end up with many useless results. When you Google for conan related topics, you currently often end up on the v1 docs with the warning banner to go to the v2 docs. But finding the equivalent page on v2 is hardly possible.

It is even better to use the GitHub code search: https://github.com/search?q=repo%3Aconan-io%2Fdocs%20Creating%20Packages&type=code 

Maybe there are some better search plugins to integrate in the docs framework you are using? https://www.algolia.com/ is a very popular service used in static website generators but its not free.

**Comment by memsharded** [comment]
Hi @Danielku15 

Thanks for your feedback.

We are using the default search functionality that comes with sphinx, and we agree it is not very good.
We tried and we actually implemented a "better" search in the past, but it was a bit too difficult to maintain and support, and we finally disabled it. 

It would be great to have another look at it, thanks for the suggestions. Adding @RubenRBS that is currently working on some docs large refactors and updates.

**Comment by RubenRBS** [comment]
Hi! We have done some work to improve usability in this aspect, and while the search behaviour is still not optimal, I think it's way better than what we used to have. Could you have another look @Danielku15, see if you feel the same? Thanks!

**Comment by RubenRBS** [comment]
Closing as solved - although the search is still not perfect, it's better than it has ever been. We'll take a look into further improving it later in the year :)
