### ISSUE TITLE
[question] Are there any examples of custom/user defined templates?

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/docs#3525]
### What is your question?

I have a couple of questions about custom templates:

1. Are there any examples of these and how to define them? I found https://docs.conan.io/2/reference/commands/new.html#custom-templates but it seems to be pretty light on on getting started
2. Can custom templates be distributed through a `conan config`-installable repository? i.e., can I add some structure to `extensions` to get my templates to be identified by the `conan new` command?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Documented in https://github.com/conan-io/docs/pull/3526, thanks!
