### ISSUE TITLE
Missing migration docs for "How to check the version of the Conan client inside a conanfile"

### ISSUE THREAD

**Issue by CJCombrink** [conan-io/docs#3539]
The [How to check the version of the Conan client inside a conanfile](https://docs.conan.io/en/1.17/howtos/check_conan_version_in_conanfile.html) page is very helpful, but when migrating to conan 2 there is a gap in the documentation. 

One issue is that the page has a banner stating "This document is for a "1.X" legacy Conan version. [Click here to read the Conan 2.0 documentation](https://docs.conan.io/2/)" when clicking there it does not go to any helpful page.

The https://docs.conan.io/1/migrating_to_2.0/recipes.html page should probably mention the migration. 

Old:
```
 from conans import ConanFile, CMake, __version__ as conan_version
 from conans.model.version import Version

 class MyLibraryConan(ConanFile):
     name = "mylibrary"
     version = "1.0"

     def build(self):
         if conan_version < Version("0.29"):
             cmake = CMake(self.settings)
         else:
             cmake = CMake(self)
     ...
```

New: 
```
from conan import ConanFile
from conan import conan_version

class pkg(ConanFile):
    ...
    def generate(self):
        if conan_version.major == "1":
            print("Running Conan 1.X")
```

**Comment by memsharded** [comment]
Thanks for the feedback @CJCombrink 

I think that it will be a bit more idiomatic to write something like:
```python
from conan import conan_version
....
     if conan_version < "2":  # this is more idiomatic
          # do something
```

Would you like to contribute this improvement yourself?

**Comment by CJCombrink** [comment]
@memsharded Nice, I was not aware.

_Personally_ I would keep with the `conan_version.major` part since I am not versed enough in python to know that the version struct would correctly compare to a literal as a whole (99% C++, 1% Python)...

> Would you like to contribute this improvement yourself?

I will see what I can do
