### ISSUE TITLE
building fmt/10.1.0 on windows failed about unicode

### ISSUE THREAD

**Issue by 11janson** [conan-io/docs#3593]
the log:
C:\Users\janson.yang.FJZ\.conan2\p\b\fmt067f9cbcef2b0\b\src\include\fmt\format.h(847,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式
以防止数据丢失 [C:\Users\janson.yang
.FJZ\.conan2\p\b\fmt067f9cbcef2b0\b\build\fmt.vcxproj]
  (编译源文件“../src/src/os.cc”)
C:\Users\janson.yang.FJZ\.conan2\p\b\fmt067f9cbcef2b0\b\src\include\fmt\format.h(1456,34): error C2001: constants contain line break[C:\Users\janson.yang.FJZ\.conan2\p\b\fmt067f9cbcef2b0\b\build\fm
t.vcxproj]

I think about,may be this should be save as unicode, but I do not know how to fix it:
the wrong place
![image](https://github.com/conan-io/docs/assets/105896625/e2d6d21c-d79d-4ad0-8980-880d24872adc)

the right code on the git
![image](https://github.com/conan-io/docs/assets/105896625/4ebb1d46-3d27-49ea-97ad-ff2d4a169697)

**Comment by memsharded** [comment]
Hi @11janson 

It seems those files are the source code of fmt itself, not really related to the Conan package. Maybe this is an issue that needs to be reported to the fmt project?

If not, please share a reproducible case that includes your ``conanfile``, and the exact commands that you are using? Also the Conan version, your OS, your compiler and compiler version, etc.

**Comment by 11janson** [comment]
> Hi @11janson
> 
> It seems those files are the source code of fmt itself, not really related to the Conan package. Maybe this is an issue that needs to be reported to the fmt project?
> 
> If not, please share a reproducible case that includes your `conanfile`, and the exact commands that you are using? Also the Conan version, your OS, your compiler and compiler version, etc.

Thanks for your reply. I have fixed it by modifing this file and successfully compiled fmt library.
![RGBjd4eMTQ](https://github.com/conan-io/docs/assets/105896625/c8e5e1e4-b46c-4ab9-8257-9edec59adacc)
