### ISSUE TITLE
[bug] Improper variable in tools.microsoft:winsdk_version description

### ISSUE THREAD

**Issue by Nekto89** [conan-io/docs#3605]
https://github.com/conan-io/docs/blob/c1ae80f38b81f4f71c8e6688db24bc3e9d5bc16b/reference/tools/cmake/cmaketoolchain.rst?plain=1#L590

It probably should be `CMAKE_GENERATOR_PLATFORM` instead of `CMAKE_GENERATOR_TOOLSET`

**Comment by memsharded** [comment]
Thanks for reporting!

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/docs/pull/3606
