### ISSUE TITLE
error: No module named 'test.examples_tools' when run run_example.py

### ISSUE THREAD

**Issue by renjiangithub** [conan-io/docs#3631]
1. I have installed python3 on my ubuntu20.04. (Python 3.8.10)
2. download the whole examples2 project to local: https://github.com/conan-io/examples2.git
3. cd ./examples2/tutorial/creating_packages/first_package
4. execute `python3 ./run_example.py`，oops:
```
➜  first_package python3 ./run_example.py 
Traceback (most recent call last):
  File "./run_example.py", line 4, in <module>
    from test.examples_tools import run, tmp_dir
ModuleNotFoundError: No module named 'test.examples_tools'

```

forgive me for this stupid question. thanks U

**Comment by czoido** [comment]
Hi @renjiangithub,

Thanks for the question. The run_example.py in the folder is not meant to be executed by users, but to be tested on ci. The examples are meant to be executed step by step by the provided instructions in the documentation. Please check https://docs.conan.io/2/tutorial/creating_packages/create_your_first_package.html in this case.

**Comment by renjiangithub** [comment]
thank you very very much.

**Comment by czoido** [comment]
> thank you very very much.

Thanks you for reporting. I think we will add some warnings or comments because that's a bit confusing.

**Comment by czoido** [comment]
Closing this and will open an issue in the examples2 repo.
