### ISSUE TITLE
[bug][docs] `generic_system` documentation is wrong/`compilers` block is not documented

### ISSUE THREAD

**Issue by sykhro** [conan-io/docs#3651]
From https://docs.conan.io/2.2/reference/tools/cmake/cmaketoolchain.html

> generic_system: Defines CMAKE_SYSTEM_NAME, CMAKE_SYSTEM_VERSION, CMAKE_SYSTEM_PROCESSOR, CMAKE_GENERATOR_PLATFORM, CMAKE_GENERATOR_TOOLSET, CMAKE_C_COMPILER, CMAKE_CXX_COMPILER

This is not correct and will cause CMAKE_XXX_COMPILER to be defined regardless when doing:
```python
def generate(self):
    tc = CMakeToolchain(self)
    # Prevent Conan from overwriting the compiler settings
    tc.blocks.remove("generic_system")
```

to achieve what the docs say, you need to:
```python
def generate(self):
    tc = CMakeToolchain(self)
    # Prevent Conan from overwriting the compiler settings
    tc.blocks.remove("generic_system", "compilers")
```

**Comment by memsharded** [comment]
Thanks for raising the issue @sykhro 

I have transferred it to the "docs" repo to fix it. Indeed it seems the docs is incorrect and missing the "compilers" block removal.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/docs/pull/3653
