### ISSUE TITLE
Easter egg in the doc?

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/docs#368]
Hi! Just upgraded Conan to version 0.28, amazing stuff!

There's something weird on [this page](http://conanio.readthedocs.io/en/latest/reference/commands/creator/export-pkg.html), I guess someone forgot to remove that `OTRA VEZ!` line ;)

**Comment by memsharded** [comment]
Definitely a mistake, thanks for telling. Going to fix it now :)

But ey, this is a good idea, we should hide some easter egg somewhere, in the docs or in conan :D

**Comment by memsharded** [comment]
Gone! http://conanio.readthedocs.io/en/latest/reference/commands/creator/export-pkg.html

Thanks!!
