### ISSUE TITLE
conan test is not accessible in the documentation

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/docs#369]
This command is mentioned in [this page](http://conanio.readthedocs.io/en/latest/reference/commands/creator/create.html?highlight=conan%20test), however there is no link.

It doesn't appear in the reference either.

**Comment by memsharded** [comment]
True. I am on it, thanks!!

**Comment by memsharded** [comment]
Added the reference: http://docs.conan.io/en/latest/reference/commands/creator/test.html

Now, it has be introduced also along the docs, but at least this solves the minimum. Thanks!

**Comment by theodelrieu** [comment]
Awesome, congrats on the reactivity :)
