### ISSUE TITLE
Bad custom command example in docs

### ISSUE THREAD

**Issue by rconde01** [conan-io/docs#3725]
Using conan 2.3

https://docs.conan.io/2/reference/extensions/custom_commands.html#reference-commands-custom-commands
Shows:

```
from conan.api.conan_api import ConanAPI
```
Which leads to:
```
ERROR: Error loading custom command 'cmd_batch_export.py': cannot import name 'ConanApi' from 'conan.api.conan_api' (D:\myenv\venv\Lib\site-packages\conan\api\conan_api.py)
ERROR: Error loading custom command 'cmd_batch_export.py': cannot import name 'ConanApi' from 'conan.api.conan_api' (D:\myenv\venv\Lib\site-packages\conan\api\conan_api.py)
```

meanwhile the example at https://github.com/conan-io/conan-extensions/blob/main/extensions/commands/cci/cmd_export_all_versions.py

uses the `conan_api` argument as untyped.

**Comment by memsharded** [comment]
Hi @rconde01 

Thanks for your report.

I am not sure what would be failing. I have just tried to install the custom commands from the ``conan-extensions`` repo, and they have the ``from conan.api.conan_api import ConanAPI`` and it works fine. I have been looking for a ``ConanApi`` with that different casing (the one your error message seems to be complaining about), but I can't find any reference.

Maybe you have an old copy of the ``examples2`` repo? Could you please try to update your custom commands or grep for ``ConanApi`` with that specific casing?

**Comment by rconde01** [comment]
I think i just made a mistake when copying - sorry about that.

**Comment by memsharded** [comment]
No prob, thanks for the feedback!
