### ISSUE TITLE
missing `+` in the code example in docu custom-generators-as-python-requires

### ISSUE THREAD

**Issue by ifxfrancois** [conan-io/docs#3780]
Hi,
I think the code example at [Custom generators as python_requires](https://docs.conan.io/2.0/reference/extensions/custom_generators.html#custom-generators-as-python-requires) is missing a `+`

```python
for dep, _ in self._conanfile.dependencies.items():
            deps_info = f"{dep.ref.name}, {dep.ref.version}"
```
should be 
```python
for dep, _ in self._conanfile.dependencies.items():
            deps_info += f"{dep.ref.name}, {dep.ref.version}"
```

**Comment by memsharded** [comment]
Thanks for reporting this @ifxfrancois 

I am doing PR https://github.com/conan-io/docs/pull/3781 to improve it
