### ISSUE TITLE
Document: Changed search for profiles. Profiles not found in the default profiles folder, will be searched for locally. Use ./myprofile to force local search only.

### ISSUE THREAD

**Issue by lasote** [conan-io/docs#380]

**Comment by danimtb** [comment]
Docimented in getting started here: http://docs.conan.io/en/latest/using_packages/using_profiles.html?highlight=You%20can%20store%20them%20in%20the%20default%20profile%20folder%20or%20anywhere%20in%20you%20project

Also in reference: http://docs.conan.io/en/latest/reference/profiles.html?highlight=different%20folders
