### ISSUE TITLE
[bug] Setting environment-variables via `[buildenv]` or `[runenv]` from profiles stores leading/trailing spaces in value

### ISSUE THREAD

**Issue by DenizThatMenace** [conan-io/docs#3812]
## Environment details

**OS:**
* Linux (Ubuntu 22.04 via WSL)

**compiler:**
*  Clang 18 (but irrelevant)

**Conan version:**
*  2.6

**Conan profile:**
```
[settings]
arch = x86_64
os = Linux
build_type = Debug
compiler = clang
compiler.version = 18
compiler.libcxx = libstdc++11
compiler.cppstd = 20
compiler.cstd = 17

[conf]
tools.build:compiler_executables = { 'c': 'clang-18', 'cpp': 'clang++-18', 'rc': 'llvm-rc-18' }
tools.cmake.cmaketoolchain:find_package_prefer_config = True
tools.cmake.cmaketoolchain:generator = Ninja Multi-Config

[buildenv]
AR = llvm-ar-18
LD= ld.lld-18
anyPathVar = (path)/usr/bin

[runenv]
someTool = MyTool
somePath = (path)C:\Windows
```

## Description

Other than expected, the parsed environment-variables from the `[buildenv]`  and `[runenv]` section of the profile are stored with a leading whitespace. This is obvious when looking at the output of the conan-run:

```
...

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=clang
compiler.cppstd=20
compiler.cstd=17
compiler.libcxx=libstdc++11
compiler.version=18
os=Linux
[conf]
tools.build:compiler_executables={'c': 'clang-18', 'cpp': 'clang++-18', 'rc': 'llvm-rc-18'}
tools.cmake.cmaketoolchain:find_package_prefer_config=True
tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
[buildenv]
AR= llvm-ar-18
LD= ld.lld-18
anyPathVar=(path)/usr/bin
[runenv]
someTool= MyTool
somePath=(path)C:\Windows

Profile build:
[settings]
arch=x86_64
build_type=Debug
compiler=clang
compiler.cppstd=20
compiler.cstd=17
compiler.libcxx=libstdc++11
compiler.version=18
os=Linux
[conf]
tools.build:compiler_executables={'c': 'clang-18', 'cpp': 'clang++-18', 'rc': 'llvm-rc-18'}
tools.cmake.cmaketoolchain:find_package_prefer_config=True
tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
[buildenv]
AR= llvm-ar-18
LD= ld.lld-18
anyPathVar=(path)/usr/bin
[runenv]
someTool= MyTool
somePath=(path)C:\Windows
...
```
Interestingly, only for non-path variables the whitespaces are not split.

I understand, why it might be beneficial to also be able to store leading (and trailing) whitespaces in environment variables. But shouldn't there be some other syntax to do so? E.g. consider:
* Surrounding the entire value by double-quotes (as it is done in Bash) or similar?
* Or require the author of that profile to provide a `(verbatim)` prefix to the value (similar to the `(path)` prefix), so that everything following it will be stored as value.

---

Anyway, this disparity from how variables and values of other sections are parsed makes it surprising and error-prone.
At least, this should be documented somewhere.

### How to reproduce it

Simply just try to build any conan package like so:

```
conan create <dir-with-conanfile.py> -pr:a <conan-profile-from-above>
```

**Comment by memsharded** [comment]
> I would recommend to document that behavior in Conan's user documentation.
It should probably be explicitly mentioned as a highlighted "note" in the documentation of [buildenv] and [runenv] [here](https://docs.conan.io/2/reference/config_files/profiles.html).

Agree, moved this to docs repo, proposed https://github.com/conan-io/docs/pull/3813
