### ISSUE TITLE
Possible documentation issue in generate regarding dynamic linked libraries

### ISSUE THREAD

**Issue by Einsied** [conan-io/docs#3826]
Good day people,

I attempted to include Qt6 in one of my recent projects and failed to correctly copy the ".dll"-files.

I used the the documentation in:
https://github.com/conan-io/docs/blob/dd487c60318b6a7d6557829081819d027ecea903/reference/conanfile/methods/generate.rst?plain=1#L103
Which suggested, that the files should be sourced from the "lib" directory by using `dep.cpp_info.libdir`.

It took me a while to figure out that `dep.cpp_info.bindir` exists.
(Thanks to https://github.com/conan-io/conan/issues/13660 and the reporter there)

In my experience the shared libaries usually end up in the bianry-directory,
so the line in the documentation looks unusally to me.
It would be helpful to change it or ammend a comment elaborating that  `dep.cpp_info.bindir` exists to save less experienced users like me some time.

Cheers and please fix
Einsied

**Comment by memsharded** [comment]
Hi @Einsied 

Thanks for your feedback.

This looks indeed a mistake in the docs, the dlls in Windows are in the "bindir".
Let me submit a fix for this.

**Comment by memsharded** [comment]
Doing https://github.com/conan-io/docs/pull/3828, it will close this ticket, will be in next 2.8 docs, thanks again!
