### ISSUE TITLE
[bug] TriCore architecture inconsistencies in documentation

### ISSUE THREAD

**Issue by aander80** [conan-io/docs#3831]
### Describe the bug

Hello!

I guess that *bug* is perhaps the wrong label for this issue, but it was the best suited label in my opinion!

In the documentation for TriCore (https://docs.conan.io/2/examples/cross_build/tricore.html), TriCore is denoted as a compiler. This is not strictly true, TriCore is instead the architecture: https://en.wikipedia.org/wiki/Infineon_TriCore, https://www.infineon.com/cms/en/product/microcontroller/32-bit-tricore-microcontroller/?gad_source=1&gclid=EAIaIQobChMIs-bByJe1iAMVWGWRBR3vnj0hEAAYASAAEgL_qfD_BwE&gclsrc=aw.ds.

There are multiple compilers for TriCore, some of which can be found here: https://www.infineon.com/cms/en/tools/aurix-tools/Compilers/. I guess that the one listed in the Conan documentation refers to this one: https://github.com/mc-cat-tty/tricore-gcc/tree/aeeeafeaa20072d7f1811890b113fe4e9c3f5407?

I don't know much about the nomenclature of these microcontrollers and architectures, but I suggest that you change the documentation to state that TriCore is the architecture and not the compiler. At a quick glance the profile suggestion looks correct, though, with `gcc` being stated as the compiler.

**Comment by memsharded** [comment]
Moved to the docs repo

**Comment by aander80** [comment]
Perhaps this is a language barrier from my end, but I would argue that "We are using a/the tricore compiler" is correct in some contexts (especially "a"). However, if you substitute tricore for x86_64, sentences such as "Tricore compiler is a popular compiler" being convert to "x86_64 compiler is a popular compiler" does not make much sense, in my opinion.

I have not found any errors in the code in conan, I believe the profile configuration looks correct with compiler being set to gcc and architecture being set to tc*, I mostly wanted to highlight that there are multiple compilers for the architecture and it would make more sense to me to see "compiler: gcc", "compiler: hightec" etc. rather than "compiler: tricore" since the latter would be ambigous. If others believe the current wording is correct I am happy to close this issue without any changes, my main point was to highlight the differences between architecture and compilers in this instance. :)

**Comment by memsharded** [comment]
No, I think you are right, it cost little to be more accurate in the wording, I think it is just a matter of changing a couple of sentences, like "Building packages for Tricore" or "Compilers for the Tricore platform and architectures are ..."

Would you like to suggest the edits in a PR yourself? The docs are also open source. Don't worry if not, we can try to address it too.

**Comment by aander80** [comment]
Sure, I will try to find the time to make a PR tomorrow!
