### ISSUE TITLE
How to disable the Cookie Banner in the local built documentation?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/docs#3844]
### Problem Description

Hello, Conan Maintainance Team.

I've noticed that the Cookie Banner appears at the bottom of the page after it's built successfully locally. I would like to disable this banner in the local environment, as it is not necessary and annoying. What parameter should I pass when building the documentation? What snippet should I modify before building the documentation?

**NOTE:** The reason why I ask is because I found that nearly all other sphinx-based documentation won't show this Cookie Banner when it's built locally. Then, why does it show up when building Conan documentation?

![Screenshot_20240917_122441](https://github.com/user-attachments/assets/5e910110-1192-4af2-93db-5d8bc8d96d1f)

**Comment by memsharded** [comment]
Closed by #3856

**Comment by hwhsu1231** [comment]
Hello, @memsharded.

First of all, it works after the PR(#3856) is merged. As long as I set `ENABLE_COOKIES_BANNER` env to `False` before building, the generated conan documentation won't show the cookies banner.

Therefore, I wonder whether this modification will be applied to all the previous release/develop versions?

- `release/1.3~release/1.X` branches
- `develop` branch
- `release/2.0~release/2.X` branches
- `develop2` branch

**Comment by memsharded** [comment]
No, it is not intended to backport this to other older branches, except ``develop2`` that already got it after ``release/2.7`` was merged into ``develop2``.
