### ISSUE TITLE
[Question] need correct the lib name  when "Packaging already Pre-built Binaries"

### ISSUE THREAD

**Issue by daiybh** [conan-io/docs#3871]
I am try "[Packaging already Pre-built Binaries](https://docs.conan.io/2/tutorial/creating_packages/other_types_of_packages/package_prebuilt_binaries.html#packaging-already-pre-built-binaries)".

THOSE steps is under WINDOWS.

I have a  third party lib named  "myhello.lib ", and "myhello.h"
But I want packaging them into a  Recipe named "slc-myhello"

so follow the topic , copy myhello.lib to vendor_hello_library/windows/x86_64/myhello.lib

I found if I don't change myhello.lib to slc-myhello.lib
my TestApp will don't work.

but if change the myhello.lib to slc-myhello.lib, the TestApp will work .

so the problem is  MUST change the lib name to match the Recipe name???

**Comment by memsharded** [comment]
Hi @daiybh 

Thanks for your question.

It is not necessary that the library is named like the package.

If you check the ``package_info()`` method in your ``conanfile.py`` (like in https://github.com/conan-io/examples2/blob/main/tutorial/creating_packages/other_packages/prebuilt_binaries/conanfile.py), then you can define there the name of the library in ``self.cpp_info.libs = ["mylibraryname"]``

If that doesn't work, it might be something else, then please share your full ``conanfile.py``, the exact command you are using and the output of that command. Thanks for your feedback.

**Comment by daiybh** [comment]
@memsharded Thanks your help , it works  on my side .
