### ISSUE TITLE
[question] docs of tool_require custom generators is different from implementation

### ISSUE THREAD

**Issue by X1aomu** [conan-io/docs#3902]
### What is your question?

I'm trying to migrate my custom generators to the tool_require style, which is an awesome feaature I think💗️ :)

But I noticed that the example given in docs dosen't work at all.

The docs says:

```python
    def package_info(self):
        self.generators_info.append(MyGenerator)
```

But:
1. `generators_info` is actually `generator_info`
2. `append(MyGenerator)` will cause exception as `generator_info` is initialize to be `None,` not an array

What's more, the [release note](https://github.com/conan-io/conan/releases/tag/2.9.0) says:
> Feature: Add `self.generators_info` for `tool_requires` to propagate generators to their direct dependencies. 

The question is, which side should have a fix, the docs or the code?

These are related PRs:
- https://github.com/conan-io/docs/pull/3880
- https://github.com/conan-io/conan/pull/17129

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
This has been closed by https://github.com/conan-io/docs/pull/3903, thanks again for your feedback!

**Comment by X1aomu** [comment]
Thank you all for quick fix :)

There's one more problem. In`generate()` function, simply calling `generator_info.append(MyGenerator)` will failed. I don't know whether it is expected to work or not. If not, we should replace it with `self.generator_info = [MyGenerator]`.
