### ISSUE TITLE
Documentation of `conan list` command is not correct

### ISSUE THREAD

**Issue by jasal82** [conan-io/docs#3936]
The docs of the `list` command (https://docs.conan.io/2/reference/commands/list.html#listing-recipe-revisions) state that it should be possible to obtain the latest recipe revision by running `conan list pkg/version`. This does not work. I have to append `#latest` explicitly to get the revision.

**Comment by memsharded** [comment]
Thanks very much for reporting this @jasal82 . Indeed a bug in the docs, most likely some legacy.

I am fixing it in https://github.com/conan-io/docs/pull/3946
