### ISSUE TITLE
Docs are not secure

### ISSUE THREAD

**Issue by memsharded** [conan-io/docs#398]
Mainly a readthedocs issue, but I think this should be improved.

**Comment by lasote** [comment]
Only possible when moved from read the docs to own machine, not a possibility to do it with a GH page either.
But, why you consider it a problem? Why is needed to encrypt the communication if you are reading docs and not even input anything?

**Comment by memsharded** [comment]
Yes, we have the mailing list subscription form. So browsers emit a warning saying that the page is not that safe, and not to enter sensitive information

**Comment by danimtb** [comment]
I think this may be blocked by rtfd/readthedocs.org#2652

**Comment by danimtb** [comment]
I'd say except for the warning about "this website is not secure" this issue was more related to the fact of subscribing to the mailing list which no longer exists...  so maybe this could be closed or marked as BLOCKED
