### ISSUE TITLE
Getting CLion to find conaninfo.txt when executing internal cmake

### ISSUE THREAD

**Issue by jmmut** [conan-io/docs#40]
Hello! I had a small problem using conan and clion, and as I didn't find any mention to this problem in the docs, I thought it might be useful including in the docs this approach.

The CMakeLists.txt explained in the docs as-is, makes CLion to try reading the conaninfo.txt in the CLion's internal build folders, and it won't be there (Error quoted below).

I fixed this in my project adding this line to my CMakeLists.txt, which I suggest adding to the Integrations/CLion section:

```
file(COPY build/conaninfo.txt DESTINATION "${CMAKE_BINARY_DIR}")
```

Given that I'm building in a `build` directory like this:

```
mkdir build && cd build/
conan install ..
cmake -G Ninja ..
cmake --build .
```

Without the `COPY` line, Clion fails to recognize the included folders, fails to compile, fails to highlight properly, etc. The error given is:

> ```
> Error:Error:file failed to open for reading (No such file or directory):
>   /home/jmmut/.CLion12/system/cmake/generated/f6d8bf47/f6d8bf47/__default__/conaninfo.txt
> Error:Error:Configuration Debug
> file failed to open for reading (No such file or directory):
>   /home/jmmut/.CLion12/system/cmake/generated/f6d8bf47/f6d8bf47/Debug/conaninfo.txt
> Error:Error:Configuration Release
> file failed to open for reading (No such file or directory):
>   /home/jmmut/.CLion12/system/cmake/generated/f6d8bf47/f6d8bf47/Release/conaninfo.txt
> Error:Error:Configuration RelWithDebInfo
> file failed to open for reading (No such file or directory):
>   /home/jmmut/.CLion12/system/cmake/generated/f6d8bf47/f6d8bf47/RelWithDebInfo/conaninfo.txt
> Error:Error:Configuration MinSizeRel
> file failed to open for reading (No such file or directory):
>   /home/jmmut/.CLion12/system/cmake/generated/f6d8bf47/f6d8bf47/MinSizeRel/conaninfo.txt
> ```

**Comment by memsharded** [comment]
Yes, you are totally right, CLion is using its own binary dir, which is not the same in which the ``conan install`` is executed. But how can it load the ``conanbuildinfo.cmake`` file, which is in the same folder? Cause in the docs we are using

```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
```

Maybe if you are changing that line, it could make sense to change generated conanbuildinfo.cmake to read in the current directory (now it is reading in the binary directory too).

Also, please check which conan version you are using, cause we have released some minors, that now have checks, to produce a warning instead of an error in case the conaninfo is not found. 
Please tell me, cause it seems we could create an issue in the code repo to provide this behavior. Thanks!

**Comment by jmmut** [comment]
mmh, I've been playing around trying quite a lot of other things, and I'm a bit ashamed that now I cannot reproduce the problem :/ maybe because I indeed upgraded to 0.7.4 this week, and I don't know which version I was previously (nor how to find it out). Now it seems to work fine without the `file(COPY...` line.

I was using `include(build/conanbuildinfo.cmake)` taking example from [getting started](http://docs.conan.io/en/latest/getting_started.html), didn't see that `include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)` from the end of [workflows](http://docs.conan.io/en/latest/manage_deps/workflows.html).

Also, I don't know how to see if CLion is now raising the warning of conaninfo.txt not found. I only can see the --build step, not the -G one.

I am willing to try more things if it is helpful, and I understand I didn't write a good reproducible issue, I will try better in the future.

**Comment by memsharded** [comment]
Yes, it is not raising the error anymore, but in fact it is not finding the conaninfo.txt. The PR https://github.com/conan-io/conan/pull/156 should fix it.

Your issue was perfectly legit, it is indeed a bug, it was more critical in 0.7.3, now it is "soft" in 0.7.4, but  still need to be fixed. Thanks very much for reporting, and keep doing so, your issue was perfect, keep the good work, thanks a lot :)

**Comment by jmmut** [comment]
OK, in fact, using `include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)`, CLion doesn't find conanbuildinfo.cmake, just as you said in the beginning.

**Comment by memsharded** [comment]
I have proposed another possible fix to this issue in #158. I am wondering, in which folder do you run ``conan install``? That would be the folder in which conanbuildinfo.cmake and conaninfo.txt are generated. If in the root folder, besides CMakeLists.txt and conanfile, the CMakeLists.txt, would just include:

```cmake
include(conanbuildinfo.cmake)
````

This is OK if you want to maintain a single build configuration at a time, and if you want to change configuration, just run ``conan install`` again with the new parameters. If you are sharing the project with a team, and not everybody uses CLion and your same layout, and for example, they want temporary files (both conan and build, for example), then I guess your cmake could do something like:

```cmake
if(EXISTS conanbuildinfo.cmake) #Clion, with conanbuildinfo.cmake in root
   include(conanbuildinfo.cmake)
else()
   include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake) # Not CLion
endif()
````

This should be merged soon and included in next release. Meanwhile, I guess you can use the COPY workaround. Or ask for help if you want to run conan from source from the latest develop branch :)

Cheers!

**Comment by jmmut** [comment]
Yes, it looks like a good approach. For the moment I'm just learning to use conan, and trying several layouts, to see which is the easiest one that works in 3 ways: in the terminal, in CLion and packaging (as I'm just toying, I'm using the same repo for the source and the package). I will take this into account, thanks!

Also, a bit offtopic, are you guys happy with questions in stackoverflow? For things that are not bugs or improvement suggestions, just doubts like [this](http://stackoverflow.com/questions/35381531/can-i-hide-my-link-flags-from-users-of-my-conan-package)? Or do you prefer another way?

**Comment by memsharded** [comment]
Ok, excellent, just let us know if you think that something could be improved in the workflows.

Abouth the stackoverflow, yes, why not, I think most programmers love SO, I do, and it is a great place to share knowledge and engage community, so go ahead :). It could be great if someone with enough reputation could create the "conan" tag so we could subscribe to new questions, I guess that will be a matter of time.

**Comment by nathanaeljones** [comment]
Is there a suggested folder layout for using Conan and CMake together?

**Comment by nathanaeljones** [comment]
@memsharded, @lasote  Do you have an example of a CMakeLists.txt that works with CLion and Conan 0.7.4? I'm not having much success with the lines above, but I may be putting them in the wrong order.

**Comment by lasote** [comment]
Not currently, I'm going to try to setup your project.

**Comment by jmmut** [comment]
Disclaimer: this is a bad layout, but it works if you are learning. Don't take it as example of how to do things. 

I'm using the simplest configuration that works for:
- compile using conan/cmake in the terminal.
- compile using clion (allowing semantic highlight and debug sessions).
- export, upload, download and compile the package.

which is:
- no separate folder for the build (yes, I know, quite dirty, but easy, and works for the moment)
- CMakeLists.txt on root folder, just as conanfile
- no separate repository for the package files

CMakeLists.txt:
```
project(myproject)
cmake_minimum_required(VERSION 2.8)

include(conanbuildinfo.cmake)
conan_basic_setup()

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
set(SOURCE_FILES ... )
add_library(myproject ${SOURCE_FILES})
target_link_libraries(myproject ${CONAN_LIBS})
```

For uploading a package that compiles, you can not do just a git clone in the `source()` method:
conanfile.py
```
...
    def build(self):
        cmake = CMake(self.settings)
        self.run('cmake "%s" %s' % (self.conanfile_directory, cmake.command_line))
        self.run('cmake --build . %s' % cmake.build_config)
...
    def source(self):
        self.run("git init && git remote add origin https://... && git fetch origin -t && git checkout -f yourversiontag")
```
**Warning** that `git checkout -f yourversiontag` is a bit dangerous, as it is overwriting the conanfile.py that conan will put for compiling the package after exporting it. It follows the assumption that any conan file (conanfile.py, conanmanifest.txt or conanfile.pyc I think) included in your repo is correct, and hopefully identical to the one it is overwriting. 

Now we run the whole process. The point is that all next should work, on top of compiling within clion. from root folder:
$ conan install
$ # now the conanbuildinfo exists, and clion will be able to copy it automatically and build properly
$ conan build
$ conan export youruser
$ conan search # (to copy the package id)
$ conan install myproject/version@user/channel --build myproject

and then you can upload it and try to use it in another project. 

Again, this layout is **dangerous** it takes a lot of assumptions, and it should not be used in serious environments.

**Comment by jmmut** [comment]
I really look forward to find a better layout that works without a separate repository for just the package, but it is likely to be the way to go.

**Comment by lasote** [comment]
@nathanaeljones in your project layout this lines works perfectly. 

`if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/build/conanbuildinfo.cmake) #Clion, with conanbuildinfo.cmake in root
    include(${CMAKE_CURRENT_SOURCE_DIR}/build/conanbuildinfo.cmake)
else()
    include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake) # Not CLion
endif()`

I made you a [Pull Request](https://github.com/imazen/imageflow/pull/30)
Just remember to enter in build directory and install the conan requirements:

`conan install --file ../conanfile_testing.txt `

@jmmut your case is different because you are creating a package, not just consuming it, but I will take a look ok?

Thanks guys!

**Comment by lasote** [comment]
I have update the conan docs: http://docs.conan.io/en/latest/integrations/clion.html
