### ISSUE TITLE
Document PR #2179 

### ISSUE THREAD

**Issue by lasote** [conan-io/docs#436]
- AutotoolsBuildEnvironment now takes a win_bash=False
- Page for cross building, examples of `build_os` and `build_arch`.
- tools.remove_from_path(command)  `env.py`
- tools.unix_path, now the default flavor is based on a detection
- tools.which, now auto-searches the extensions
- tools.run_in_windows_bash, new parameters
- tools.vcvars_dict
- tools.vcvars (context manager)
- conanfile.run (New parameters for windows subsystems)
- OSInfo():
    - bash_path()
    - uname(options=None)
    - detect_windows_sybsystem()

**Comment by danimtb** [comment]
Windows subsystems parameters in `conanfile.run()` documented here: https://docs.conan.io/en/latest/reference/conanfile/other.html#running-commands

**Comment by danimtb** [comment]
Finally all tasks completed! closing this
