### ISSUE TITLE
Rest API public endpoints

### ISSUE THREAD

**Issue by Prinkesh** [conan-io/docs#44]
conan uses rest api to interact with conan_server . It would be nice if these endpoints are documented somewhere , then one could make a ui on top of conan using this api ... which would make monitoring of uploaded packages easier .

https://github.com/conan-io/conan/issues/251

**Comment by Mikayex** [comment]
I'll try to make a pull request on this...

**Comment by szmyd** [comment]
This issue is getting a bit long in the tooth for a documentation issue...

**Comment by memsharded** [comment]
Actually I think it might be better not to document this at the moment. Conan 1.0 was launched just a few weeks ago, with a committement to stability, and not breaking the public/documented API, basically the conanfiles/recipes, the packages and the command line. 

This is the same reason the internal python API hasn't been documented yet. I think it is better to not document them at the moment and keep them as internal implementation detail, so they can still be evolved and matured without breaking. What do you think @lasote, can we close this issue? That doesn't mean it won't be documented in the future, of course.

**Comment by danimtb** [comment]
Maybe @lasote could help on updating the status of this issue

**Comment by lasote** [comment]
We can keep it open but it's true that it is not stable. In the 1.1 we introduced changes.

**Comment by danimtb** [comment]
Having now Artifactory CE the use case of this issue is covered and Artifactory has well documented features that empowers the server side management.

Also the API endpoints can be easily found in the Conan code base and the conan_server can be taken as reference.

I am tagging this as obsolete for a future close of the issue.

**Comment by marco-m** [comment]
@danimtb for my understanding: I assume that Artifactory CE has its own HTTP API, which is different from the conan server HTTP API, correct? I mean: if I want to query the Conan server HTTP (and not Artifactory), then my only source of documentation is still the conan source code, correct? Would also be useful to add the Artifactory HTTP documentation URL to this ticket, to help people coming here from a Google search?

**Comment by marco-m** [comment]
I found an approach that is good enough for me. If you want to answer the question: "How is a conan client command translated into the conan HTTP API", it is enough to run your command with a high enough debug level.

For example (output edited to show only HTTP information):

```
env CONAN_LOGGING_LEVEL=10 conan search --raw --remote conan-center "Expat"
...
rest_client_common.py[110]: REST: ping: https://conan.bintray.com/v1/ping
rest_client_common.py[136]: REST: get: https://conan.bintray.com/v1/conans/search?q=Expat
...
```

then use for example curl to validate:

```
curl 'https://conan.bintray.com/v1/conans/search?q=Expat'
{"results":["Expat/2.2.1@pix4d/stable","Expat/2.2.1@pix4d/testing", ...]}
```

Each time I touch Conan code, in very short time I get what I want. Again, kudos to the whole Conan team! ❤️

**Comment by danimtb** [comment]
Hi @marco-m,

Thanks a lot to post here your findings.
Here you also have the Artifactory REST API link: https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API

I think it is safe to close this issue for now 😃

**Comment by steve-thousand** [comment]
thanks @marco-m for mentioning the log level, that's been very useful in identifying the API, but something I still am not clear on is: is this discouraged? Should I refrain from calling those REST endpoints directly?
