### ISSUE TITLE
DLL paths and binaries on Windows for examples/zmq_protobuf.rst

### ISSUE THREAD

**Issue by e12e** [conan-io/docs#45]
Hi,

after working through the excellent introduction at: https://github.com/conan-io/docs/blob/master/examples/zmq_protobuf.rst I ran into a couple of problems with the steps as outlined in the text:

1) The protoc.exe-file ends up in the top folder, while the libprotoc.dll-file ends up with the other dll files in the "bin" folder. The easiest fix is to move the protoc.exe-file to the bin-folder, and call it from the work-dir like so (avoiding issues with the path for protobuf if calling protoc.exe from within the bin-folder): `.\bin\protoc.exe message.proto --cpp_out="."`

2) The dll-files are not copied into the build\bin-folder and so the server.exe and client.exe files won't run -- again the easiest fix, is to manually copy the server.exe and client.exe to the project .\bin folder (they are created in .\build\bin).

I feel that both of these issues should probably be taken care of automatically, but I'm not sure what would be the best way -- it certainly seems like the build process should copy the needed dlls to the bin-folder (as "." is sadly and insecurely always in the dll search path on windows).

Not submitting a PR, as I'm not sure if this is easily fixed by tweaking the build-scripts or if it is more of a documentation problem on Windows (ie: the change should be to the tutorial text)?

**Comment by memsharded** [comment]
Hi @e12e ,

Thanks for reporting. As you said, It might be a docs issue, or maybe something that can be improved with the package (package issues can be reported to the package repository itself, in this case https://github.com/memsharded/conan-zmq). I will have a look when possible, and check if docs or package issue, and tell you something. Cheers!

**Comment by lasote** [comment]
The examples has been removed so I'm closing this specific issue.
To be able to locate a shared library or an executable of a requirement we have introduced two ways, a virtual environment, and a build tool:

1) http://docs.conan.io/en/latest/mastering/virtualenv.html#virtualrunenv-generator
2) http://docs.conan.io/en/latest/mastering/build.html#runenvironment
