### ISSUE TITLE
Improve local flow page

### ISSUE THREAD

**Issue by lasote** [conan-io/docs#458]
- Formating @danimtb 
- Exemplify how to do it. Starting with a conan new Hello/0.1, then really executing the commands, building, creating the package, modifying the source code, repeat.

**Comment by memsharded** [comment]
- Make sure that the recipe folders ``self.source_folder``, ``self.build_folder``, etc are also explained better in this section (request from https://github.com/conan-io/conan/issues/2302)

**Comment by danimtb** [comment]
I think ``self.source_folder`` and ``self.build_folder`` are well explained here http://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=source_folder#folders and there is no further explanation needed. WDYT?
