### ISSUE TITLE
Setting options for required packages

### ISSUE THREAD

**Issue by bilke** [conan-io/docs#47]
Is it possible to require a package in a `conanfile.py` with some specific options? I would like to pass a `shared`-option (dynamic vs. static linking) from my package to a required package. If it is possible it should be documented under 

http://docs.conan.io/en/latest/reference/conanfile.html#requirements

**Comment by lasote** [comment]
Yes, you can do it:

```
from conans import ConanFile, CMake

class PocoTimerConan(ConanFile):
   settings = "os", "compiler", "build_type", "arch"
   requires = "Poco/1.7.2@lasote/stable" # comma separated list of requirements
   generators = "cmake", "gcc", "txt"
   default_options = "Poco:shared=True", "OpenSSL:shared=True"
```

I agree that it should be documented there too. (now is explained here http://docs.conan.io/en/latest/conanfile_py.html#migrate-from-conanfile-txt)

**Comment by memsharded** [comment]
Should be, yes. Please open a docs issue and assign it to me.

**Comment by lasote** [comment]
Like this? hahahah

**Comment by memsharded** [comment]
Ups, sorry, I thought it was a conan source issue, just came here directly from email, didnt read. XDDD.

**Comment by Tazura** [comment]
I think we should also be able to specify the options when calling self.required(...)

**Comment by memsharded** [comment]
@Tazura That might be a possibility, but the internal model highly decouples requirements from options, so to support this, ugly coupling of the ``Requirements`` and ``Options`` model should be done. So even if a UI improvement, I think better not do it and maintain a cleaner codebase

**Comment by danimtb** [comment]
I think the explanation to this issue is well writen here: http://docs.conan.io/en/latest/reference/conanfile/attributes.html#options-default-options

And even in the example of "Using packages" section: http://docs.conan.io/en/latest/using_packages/conanfile_txt.html#options

So I think this issue could be closed

**Comment by danimtb** [comment]
Maybe @memsharded could help to update the status about this issue

**Comment by memsharded** [comment]
Yes, this is already explained now in http://docs.conan.io/en/latest/reference/conanfile/attributes.html#options-default-options, can be closed. Thanks!

**Comment by Yuri6037** [comment]
Can you at least provide some explanation here: How am I supposed to pass options from dependency A to B when B is a build_requires?
