### ISSUE TITLE
Doc error using - vs. _

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/docs#481]
On http://docs.conan.io/en/latest/reference/commands/creator/export-pkg.html

Here a dash for --build`-`folder: 
`$ conan export-pkg . Hello/0.1@user/stable --build-folder build_x86`

Here a underscore for --build`_`folder:
`$ conan export-pkg . Hello/0.1@user/stable -pr=myprofile --source_folder=sources --build_folder=build`

Which is correct?

**Comment by memsharded** [comment]
You are right, there are some inconsistencies in the docs, and in the command line help

I have submitted fixes for both conan 1.0.2 and the docs.

The correct syntax is the dash, so everything looks the same: ``export-pkg``, ``source-folder``.

Thanks for pointing out this issue.

**Comment by memsharded** [comment]
Fixed and released
