### ISSUE TITLE
Alias page has upload intro text

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/docs#488]
The `alias` command [page ](http://docs.conan.io/en/latest/reference/commands/misc/alias.html) has the intro text for the `upload` command.  For example:

> `$ conan alias [-h] reference target`
> 
> Uploads a recipe and binary packages to a remote. If you use the –force variable, it won’t check the package date. It will override the remote with the local package.

**Comment by danimtb** [comment]
You are right! Thank you for reporting. We'd have it fixed asap.

**Comment by memsharded** [comment]
This is not only the docs, also ``conan alias --help`` shows the wrong message :S

**Comment by memsharded** [comment]
Docs have been updated (http://docs.conan.io/en/latest/reference/commands/misc/alias.html). The ``conan alias --help`` has been updated, it will be released soon. Thanks for the feedback!
