### ISSUE TITLE
DYLD_LIBRARY_PATH in RunEnvironment not working

### ISSUE THREAD

**Issue by lasote** [conan-io/docs#491]
Document that it doesn't work anymore for osx security restrictions, search for it and document it.

http://docs.conan.io/en/latest/reference/build_helpers/run_environment.html?highlight=DYLD_LIBRARY_PATH

**Comment by danimtb** [comment]
doing it like this will still work, right?
https://github.com/bincrafters/conan-templates/blob/34ae4b0c32f2866dee20f1ffc1e46d6fa68ef61c/test_package/conanfile.py#L18

**Comment by lasote** [comment]
yes
