### ISSUE TITLE
Recipe method flows/diagrams

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/docs#501]
A question that I see cropping up often in the Slack is "when running `conan xxx`, what methods are called and in which order?"  

To address these FAQs, add a section to each command page either a diagram/flowchart or a tablular  description of which methods are called.  You can sometimes glean this information from other parts of the docs (depending on the command) but having it as part of the reference would be useful.

**Comment by danimtb** [comment]
We have started doing this for ``$ conan create`` and and ``$ conan install`` inside the reference section #535 

Which do you think @sourcedelica  will be the most used commands that would need this information for users?

**Comment by sourcedelica** [comment]
Hi @danimtb 

- build
- create
- export
- export-pkg
- install
- package
- source

**Comment by sourcedelica** [comment]
There is another thing related to this that I have been thinking about.  Certain conanfile attributes are used in some methods but not in others.  For example `version` is only use at export time, but not beyond that ([see this comment](https://github.com/conan-io/conan/issues/1049#issuecomment-283181687)).  Are there others like version?

**Comment by memsharded** [comment]
@sourcedelica Not really, you can access ``self.version`` anytime in your recipe. Not only at export time, but also at build time (e.g. this is when the ``source()`` method is called, that typically uses ``self.version``)

**Comment by sourcedelica** [comment]
Ahh.  Ok, I misunderstood you. Thanks for the clarification.

**Comment by danimtb** [comment]
- ``conan build``: executes ``build()`` only -> already documented in reference and help command (``conan build --help``): http://docs.conan.io/en/latest/reference/commands/development/build.html

- ``conan source``: executes ``source()`` only -> already documented in reference and help command (``conan source --help``): http://docs.conan.io/en/latest/reference/commands/development/source.html

- ``conan package``: executes ``package()`` only -> already documented in reference and help command (``conan package --help``): http://docs.conan.io/en/latest/reference/commands/development/package.html

- ``conan create`` and ``conan install``: both already documented

- ``conan export``: Does not execute any method, just copies recipe to local cache as stated in docs http://docs.conan.io/en/latest/reference/commands/creator/export.html
