### ISSUE TITLE
Install packaging method

### ISSUE THREAD

**Issue by robertmrk** [conan-io/docs#51]
I opened this issue to post the examples @memsharded requested in conan-io/conan#316
Probably the easiest way to demonstrate the installation method that the PR conan-io/conan#316 enables is to provide a modified version of the [hello package project](http://docs.conan.io/en/latest/packaging/creating_in.html#packaging-from-the-source-project) described in the docs.
By adding the following lines at the end of the liststfile

``` CMake
INSTALL(TARGETS hello 
    ARCHIVE DESTINATION "lib")
INSTALL(FILES "hello.h" 
    DESTINATION "include")
```

and by modifying the `build` and `package` methods as described in conan-io/conan#316, the package would end up installing exactly the same files as before, and the [hello-use project](http://docs.conan.io/en/latest/packaging/creating_in.html#using-the-package-in-another-project) would be able to use it without any changes.
So the entire modified `CMakeLists.txt` file of the hello project would be:

``` CMake
PROJECT(MyHello)
cmake_minimum_required(VERSION 2.8)

SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/bin)
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_CURRENT_SOURCE_DIR}/bin)
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${CMAKE_CURRENT_SOURCE_DIR}/bin)

SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/lib)
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})

ADD_LIBRARY(hello STATIC hello.cpp)
ADD_EXECUTABLE(greet main.cpp)
TARGET_LINK_LIBRARIES(greet hello)
IF (WIN32 AND "${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    TARGET_LINK_LIBRARIES(greet stdc++)
ENDIF()

INSTALL(TARGETS hello 
    ARCHIVE DESTINATION "lib")
INSTALL(FILES "hello.h" 
    DESTINATION "include")
```

and the `conanfile.py` would be

``` python
from conans import ConanFile, CMake

class HelloConan(ConanFile):
    name = "Hello"
    version = "0.1"
    settings = "os", "compiler", "build_type", "arch"
    exports = "*"

    def build(self):
        cmake = CMake(self.settings)
        self.run('cmake %s %s -DCMAKE_INSTALL_PREFIX=%s' % \
            (self.conanfile_directory, cmake.command_line, self.package_folder))
        self.run("cmake --build . %s" % cmake.build_config)

    def package(self):
        self.run("cmake --build . --target install")

    def package_info(self):
        self.cpp_info.libs = ["hello"]
```

**Comment by memsharded** [comment]
Hi Robert!

I have documented this feature, already available at http://docs.conan.io/en/latest/howtos/cmake_install.html

It is also linked in the package() method reference, so it should be easy to find. Please have a look and close the issue if you think it is clear enough, or please tell me what to improve. Thanks very much!

**Comment by memsharded** [comment]
Actually with your example I think there might be a small problem, is that might build it twice. At least the ``cmake --build . --target install`` built my example, even if it was built before. Can you check it too, please?
