### ISSUE TITLE
binary remote download

### ISSUE THREAD

**Issue by jatimix** [conan-io/docs#524]
Hello,
I'm not sure I understand quite well the way conan handle remote package download.

But I got a particular use case that require some insight. I got relatively huge number of binaries (around 100mb * 100), which are prebuilt redistribuable that I can't rebuild. Each packages target a specific option.

I was thinking of making a conan package that select the right binary to be imported. However, if I understand how it work, conan is downloading the whole package (10Go) before executing the "package" method in conanfile.py. Which is something I don't want (cloud conan). There is also a solution where I create a recipe for each binaries and a conan package that modify self.requires at "conan install" time, Its not ideal: only to select the right "subpackage" I need 100+ conanfile, git and jenkins node to maintains (my conan remote is populated only through jenkins).

I was thinking if conan was able to download the "recipe", execute "package", then download the necessary binaries afterwards.

here a pseudo of what I mean:
```
class MyHugePackage(Conanfile):
       no_download= true

       def package(self):
            if self.options.need_huge_file_1:
                 self.from_remote_copy(*.huge_binary_on_remote_1, dst="prebuild/")
```
Here the workflow:
Download recipe -> package() -> download needed binaries.

Maybe is already implemented that way, but its not really clear from the documentation

Thanks :)

**Comment by memsharded** [comment]
Hello!

> But I got a particular use case that require some insight. I got relatively huge number of binaries (around 100mb * 100), which are prebuilt redistribuable that I can't rebuild. Each packages target a specific option.

Do you mean 100 different binaries for the same library/binary, but just for different configurations? Like different architectures, compiler versions, optimizations, etc? Os are they different binaries for different libraries?

> Which is something I don't want (cloud conan). 

You mean, you are going to use your own conan_server, or Artifactory? In any case, this is independent from using Bintray, from the conan perspective they are all the same, just the latest one is public (for OSS).

> conan is downloading the whole package (10Go) before executing the "package" 

No. ``package()`` method is only executed when you create the package the first time, before uploading it. ``conan install`` will only download the specific binary you need for your current configuration of settings/options.


Please elaborate a bit more what you are trying to achieve, and we will try to help. Thanks!

**Comment by jatimix** [comment]
Thanks for answering that quick,

Yes, I got same library but with different configuration : 
- libDistrib_x64_optionset_1.bin
- libDistrib_x64_optionset_2.bin
...
- libDistrib_x64_optionset_100.bin
etc..
Each library is prebuilt for security reason (actually its a proprietary format with encryption, thats why the size is huge and why we got so many different binaries), It might also grow as we need to support differents OS/toolchains in the future.

I already use my own conan server in a AWS. I need the smallest bandwith usage and downloading the whole 10Go each times we need to build its space and bandwith consuming. We also use jenkins, docker as a continuous integration tools and we don't want conan to download the whole 100+ binaries each time we are flushing the cache.

I actually want to create a consumer which is able to do this kind of thing : 
```
requires="LibDistrib[*]/prebuilt/channel"
default_options="LibDistrib:option_set1=True"

def build()
       ... etc
```
Maybe I should write a build() method which is downloading the library from a ftp/nfs, But I was wondering if it was possible to achieve this behavior just by tweaking conan.

Its like "I need this binary, in this conan_package, don't download the files I don't need".

Thank u!

**Comment by memsharded** [comment]
But that is exactly the behavior of conan :)

Your consumer will depend on the library. Only the binary with the ``option_set`` that you define will be retrieved, not all of them. By the way, you can also define options with sets, not only True/False, so maybe you want a range there.

The important thing is when you create the package you do ``conan create`` 100 times, giving the 100 possible different option values. It will create 100 different package binaries, you don't need to create 1 single package with all binaries for different configs in it.

**Comment by jatimix** [comment]
Well thank you, I did this and it work :) Perfect!
