### ISSUE TITLE
Could Visual Studio integrations page please explain how to programmatically create the Solution to enable Property Manager

### ISSUE THREAD

**Issue by claremacrae** [conan-io/docs#556]
I am using the generator `visual_studio_multi` - with tool versions listed at the bottom...

The following page says:

* "Go to your Visual Studio project, and open the Property Manager, usually in View -> Other Windows -> Property Manager."
* Click the “+” icon and select the generated conanbuildinfo.props file

http://docs.conan.io/en/latest/integrations/visual_studio.html#visual-studio

The problem I'm having is that there is no "+" icon in the Property Manager until you have a project added, and there are no instructions for how to set up the project for Conan in the first place, in order to correctly then be able to use the Property Manager. 

[for the record, that page of docs was at this this revision when I wrote this ticket:
https://github.com/conan-io/docs/commit/2f01dd2dc7f56dc4de2de837471ebd6342479cd2 ]

---

Background:
* I am using conan 1.0.4
* Visual Studio 2017:

```Microsoft Visual Studio Community 2017 
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA732
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA732
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA732
Microsoft Visual C++ 2017
```

**Comment by memsharded** [comment]
Hi Clare,

Maybe the docs are not detailed enough at that part. The VS solution and project is just a standard one. One you can create with the VS wizard, to create a static library, a dynamic library, an executable... You create your Solution with the Projects you want. Then, the Property Manager can be used (if not, look for it in View, or Windows).

Maybe this page can help: http://docs.conan.io/en/latest/howtos/visual_studio_packages.html It uses github repos with complete projects. 

Please tell me if this helps. Thanks!

**Comment by claremacrae** [comment]
Hi James

Thanks for the swift reply.

Sorry I was unclear - I am trying to programmatically create the VS .sln - I’ve been using CMake for that so far, to run cross-platform builds. CMake generates .sln files that load very well into Visual Studio, and allow switching between Release and Debug builds.

Now I have a dependency on 3rd-party libraries, I wanted to add managing of those libraries with Conan, but still machine-generate the .sln and .vcxproj files - and still be able to switch between configurations inside Visual Studio.

**Comment by claremacrae** [comment]
I should have added that I wasn’t aware of the howto page you linked to - thansk for that. Did I miss a link from the Visual Studio integration page to the Howto page?

As far as I can see, the Howto page talks about cloning existing .sln files and again, doesn’t talk about how to create one programmatically.

**Comment by memsharded** [comment]
Oh! If you are using CMake to generate the Visual Studio solutions, then you don't need the ``visual_studio`` generator, but I think you should definitely go with the ``cmake`` generator. If you want to switch configurations within Visual Studio then use the ``cmake_multi`` generator (beware of some current cmake limitations, as not dealing well with find-packages, because cmake don't know how to handle finding both debug and release packages).

**Comment by claremacrae** [comment]
Thanks - I’ll try this out tomorrow. (I actually started with the cmake generator and had problems with it - I couldn’t get stable, reproducible builds.)
Sure, I’ll put future questions unrelated to this to Slack.
Thanks again for the help!

**Comment by memsharded** [comment]
No problem, you can always post questions to github too, especially if you expect some feedback from the maintainers. Slack is great for more informal discussions and interactive help. Feel free to use both at your will. Looking forward your feedback regarding the above. Cheers.

**Comment by claremacrae** [comment]
Thanks  again for the help - I think this can be closed now, if you want... I don't think it's really actionable.
