### ISSUE TITLE
Stackoverflow Documentation

### ISSUE THREAD

**Issue by monsdar** [conan-io/docs#56]
Stackoverflow just introduced a new part of their network: A platform to provide documentation for all kinds of software development topics. Here's a direct link to the [intro page](http://stackoverflow.com/tour/documentation).

"Things" that documentation could be generated for are sorted into tags. See for example the tags for [C++](http://stackoverflow.com/documentation/c%2b%2b), [Boost](http://stackoverflow.com/documentation/boost) or [CMake](http://stackoverflow.com/documentation/cmake). The platform is very young and good content is currently being added.

My opinion is that this new platform is realized in a very good way. It would problably help Conan to be part of it. It is possible to propose new tags on the [main page](http://stackoverflow.com/documentation). If we have created a conan-tag it will be possible to put in documentation and examples.

**Comment by memsharded** [comment]
Yes, I had a look at documentation yesterday and it looks great. However, the "conan" stackoverflow tag for Q&A is still young, I have tried, and it is not eligible to be promoted to documentation yet, so not possible at the moment. We'll have to wait.
