### ISSUE TITLE
Inconsistent reference for copy() method

### ISSUE THREAD

**Issue by lasote** [conan-io/docs#562]
http://docs.conan.io/en/latest/reference/conanfile/methods.html#package

In the function prototype, we mention a "links=False" parameter that then is not documented.

**Comment by danimtb** [comment]
Seems links and symlinks do actually the same thing: https://github.com/conan-io/conan/blob/26ddf94bba4431ddeb2444dc1302bea5439be0dd/conans/client/file_copier.py#L67#L68

So let's keep only `symlinks` documented as I think it is easier to understand its purpose.
