### ISSUE TITLE
Clarify copy() method "src" parameter

### ISSUE THREAD

**Issue by liberforce** [conan-io/docs#577]
I find it a bit difficult to understand how `copy()` works.
http://docs.conan.io/en/latest/reference/conanfile/methods.html#package

The doc says (emphasis mine):
> The folder where you want to search the files in the **build folder**. If you know that your libraries when you build your package will be in build/lib, you will typically use build/lib in this parameter.
Leaving it empty means the **root build folder** in local cache.

As source, install, build and package folders can be located pretty much anywhere using the `--source-folder`-like options, `build/lib` doesn't give me much information. It's a relative path, but relative to what?

When I initialize a new package with `conan new`, the sample contains in the `package()` method:
`self.copy("*.h", dst="include", src="hello")`

So now here `src` seems relative to the source folder, as it's where the code is checked out in the `hello` example, but the doc says `src` is relative to the build folder. So how does it works?

**Comment by liberforce** [comment]
The question of recursivity is also unclear and should be explicited.

**Comment by danimtb** [comment]
Thanks @liberforce! We will try to improve the explanation
