### ISSUE TITLE
Install conan built packages into the operating system.

### ISSUE THREAD

**Issue by grafandreas** [conan-io/docs#590]
Dear conan.io-Team,

I have the following use case:
* I have used conan to cross-compile a an application that uses a number of libraries from Conan Center. The built libs are in my .conan dir on the build system (created by --build=missing).
* To run the built application on the host, I need an installation of the libs there. I would like install the built libs on the host just like I would with a "make install" (i.e. building on the host).

Is there a way to reuse the built conan packages from my .conan on the build machine for that?

Thanks for feedback.

**Comment by danimtb** [comment]
HI @grafandreas!

If you want to reuse the generated binaries you would have to upload them to a remote and fetch them from the host just like any other `conan install`.

In case you want to ship an application you can use the [deploy()](http://docs.conan.io/en/latest/reference/conanfile/methods.html?#deploy) method. But I am not sure if that applies to your use case.

Could you explain your case a little bit further?

**Comment by danimtb** [comment]
Closing this as a duplicated of conan-io/conan#2632
Please follow conversation there. Thanks!
