### ISSUE TITLE
Add clarification to ConanBase example

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/docs#591]
The `ConanBase` example at the end of the [Reusing Python code in your recipes](http://docs.conan.io/en/latest/howtos/python_code_reuse.html#sharing-a-python-module) page needs clarification.  Where can `ConanBase` come from?

See related (https://github.com/conan-io/conan/issues/2542, https://github.com/conan-io/conan/issues/2631, https://github.com/conan-io/conan/issues/1271)

**Comment by danimtb** [comment]
Hi @sourcedelica!

Thanks for pointing this out.
`ConanBase` is a class base that could be reused from `conan_base.py` file inside a `conanfile.py`.

The `conan_base.py` is exported with the `conanfile.py`. The only thing missing there is:

```
exports = "conan_base.py"
```

I think it could be added. Do you have any other suggestion?

**Comment by sourcedelica** [comment]
Hi @danimtb -

There is a chicken-egg problem.  If I'm understanding you correctly you are saying add `exports` like:

```
from conans import ConanFile
from base_conan import ConanBase

class ConanFileToolsTest(ConanBase):
    name = "test"
    version = "1.9"
    exports = "conan_base.py"
```

The line 
```
from base_conan import ConanBase
```
needs to be parsed before
```
class ConanFileToolsTest(ConanBase):
```

because `ConanFileToolsTest` inherits from `ConanBase`.  But `conan_base` doesn't exist because it hasn't been exported.  `ConanFileToolsTest` needs to be parsed in order to export the file `conan_base.py`.   But `ConanFileToolsTest` can't be parsed because it inherits from `ConanBase`.

**Comment by danimtb** [comment]
I tried a similar example and it works fine. You have to use `exports = "base_conan.py"`. Please give it a try.

I haven't found an example in our tests, so I will add it as a PR to prove it.

**Comment by sourcedelica** [comment]
Whoops - in my example I mixed up the filename (base_conan vs. 'conan_base.py').  Of course that wouldn't work!
