### ISSUE TITLE
The default conan server address is nowhere documented

### ISSUE THREAD

**Issue by monsdar** [conan-io/docs#61]
I removed my conan.io remote during some tests - Unfortunately I wasn't able to find the address again. After some time I stumbled across [the sources](https://github.com/conan-io/conan/blob/develop/conans/client/remote_registry.py) where the default remotes are defined.

It would probably be better to document the default server address somewhere. Perhaps this info could be part of the conan webpage search results / package info?

**Comment by memsharded** [comment]
Hi! You can find the details in http://docs.conan.io/en/latest/reference/commands.html#conan-remote
A search ``conan.io remote`` in the http://docs.conan.io/ site is supposed to find it.

**Comment by memsharded** [comment]
Hi! Did you find the info in the docs? I think it is documented fine in docs.conan.io, so I would say that this issue could be closed. Thank you!

**Comment by monsdar** [comment]
Sorry, somehow I missed this one being still open

**Comment by memsharded** [comment]
No problem, thanks for following up and closing!
