### ISSUE TITLE
Example in virtualenv docs are not working

### ISSUE THREAD

**Issue by LukeSkyw** [conan-io/docs#616]
Example in virtualenv docs are not working

Followed http://docs.conan.io/en/latest/mastering/virtualenv.html:
* First problem, `conan install` does not work:
```
user@cabd065217ed:~/test$ conan install
usage: conan install [-h] [-g GENERATOR] [-if INSTALL_FOLDER] [-m [MANIFESTS]]
                     [-mi [MANIFESTS_INTERACTIVE]] [-v [VERIFY]]
                     [--no-imports] [-j JSON] [-u] [-pr PROFILE] [-r REMOTE]
                     [-o OPTIONS] [-s SETTINGS] [-e ENV] [-b [BUILD]]
                     path
conan install: error: too few arguments
ERROR: Exiting with code: 2
```
* Second problem, cmake_install package is not found:
```
user@cabd065217ed:~/test$ conan install .
cmake-installer/0.1@lasote/testing: Not found in local cache, looking in remotes...
cmake-installer/0.1@lasote/testing: Trying with 'conan-center'...
ERROR: Unable to find 'cmake-installer/0.1@lasote/testing' in remotes
```
Tried with different version. Tried with `stable` instead of `testing`. Tried looking at the cmake_installer page in bintray and contrary to npm, there is no specific line you can just copy paste to install the package.

**Comment by memsharded** [comment]
Hi @LukeSkyw,

Thanks for reporting this. Yes, it seems this part of the docs is a bit old and incompatible with the current release. We will update it asap

Regarding the first issue, the path is needed:
```bash
$ conan install .
```
The second issue, the packages from conan center can be inspected with:
```bash
$ conan search cmake* -r=conan-center
```
You'd need to use e.g. ``cmake_installer/3.8.2@conan/stable``.

**Comment by memsharded** [comment]
Quick tip. You can also directly do:

```bash
$ conan install cmake_installer/3.9.0@conan/stable -g=virtualenv
```
Without requiring creating the *conanfile.txt*

**Comment by memsharded** [comment]
Fixed in: https://github.com/conan-io/docs/commit/4adbc940ec036562fc781798efaeb41a4d1f04e2

Live at: http://docs.conan.io/en/latest/mastering/virtualenv.html

Thanks very much for reporting this!
