### ISSUE TITLE
Getting started hard to understand

### ISSUE THREAD

**Issue by Nek-** [conan-io/docs#620]
Hello,

I'm not used to C++ world. It's even worse with package managers for C++. So I tried the getting started, but I see this sentence that I cant understand:

<p align="center">
<img src="https://user-images.githubusercontent.com/972456/38473750-30176cc8-3b95-11e8-80bc-74a41feb1829.png" alt="Getting started" />
<b><i>What file ??? How to generate this one ???</i></b>
</p>

I hope it will help you to have a better documentation. Maybe I will be able to post some other weird things. :smile:

**Comment by Nek-** [comment]
I understand that I'm maybe not the main target of conan. I know Cpp, and used to use it with QtCreator, which is a completely different context... But I really think I should be able to understand this documentation, and if I don't, then something is probably wrong.

Let me track again what it says:

### Configuration of conanfile.txt
> In this example we will use CMake to build the project, which is why the cmake generator is specified.

Ok, we specify `cmake` as configuration. All good.

### The `conanbuildinfo.cmake`
> This generator will create a conanbuildinfo.cmake file that defines CMake variables as include paths and library names, that can be used in our build.

Ok, it **will** create the file (no idea how, by running what command etc).

### Creation of `CMakeLists.txt` file
> Just include the generated file and use these variables inside our CMakeLists.txt:

What? You just said that the `conanbuildinfo.cmake` will be generated (I don't even know how at this state). And you're now saying this?
- Why "just"? Maybe I miss a part of the sentence
- What generated file?

At this state there is no generated file. That's why it's disturbing.

Is it more clear ? :)

**Comment by memsharded** [comment]
Oh! Now I see it. I think it is mostly a grammar/expression issue, as we are not native speakers, the present and future tenses are a bit mixed, and it is not that clear. Thanks @Nek- !
