### ISSUE TITLE
Put cmake.install() in the package() method

### ISSUE THREAD

**Issue by memsharded** [conan-io/docs#654]

**Comment by roe85** [comment]
It has the caveat of being called twice when used with `no_copy_source = True`.
> The package() method will be called twice if the attribute no_copy_source is defined and True.

**Comment by memsharded** [comment]
@roe85 Good point. 

Maybe only the ``self.copy()`` calls should be executed twice, but I am not sure how that could be implemented. Will have a look when possible.

**Comment by danimtb** [comment]
This was already accomplished in #750 with a proper explanation about ``no_copy_spurce`` as @roe85 suggested. Thanks!
