### ISSUE TITLE
profile example for ios?

### ISSUE THREAD

**Issue by CingKong** [conan-io/docs#666]
[Solved](https://github.com/conan-io/docs/issues/666#issuecomment-394704318)

**Comment by CingKong** [comment]
I looked through most of google results, and didnt manage to find something useful :(

**Comment by CingKong** [comment]
That sounds awesome! xD

**Comment by theodelrieu** [comment]
High @CingKong, I just released `darwin-toolchain`, it will be available on conan-center shortly.

Meanwhile, you can take a look at the [Readme](https://github.com/theodelrieu/conan-darwin-toolchain).

Let me know how it goes ;)

**Comment by CingKong** [comment]
There surely is a big problem... to me. 
`ERROR: Unable to find 'Darwin-toolchain/1.0@theodelrieu/stable' in remotes`
😂I dont have your repository.

**Comment by lasote** [comment]
It is linked in `conan-center` so yes, you have it ;) but you have to write the correct reference, that are case sensitive:

`darwin-toolchain/1.0@theodelrieu/stable`

**Comment by theodelrieu** [comment]
Do you have Xcode installed? The Readme says it does not *yet* install it automatically

**Comment by CingKong** [comment]
installed Xcode Version 9.3 (9E145)

**Comment by theodelrieu** [comment]
You also need command line tools.

What happens if you try to run `xcrun` on the terminal?

**Comment by CingKong** [comment]
Xcrun exists on my machine

**Comment by CingKong** [comment]
`Virgos-Mac:~ virgo$ xcrun
Usage: xcrun [options] <tool name> ... arguments ...

Find and execute the named command line tool from the active developer
directory.

The active developer directory can be set using `xcode-select`, or via the
DEVELOPER_DIR environment variable. See the xcrun and xcode-select manual
pages for more information.

Options:
  -h, --help                  show this help message and exit
  --version                   show the xcrun version
  -v, --verbose               show verbose logging output
  --sdk <sdk name>            find the tool for the given SDK name
  --toolchain <name>          find the tool for the given toolchain
  -l, --log                   show commands to be executed (with --run)
  -f, --find                  only find and print the tool path
  -r, --run                   find and execute the tool (the default behavior)
  -n, --no-cache              do not use the lookup cache
  -k, --kill-cache            invalidate all existing cache entries
  --show-sdk-path             show selected SDK install path
  --show-sdk-version          show selected SDK version
  --show-sdk-build-version    show selected SDK build version
  --show-sdk-platform-path    show selected SDK platform path
  --show-sdk-platform-version show selected SDK platform version
Virgos-Mac:~ virgo$ which xcrun
/usr/bin/xcrun
`

**Comment by theodelrieu** [comment]
Hmm, what about running the same command line that conan complains about? 

At least we'll what goes wrong

**Comment by CingKong** [comment]
i dont know python xD, stucked at the first line
`ModuleNotFoundError: No module named 'conans'`

**Comment by theodelrieu** [comment]
Make sure that you have the latest conan version by running:

>pip install conan --upgrade

If using python3, make sure to use `pip3`.

I hope it's just that...

**Comment by CingKong** [comment]
actually i upgrade conan early using brew when i encountered another error, that did fix it, but not this one

**Comment by CingKong** [comment]
```
Virgos-Mac:conan-darwin-toolchain virgo$ conan install . --profile iOS --build=missing
PROJECT: Installing /Users/virgo/conan-darwin-toolchain/conanfile.py
Requirements
Packages

Cross-build from 'Macos:x86_64' to 'iOS:armv7'
PROJECT: Installing build requirements of: PROJECT
PROJECT: Build requires: [darwin-toolchain/1.0@theodelrieu/stable]
PROJECT: Requirements
PROJECT:     darwin-toolchain/1.0@theodelrieu/stable from 'conan-center'
PROJECT: Packages
PROJECT:     darwin-toolchain/1.0@theodelrieu/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
PROJECT: 
darwin-toolchain/1.0@theodelrieu/stable: WARN: Package is corrupted, removing folder: /Users/virgo/.conan/data/darwin-toolchain/1.0/theodelrieu/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
darwin-toolchain/1.0@theodelrieu/stable: Retrieving package 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 from remote 'conan-center' 
Downloading conanmanifest.txt
[==================================================] 59B/59B          
Downloading conaninfo.txt
[==================================================] 236B/236B        
Downloading conan_package.tgz
[==================================================] 63B/63B          
darwin-toolchain/1.0@theodelrieu/stable: Package installed 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'iphoneos'
ERROR: darwin-toolchain/1.0@theodelrieu/stable: Error in package_info() method, line 36
	sysroot = xcrun.sdk_path
	CalledProcessError: Command '['xcrun', '-find', '-sdk', 'iphoneos', '--show-sdk-path']' returned non-zero exit status 1.
Virgos-Mac:conan-darwin-toolchain virgo$ xcrun -find -sdk iphoneos --show-sdk-path
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'iphoneos'
Virgos-Mac:conan-darwin-toolchain virgo$ xcrun --show-sdk-path
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
Virgos-Mac:conan-darwin-toolchain virgo$ ls /Library/Developer/CommandLineTools/SDKs/
MacOSX.sdk	MacOSX10.14.sdk
```

guess this is the issue, i dont have an iphone sdk at all?

**Comment by theodelrieu** [comment]
Yep, makes sense, did you install with the Xcode dmg?

IIRC it installed everything for me.

**Comment by CingKong** [comment]
I installed from appstore, now upgrading to 9.4, it would take hours due to my slow internet.

**Comment by CingKong** [comment]
should have googled for the error message before, wasted so much time, and the solution to this sdk not found issue is simply do a [`xcode-select --reset`](https://stackoverflow.com/a/41036851/6643157)

now i encountered an error building openssl for iOS using conan, its not an **conan-io/docs** issue but hopefully people here can help me with it
```
OpenSSL/1.0.2o@conan/stable: WARN: Build folder /Users/virgo/.conan/data/OpenSSL/1.0.2o/conan/stable/build/7b8145efacf94df45e34a493b54d49e9514c4fde
ERROR: OpenSSL/1.0.2o@conan/stable: Error in build() method, line 115
	self.ios_build(config_options_string)
while calling 'ios_build', line 250
	cc += " -arch %s" % to_apple_arch(self.settings.arch)
	TypeError: can't concat str to bytes
```
