### ISSUE TITLE
uploading header only packages to conan

### ISSUE THREAD

**Issue by agauniyal** [conan-io/docs#67]
Hi, I was going through conan docs hoping to find a real quick example to upload my source to conan.io. I've a [simple header only library](https://github.com/agauniyal/rang) that I plan to use in other projects with conan as package manager. The code currently builds with cmake and meson, and is compatible with meson wrapdb too so other meson users can import it into their projects. I'm only exporting a single header `rang.hpp` inside `include` directory of my repo.

Going through the docs, I found - 

```
from conans import ConanFile, CMake

class HelloConan(ConanFile):
    name = "rang"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"
    exports = "*"

// should I remove this since I don't need to build anything
    def build(self):
        cmake = CMake(self.settings)
        self.run('cmake %s %s' % (self.conanfile_directory, cmake.command_line))
        self.run("cmake --build . %s" % cmake.build_config)

    def package(self):
        self.copy("*.hpp", dst="include")

// and remove this too?
    def package_info(self):
        self.cpp_info.libs = ["hello"]
```

would the above conf be able to export `rang.hpp` so that when user does `#include "rang.hpp"` and uses conan with it, it compiles successfully?

**Comment by memsharded** [comment]
A few tips:

- If it is header_only, just remove the settings line. You will not have a binary, so no settings needed.
- Yes, you can remove the build() method
- The ``package_info()`` can be removed too, as by default it already includes the ``include`` directory in the include paths

You might have a look at some other header-only lib, like this one: https://github.com/memsharded/conan-date/blob/master/conanfile.py

**Comment by memsharded** [comment]
BTW, I strongly suggest other things, check the docs and ask if any doubt:

- Creating a ``test_package``.
- You might be interested in ``build_policy="missing"``, to not require the --build flag

**Comment by agauniyal** [comment]
Thankyou for responding such quickly. I'll make sure to read the suggested docs and give it a go 😄 .

**Comment by memsharded** [comment]
You are welcome. You might also have a look to the ``conan new MyPackage/1.0@myuser/channel -h -t`` command, that will create a default recipe for header-only and a test_package.

Thanks to you for telling, many times it is true that we could improve the docs, maybe it deserves a how-to or an entry in the FAQs? Dont be afraid to submit issues also to the docs repo, even PRs :)

Tell me if everything worked with the docs, or if you have any further question. Cheers!

**Comment by agauniyal** [comment]
@memsharded could you help us out here - https://github.com/agauniyal/rang/issues/29 :smile:

**Comment by lasote** [comment]
I suggest a Howto upload a header only package aggregating info about:

- Talking about conan new -h
- Settings
- build_policy

**Comment by solvingj** [comment]
I think one or more of the comments above regarding "conan new" might have been intended to say "-i" instead of "-h" for header only.  It's possible they meant -h, as that means help... but for posterity, just posting here that -i gets the header-only template on the "conan new" command.

**Comment by memsharded** [comment]
Done, updated comments.
Also, for posterity, there is a dedicated section for header only in the docs: http://docs.conan.io/en/latest/howtos/header_only.html
