### ISSUE TITLE
Confusing how-to of shared libraries regarding virtualrunenv

### ISSUE THREAD

**Issue by memsharded** [conan-io/docs#676]
The page https://docs.conan.io/en/latest/howtos/manage_shared_libraries.html is not using virtualrunenv, but instead virtualenv and defining ``package_info()``. This section has to be updated, it is not clear.

Comes from https://github.com/conan-community/conan-tbb/issues/6

cc /@db4

**Comment by db4** [comment]
Just to understand it better myself. Now
```python
def package_info(self):
    self.env_info.PATH.append(os.path.join(self.package_folder, "bin"))
```
is not recommended at all?

**Comment by memsharded** [comment]
@db4 

It is not that it is not recommended, more that it is not necessary in many cases. It depends how you want to manage, and the fine control you want to have. The ``virtualrunenv`` will automatically add all bindirs folders of all packages to PATH. So all executables that are packaged in the dependencies will be available. This works fine for most of the cases, and it doesn't require adding it manually to the recipes.

But there might be some cases where you want to control that only a given package is adding its binaries to the PATH, in that case it could make sense to explicitly add it to the ``package_info()``.

What I am suggesting to add in the docs, is to explain as default the first, automatic approach that doesn't require modifications to recipes, then explain the second one as a manual approach for special cases.
