### ISSUE TITLE
Re-enable the possibility to download the docs

### ISSUE THREAD

**Issue by dkgs** [conan-io/docs#682]
Hello,

I'm using conan on separated network which doesn't have any internet connection. When I'm upgrading conan, I download the installer and the docs in PDF format (from the bottom left menu).
As I was trying to download the docs for the version 1.4.3, the download links presenting the different ways to download the docs are no more present.

Will this feature be available again ?

**Comment by danimtb** [comment]
Hi @dkgs 

Yes, we recently migrated the documentation from readthedocs to our github pages and we lost that feature. Currently there is no PDF available as it was automatically generated by readthedocs.

There is PR open #631 to generate very nice offline documentation directly from sphinx but we have not merged it yet.
