### ISSUE TITLE
Documenting the format of remotes.txt for conan config install

### ISSUE THREAD

**Issue by cstratopoulos** [conan-io/docs#697]
This issue concerns the documentation for https://docs.conan.io/en/latest/reference/commands/consumer/config.html#conan-config-install

When setting up a conan config for installation, it was not immediately clear to me what should be the format of the `remotes.txt` file.

My first guess was that `conan remote list > remotes.txt` would do the trick, but this fails in a pretty cryptic way:
```
Unzipping 100 %                                                       Defining remotes
ERROR: Bad file format, wrong item numbers in line 'ÿþc o n a n - c e n t e r :   h t t p s : / / c o n a n . b i n t r a y . c o m   [ V e r i f y   S S L :   T r u e ] '
```

Eventually I ended up googling around for examples and found this one:
https://github.com/bincrafters/conan-config/blob/master/remotes.txt

I later realized that the answer was sort of spelled out in the documentation
> The local cache registry.txt file contains the remotes definitions, as well as the mapping from packages to remotes. In general it is not a good idea to add it to the installed files.

so that `cat ~/.conan/registry.txt` shows the right format, but I think this is unclear too.

I think it could be helpful to just say something like 
> The file `remotes.txt` is a plain text file where each line consists of
    `[remote name] [remote url] [bool]`
where `<bool>`  is `True` or `False` indicating whether or not to verify SSL. 

Just as an aside (but something that would probably belong on the issues for the conan repo itself) maybe it could be helpful to add a positional argument like `list_export` or something to `conan remote` so that `conan remote list_export > remotes.txt` works?

**Comment by memsharded** [comment]
Yes, you are totally right, it is not evident what format should they use. Would you like contributing those lines yourself via a pull request? :)

For the second suggestion, maybe ``conan remote list --raw`` could make more sense, it is aligned with other args in other commands. In any case sounds like an optional --something to the ``list`` subcommand. Please submit an issue to the main conan repo (and that should be relatively easy to implement, if you want to try to contribute it too).

Thanks for reporting these things!

**Comment by cstratopoulos** [comment]
@memsharded thanks for the reply! I would be happy to contribute a documentation PR, and I will open an issue in conan main as well. A `list  --raw` PR does sound feasible as well but I'll poke around the source code a bit before volunteering for that, and I will open an issue meanwhile!

**Comment by memsharded** [comment]
Sure, many thanks!! Do not hesitate to ask any question around the code if you need. Cheers.
