### ISSUE TITLE
PDF for 1.5 doesn't work

### ISSUE THREAD

**Issue by lasote** [conan-io/docs#745]
I think it should because I merged master into the 1.5.2

**Comment by lasote** [comment]
Actually, the PDF is there, but the link is bad: 
- https://docs.conan.io/en//conan.pdf
- https://docs.conan.io/en/1.5/conan.pdf

**Comment by danimtb** [comment]
#746 #747 #748

**Comment by danimtb** [comment]
Already merged and fixed!
