### ISSUE TITLE
Getting started fails with a modern gcc compiler

### ISSUE THREAD

**Issue by lasote** [conan-io/docs#767]
Read: https://github.com/conan-io/conan/issues/3370

We should introduce at least a note or something for modern GCC users.

**Comment by danimtb** [comment]
In #810 we moved the libcxx warning up to the **Installing depdendencies** subsection. I think it should be quite clear. Maybe if there are more issues with this we could include the suggested CMake libcxx coammand:
```
cmake .. -DCONAN_LIBCXX=libstdc++
```
