### ISSUE TITLE
Documentation for develop attribute looks incorrect

### ISSUE THREAD

**Issue by keithrob91** [conan-io/docs#771]
The docs state that "Develop mode" will be output if the following command is used:
`conan create user/testing`

As far as I can tell, this is an invalid way of running conan create and the command will return:

> conan create: error: too few arguments

**Comment by memsharded** [comment]
Certainly. All commands try to follow the ``conan command <path-to-conanfile-or-reference> other-args``. In this case it is missing the dot: ``conan create . user/testing``. Will change it now.
