### ISSUE TITLE
New tools.Git feature - get branch

### ISSUE THREAD

**Issue by hatl** [conan-io/docs#778]
Hi

In the changelog of 1.6, you are listing the following:

Feature: Improved tools.Git to allow capturing the current branch and enabling the export of a package whose version is based on the branch and commit

I can't find anything regarding this feature in the documentation.
The method is not documented:
https://docs.conan.io/en/latest/reference/tools.html#tools-git

Could you please give an example on how to export a package whose version is based on the branch and commit?

Thanks!

BR

**Comment by memsharded** [comment]
Hi @hatl

You are right, find https://github.com/conan-io/docs/issues/779 an example how to do it. Thanks for the feedback!

**Comment by hatl** [comment]
Thanks for the very fast response!
The `git.get_branch(), git.get_revision()` always exceeds the 50 character limit for conan versions in my case :-)
So for now, we are just cut-off the branch name.

It would really be great if you could show, how it is possible to put this code into a common library
As far as I know, this is currently not possible and would need some implementation like suggested in https://github.com/conan-io/conan/issues/1271
correct?

**Comment by danimtb** [comment]
Docs updated! 👍
