### ISSUE TITLE
Escaping issues with windows paths

### ISSUE THREAD

**Issue by liberforce** [conan-io/docs#788]
Some paths using backslashes fail to be interpreted the right way.
Here are the current occurences: 

```
$ git grep 'C:\\\\'
integrations/cmake/find_packages.rst:Sometimes the "official" CMake FindXXX.cmake scripts are not ready to find our libraries (not supported library names for specific settings, fixed installation directories like
reference/config_files/conan.conf.rst:If not specified, the packages marked as `short_paths` will be stored in the `C:\\.conan` (or the current drive letter).
reference/env_vars.rst:marked as `short_paths` will be stored in the `C:\\.conan` (or the current drive letter).
```
So for example, `C:\\.conan` is displayed as `C:.conan`. This is a bit strange because of doubling the [backslashes is how it seems it should work](http://docutils.sourceforge.net/docs/user/rst/quickref.html#escaping).

**Comment by danimtb** [comment]
Seems this was fixed with your own PR so closing this...
