### ISSUE TITLE
Meson example should show dependency consumption within `meson.build` file

### ISSUE THREAD

**Issue by adaviding** [conan-io/docs#807]
I'd like to suggest an improvement to the documentation on this page:  https://docs.conan.io/en/latest/reference/build_helpers/meson.html

So the magic with conan is that I am getting some `*.pc` files generated automatically, but the current example does not show how to consume the `*.pc` dependencies from the `meson.build` file.  I think that is the most important point, but the example doesn't cover it.

For example, if my conanfile.py depends on Boost and Poco ...

```python
from conans import ConanFile, tools, Meson
import os


class PanoptoBase(ConanFile):
    default_options = \
        "boost:shared=False"

    exports_sources = "include/*"

    generators = "pkg_config"

    requires = \
        "Poco/1.8.0.1@pocoproject/stable", \
        "boost/1.66.0@conan/stable"

    settings = \
        "os", \
        "compiler", \
        "build_type"

    def build(self):
        meson = Meson(self)
        meson.configure(build_folder="./build", pkg_config_paths="./build")
        meson.build()
```

... then I will have 5 `*.pc` files after I execute `conan install ..` shown here:

```
* boost.pc
* bzip2.pc
* OpenSSL.pc
* Poco.pc
* zlib.pc
```

So then the `meson.build` file should show how I suck those dependencies in from the `*.pc` files as follows:

```
project(
    'Whatever.Lib',
    'cpp',
    version: '0.0.0',
    meson_version: '>= 0.47.0',
    default_options: [ 'buildtype=debug',
                       'cpp_std=c++11',
                       'warning_level=1']
)

includeFolder = include_directories('include')

static_library(
    'package_name',
    [   'src/whatever.cpp',
    ],
    include_directories: includeFolder,
    dependencies:
    [   dependency('boost'),
        dependency('bzip2'),
        dependency('OpenSSL'),
        dependency('Poco'),
        dependency('zlib')
    ]
)
```

**Comment by lasote** [comment]
Mhh, but the default `pkg_config_paths` parameter, when not specified is pointing to the "install" folder, where the generator file should be located. Could it maybe be a bug?

**Comment by lasote** [comment]
I tested it manually and it works.

**Comment by memsharded** [comment]
I think the OP is not talking about the .pc files, which are indeed found and used, but how Meson needs to actually inject that information in the build to specific libraries and executables (via ``dependencies``). I think  adding a full example, consuming Poco, as the one depicted above would be good.

**Comment by lasote** [comment]
oh! I see. I agree then.

**Comment by adaviding** [comment]
After working more with conan / meson, I think the `meson.configure` line should be:

```
meson.configure(build_folder="build")
```

FYI:  If you don't define a `build_folder` to be different from the `source_folder` then you will always get an error during `create`.  For example I executed `conan create . ding/testing` and I get:

```
Error during basic setup:

Source and build directories must not be the same. Create a pristine build directory.
Panopto.Native.Base.Lib/0.0.0@ding/testing: 
Panopto.Native.Base.Lib/0.0.0@ding/testing: ERROR: Package '540d45cdd0deb5164fda82545dec7d0144f769ed' build failed
Panopto.Native.Base.Lib/0.0.0@ding/testing: WARN: Build folder /home/ding/.conan/data/Panopto.Native.Base.Lib/0.0.0/ding/testing/build/540d45cdd0deb5164fda82545dec7d0144f769ed
ERROR: Panopto.Native.Base.Lib/0.0.0@ding/testing: Error in build() method, line 62
	meson.configure()
	ConanException: Error 256 while executing meson "/home/ding/.conan/data/Panopto.Native.Base.Lib/0.0.0/ding/testing/build/540d45cdd0deb5164fda82545dec7d0144f769ed" "/home/ding/.conan/data/Panopto.Native.Base.Lib/0.0.0/ding/testing/build/540d45cdd0deb5164fda82545dec7d0144f769ed" --backend=ninja --buildtype=debug
```
I wasted a couple hours debugging this.  For the Meson build helper, you might want to put an informative error message to catch `source_folder == build_folder` which is never okay with Meson.
