### ISSUE TITLE
Encourage use of SPDX licenses in the "license" attribute of ConanFile

### ISSUE THREAD

**Issue by liberforce** [conan-io/docs#811]
The plan behind this is exposed at: https://github.com/conan-io/conan/issues/3498
Either way, SPDX is a Linux Foundation standard and should be encouraged.

**Comment by liberforce** [comment]
Could someone tell me if a PR for this would be accepted?

**Comment by memsharded** [comment]
Hi @liberforce 

No, a PR for this feature might not be the best approach at this time. We are about to release the "plugins" feature, and we strongly think that this feature is the perfect fit for a "plugin", so it can be very easily adapted and customized for different use cases, and applied in an orthogonal way to all packages. Have you already checked the "plugins" in the develop docs: https://github.com/conan-io/docs/pull/846?

**Comment by liberforce** [comment]
Hi @memsharded 

Sorry that I wasn't clear enough. This bug is not about _how to check the license_, but _which content to put in the "license" attribute_. Currently most packagers follow the current guidelines and put whatever they think is correct. This is not adapted to automation. Having a plugin that checks SPDX licences will be useless if community conan packages don't put SPDX data in the license field when that makes sense.

Look at [bzip2](https://github.com/conan-community/conan-bzip2/blob/release/1.0.6/conanfile.py#L18), [zlib](https://github.com/conan-community/conan-zlib/blob/release/1.2.11/conanfile.py#L16), [eigen](https://github.com/conan-community/conan-eigen/blob/stable/3.3.5/conanfile.py#L13), [gtest](https://github.com/bincrafters/conan-gtest/blob/stable/1.8.1/conanfile.py#L14), [openssl](https://github.com/conan-community/conan-openssl/blob/release/1.0.2o/conanfile.py#L14). All these use a mix of free formed text, URLs. None of those use SPDX, even though all those licenses exist in SPDX. I don't think that's because people don't want to use SPDX, just that they can't use something they don't know.

Currently the documentation just says:

> This attribute can contain several, comma separated licenses. It is a text string, so it can contain any text, including hyperlinks to license files elsewhere.

I would add after that something like:

> However, we encourage packagers of Open-Source projects to use [SPDX](https://spdx.org/) identifiers from the [SPDX license list](https://spdx.org/licenses/) instead of free formed text. This will help people wanting to automate license compatibility checks, like consumers of your package, or you if your package has Open-Source dependencies.

I think that's the best place to put that information. But if you really are against that idea, maybe there's a packaging best practice guide for packages inside conan-community where this could be added?

**Comment by Croydon** [comment]
Yes please, recommending SPDX license names may end this fragmentation of different naming styles.

**Comment by memsharded** [comment]
Oh, yes, sorry, my bad. I missed the context.
Yes, we certainly can strongly recommend to use standard licenses in the ``license`` field. 
Yes, definitely a PR for the docs that "strongly recommend" it, will be welcome.
