### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by uilianries** [conan-io/docs#832]
Hi!

Conan is growing fast but is only available in english.  
Some communities from other countries could have some difficult to introduce Conan without any support, including by documentation.

Here in Brazil we have a popular community called "Viva o Linux" (means "Live Linux" or "Viva el Linux") where all articles are posted in portuguese. I have written some articles about Conan, but I need to replicate much information from the docs.

Now Conan community has people from around the world, so I see a good opportunity to start a multi language support for Conan docs.

Google could translate any web page, it helps but fail when you need to translate an english command on same line where is a regular text.

We could start just adding new languages at the top of the page and get some support from the community. I think that Conan is present is mostly popular countries nowadays.

**Comment by danimtb** [comment]
Hi @uilianries 

I understand and see your point but I cant even imagine the effort of maintaining a multi-language documentation

 Currently we don't even have people in the team dedicated only to documentation, the Conan devs are the ones writing the documentation of the tool and most of the Conan contents (btw, I think this is the right way to do it) and although I think docs are not bad, I see we would need to dedicate more time to them just for English.

I tried to think about other OSS tech tools with multi-language support documentation but cant tell anyone out there. Not to say that we don't talk any other language proficiently (We are not even proficiency in English 😆) and we couldn't ensure the same quality for all of them.

**Comment by memsharded** [comment]
While I understand the issue, I think the first step is to have strong evidence that other successful open-source dev tools (git, docker, cmake...) have succeeded in creating and maintaining such a multi-language documentation. Unfortunately I don't think this is the case, and agree with @danimtb that the issue could be the huge effort that it implies.

**Comment by uilianries** [comment]
Excellent thoughts!

Now I agree with your ideas. Thinking again, only newbies could be attracted by a multi-language support, but the effort to maintain it wont be paid by the result.

I have supported some multi-language projects, including the documentation, but is a huge effort. For the software we use babel project -- in that case babel is related directly to web interface and CLI.

So I presume that give punctual support is the best way to solve edge cases where newbies need non-english support.

Thanks for sharing your views!
