### ISSUE TITLE
CFLAGS and CXXFLAGS values in cross-building to Android

### ISSUE THREAD

**Issue by Paultergeist** [conan-io/docs#833]
There is a sample profile in docs about [cross-building to Android](https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#linux-windows-macos-to-android).

It has the following lines:
```
CFLAGS= -fPIE -fPIC -I$standalone_toolchain/include/c++/4.9.x
CXXFLAGS= -fPIE -fPIC -I$standalone_toolchain/include/c++/4.9.x
```

I see 2 issues here:
1. Path to C++ headers should not be added `CFLAGS`
2. `-isystem` should be used for system headers instead of `-I`:
```
CXXFLAGS= -fPIE -fPIC -isystem $standalone_toolchain/include/c++/4.9.x
```

**Comment by lasote** [comment]
Agree. Thanks!

**Comment by SSE4** [comment]
the referenced CFLAGS are no longer suggested in the doc
