### ISSUE TITLE
QMake integration documentation missing a code block

### ISSUE THREAD

**Issue by Talkless** [conan-io/docs#841]
Looks like (at least it feels so) that `qmake` integration is missing some code block, after this line and column:
> This hello package is created with cmake, but that doesn't matter, it can be consumed from a qmake project:

https://github.com/conan-io/docs/blame/04dbe291f77608f84c97a8c8e0f2296c707c6c4a/integrations/qmake.rst#L54

Or should it have been a stop, without any example?

**Comment by danimtb** [comment]
Yes, may a period is needed there. I will take a look. Thanks for reporting @Talkless

**Comment by danimtb** [comment]
fixed in #842
