### ISSUE TITLE
Example for SVN versioning

### ISSUE THREAD

**Issue by climblinne** [conan-io/docs#861]
Show an example of how to add versioning to svn inline scm. See conan-io/conan#3192

**Comment by jgsogo** [comment]
Just a link to the comment where it all started: https://github.com/conan-io/conan/pull/3192#issuecomment-425539170

**Comment by climblinne** [comment]
Generated pull request. So closing this issue.

**Comment by danimtb** [comment]
Please @climblinne keep the issue open until it solved my merging a PR with the requested action. Thanks!

**Comment by jgsogo** [comment]
Thanks for the contribution, @climblinne!
