### ISSUE TITLE
CMake: Missing information about CMAKE_POSITION_INDEPENDENT_CODE

### ISSUE THREAD

**Issue by Croydon** [conan-io/docs#864]
CMAKE_POSITION_INDEPENDENT_CODE is getting set automatically by Conan when fPIC == True, but I can't find this information in the docs.

**Comment by danimtb** [comment]
Please, check the definitions section: https://docs.conan.io/en/latest/reference/build_helpers/cmake.html?highlight=fpic#definitions

> 
`CONAN_CMAKE_POSITION_INDEPENDENT_CODE` | When `fPIC` option is present and `True` or when `fPIC` is present and `False` but and option `shared` is present and `True`
