### ISSUE TITLE
Better docs for VS Debug/Release

### ISSUE THREAD

**Issue by memsharded** [conan-io/docs#87]
From: https://github.com/conan-io/conan/issues/616#event-841122786

**Comment by danimtb** [comment]
There is an explanation here: https://github.com/conan-io/docs/blob/develop/howtos/visual_studio_packages.rst#reusing-packages

Is a longer explanation needed?

**Comment by danimtb** [comment]
kindly reminder @memsharded

**Comment by memsharded** [comment]
Yes, I think now the docs are much more complete regarding these points, so this can be closed.
