### ISSUE TITLE
Docs used to have an "Edit" button in top right, now gone

### ISSUE THREAD

**Issue by solvingj** [conan-io/docs#873]
I don't know when it changed, a while ago I think, but it was a 1 click operation to jump to creating a PR for a page while browsing that page. I can't find that button anymore, there's no only "view page source" which isn't helpful.  Am I missing something?

**Comment by memsharded** [comment]
The Edit button was automatically inserted by ReadTheDocs, but when we moved the docs to github, we lost that button. I guess it should be doable, but don't know the complexity, lets have a look
