### ISSUE TITLE
Add a notice early in the docs about short_paths

### ISSUE THREAD

**Issue by jgsogo** [conan-io/docs#890]
In Windows, in your first steps using Conan, you can come across a folder ``C:/.conan`` containing a lot of stuff... but in the docs the issue about ``short_paths`` is not mentioned at the beginning, so it's hard for a newbie to know why this directory exists.

Let's add a comment about it at the very beginning, as soon as the Conan cache is introduced to the user, just a side note with a link.

Thanks @newlawrence for the warning and suggestion ;D

**Comment by danimtb** [comment]
I don't think this should go in the getting started and there is no general cache section describing this.

There is a new PR #895 with updated information

**Comment by jgsogo** [comment]
Yes, let's close this one. 👍
