### ISSUE TITLE
Standard options

### ISSUE THREAD

**Issue by sigiesec** [conan-io/docs#903]
I am missing information on standard package options in conan packages, which might have an effect inside conan. One option I know about for which this is the case is fPIC. It is mentioned in the docs of the cmake generator (https://github.com/conan-io/docs/blame/8c39493f974abcf9d973e11e24727f5ec290fe5f/reference/build_helpers/cmake.rst#L142), but I am missing an overview of such standard/predefined options, independent from the individual generators.

I suspect that "shared" is also such a standard option, but I am not sure.

**Comment by danimtb** [comment]
We could add a box in the options attribute saying that `shared` and `fPIC` are auto-applied in the cmake and autotools build helpers / generators

**Comment by danimtb** [comment]
fixed in #991
