### ISSUE TITLE
Example code in docs broken - Hello/0.1@memsharded/testing is missing from conan-center

### ISSUE THREAD

**Issue by nikgibbens** [conan-io/docs#908]
I am going through the documentation examples and the example-hello-world conan install fails due to a missing dependency.

[Workflows > Single Configuration](https://docs.conan.io/en/latest/using_packages/workflows.html)

```bash
conan install ./example-hello/ --build=missing --install-folder example-hello-world
Configuration:
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=5
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

Hello/0.1@memsharded/testing: Not found in local cache, looking in remotes...
Hello/0.1@memsharded/testing: Trying with 'conan-center'...
ERROR: Failed requirement 'Hello/0.1@memsharded/testing' from 'PROJECT'
ERROR: Unable to find 'Hello/0.1@memsharded/testing' in remotes
```
I searched conan-center and the packages does not exist. I did locate it in conan-transit. Once I added the remote, the example worked.

The example Hello/0.1@memsharded/testing should be moved to the main conan-center remote so the documentation is accurate or a step should be added in the documentation to add the conan-transit remote. Being that the conan-transit remote is deprecated, the former option is probably the better one.

**Comment by memsharded** [comment]
We have updated the whole section to use an example based on the Poco libraries, instead of the Hello one, so it is also more aligned with the Getting Started, do not require conan-transit, nor a Hello package.

Please have a look at: https://docs.conan.io/en/latest/using_packages/workflows.html. Thanks very much for raising this issue!
