### ISSUE TITLE
Document: Feature/reuse python requires exports #3661

### ISSUE THREAD

**Issue by lasote** [conan-io/docs#916]
https://github.com/conan-io/conan/pull/3661

**Comment by jgsogo** [comment]
Follow this issue (https://github.com/conan-io/conan/issues/4262), docs might not be needed or require some adjustments

**Comment by danimtb** [comment]
Here is the PR that will eventually remove this undocumented behavior https://github.com/conan-io/conan/pull/4340

**Comment by danimtb** [comment]
This issue is no longer valid as the feature was finally removed. This issue was open and the feature was not documented as the usage was not clear and finally the time has proven us right 🥂
