### ISSUE TITLE
Add documentation for registry.json

### ISSUE THREAD

**Issue by netpoetica** [conan-io/docs#947]
After installing `conan` via `homebrew`, using `conan` produces a warning about "creating a default" registry.json. 

```
➜  05 conan --help
WARN: Remotes registry file missing, creating default one in /Users/rosenbek/.conan/registry.json
```

No documentation can be found either on Github, Conan docs, or via web search to describe what this file is, how it should look, what properties it requires/supports (optional, defaults). The closest thing I found is this doc on [registry.txt](https://docs.conan.io/en/latest/reference/config_files/registry.txt.html), but it is not a JSON file.

I understand that this is just a warning, but it would be great if there was some example registry.json and some documentation on what the defaults are, etc.

System details:

- OS: Mac OSX High Sierra 10.13.6 (17G65)
- Conan version: 1.9.1

Contributing Checklist

- [ X ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ X ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ X ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
This was completed in #990

**Comment by shashikantjagtap7** [comment]
I also want the same information
