### ISSUE TITLE
How to extract license from headers

### ISSUE THREAD

**Issue by uilianries** [conan-io/docs#968]
I was looking for "how to extract the license from a header file".

It supposed to be in [howtos](https://docs.conan.io/en/latest/howtos.html) page, but I found in [conan center guide](https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html?highlight=extract)

Additionally, there is [collect licenses](https://docs.conan.io/en/latest/howtos/collect_licenses.html) in howtos.

Could we move or refer that trick in howtos?

**Comment by danimtb** [comment]
Yeah, I think so. Better unify the content in one how to and then link it in the conan center guide

**Comment by danimtb** [comment]
This was fixed by #970
