### ISSUE TITLE
Add doc links to Conan changelog

### ISSUE THREAD

**Issue by db4** [conan-io/docs#973]
Currently [Conan changelog](https://docs.conan.io/en/latest/changelog.html) only references PRs for new features and fixes. For fixes it's OK, but for features one would probably like to read a section in the docs describing the feature in detail. And it would be clear if such section did not exist. Say, I would like to know what is
- Feature: Support for `srcdirs` in `package_info()`. Packages can package sources, and specify their location, which will be propagated to consumers. Includes support for CMake generator. [#3857](https://github.com/conan-io/conan/pull/3857)

But docs on the feature seem to be missing; if a doc link were required it would not happen.

**Comment by danimtb** [comment]
Hi @db4 

You are totally right.

We thought about it and looked at other similar opensource projects and providing a kind of "automatic" links to the docs it is not strightforward right now. However, we try to include in the information of the PR a link to the changes in the documentation that new features include.

In this case it seems that the PR to the docs is missing and obviusly is impossible to find the changes in the PR link to the conan code.

We will try to reconsider incluing a link to the new docs for every feature at least.

Thanks a lot for the feedback!

**Comment by memsharded** [comment]
This has been implemented, check the latest changelog: https://docs.conan.io/en/latest/changelog.html

Thanks for the suggestion!
